### ISSUE TITLE
Fix unclear message when credential files do not comply with specification

### ISSUE THREAD

**Issue by museadmin** [aws/aws-toolkit-jetbrains#1010]
**Describe the bug**
When updating PyCharm an error is thrown for failure to load AWS credentials

**To reproduce**
1 - Accept an upgrade to PyCharm
2 - The PyCharm restarts, an error is reported. See stack trace below

**Expected behavior**
No error reported

**Your Environment**
 - OS: Mac OS Mojave 10.14.5
 - JetBrains' Product: PyCharm Community Edition
 - JetBrains' Product Version: 
**PyCharm 2019.1.3 (Community Edition)
Build #PC-191.7479.30, built on May 29, 2019
JRE: 11.0.2+9-b159.60 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5**
 - Toolkit Version: v1.3
 - SAM CLI Version: ?
 - JVM/Python Version: 3.7

**Additional context**
Failed to load AWS profiles

java.lang.IllegalArgumentException: Expected an '=' sign defining a property on line 26
	at software.amazon.awssdk.utils.Validate.isTrue(Validate.java:76)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.parsePropertyDefinition(ProfileFileReader.java:249)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.readPropertyDefinitionLine(ProfileFileReader.java:131)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.parseLine(ProfileFileReader.java:77)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.lambda$parseFile$0(ProfileFileReader.java:57)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at software.amazon.awssdk.profiles.internal.ProfileFileReader.parseFile(ProfileFileReader.java:57)
	at software.amazon.awssdk.profiles.ProfileFile$BuilderImpl.build(ProfileFile.java:261)
	at software.amazon.awssdk.profiles.ProfileFile.lambda$addConfigFile$1(ProfileFile.java:147)
	at java.util.Optional.ifPresent(Optional.java:159)
	at software.amazon.awssdk.profiles.ProfileFile.addConfigFile(ProfileFile.java:144)
	at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
	at software.amazon.awssdk.profiles.ProfileFile.defaultProfileFile(ProfileFile.java:88)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileToolkitCredentialsProviderFactory$loadFromProfileFile$profiles$1.invoke(ProfileToolkitCredentialsProviderFactory.kt:45)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileToolkitCredentialsProviderFactory$loadFromProfileFile$profiles$1.invoke(ProfileToolkitCredentialsProviderFactory.kt:22)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull(LogUtils.kt:18)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull$default(LogUtils.kt:17)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileToolkitCredentialsProviderFactory.loadFromProfileFile(ProfileToolkitCredentialsProviderFactory.kt:44)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileToolkitCredentialsProviderFactory.<init>(ProfileToolkitCredentialsProviderFactory.kt:31)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.createToolkitCredentialProviderFactory(ProfileCredentialProviderFactory.kt:14)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.createToolkitCredentialProviderFactory(ProfileCredentialProviderFactory.kt:13)
	at software.aws.toolkits.jetbrains.core.credentials.ExtensionPointCredentialsProviderRegistry.listFactories(ExtensionPointCredentialsProviderRegistry.kt:44)
	at software.aws.toolkits.jetbrains.core.credentials.ExtensionPointCredentialsProviderRegistry.listFactories(ExtensionPointCredentialsProviderRegistry.kt:37)
	at software.aws.toolkits.core.credentials.DefaultToolkitCredentialsProviderManager.reloadFactories(ToolkitCredentialsProviderManager.kt:85)
	at software.aws.toolkits.core.credentials.DefaultToolkitCredentialsProviderManager.<init>(ToolkitCredentialsProviderManager.kt:42)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager.<init>(CredentialManager.kt:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:210)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$Companion.getInstance(CredentialManager.kt:27)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultProjectAccountSettingsManager.<init>(ProjectAccountSettingsManager.kt:134)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultProjectAccountSettingsManager.<init>(ProjectAccountSettingsManager.kt:123)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:210)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:30)
	at software.aws.toolkits.jetbrains.core.credentials.ProjectAccountSettingsManager$Companion.getInstance(ProjectAccountSettingsManager.kt:106)
	at software.aws.toolkits.jetbrains.core.AwsSettingsPanel.<init>(AwsSettingsPanel.kt:49)
	at software.aws.toolkits.jetbrains.core.AwsSettingsPanelInstaller.runActivity(AwsSettingsPanel.kt:42)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAndMeasure(StartupManagerImpl.java:164)
	at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:138)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:356)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$2(StartupManagerImpl.java:170)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:370)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:362)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by museadmin** [comment]
After further investigation, this was actually complaining about my having spaces around the = in my was credentials files. When I removed the spaces my profiles appeared in the IDE and it prompted me for my token.

I would suggest that you handle spaces, as everything else seems happy with them.

Either way, you are currently urging users to raise an issue when this happens and presenting them with a stack trace.

**Comment by abrooksv** [comment]
We use the Java SDK v2 to do the parsing and according to our spec, spaces are allowed.

The line format is `Identifier Whitespace? = Whitespace? Value? Whitespace? (Whitespace CommentLine)?` so I would need to see what line 26 was to see why is was unhappy. It could just be a bug.

**Comment by abrooksv** [comment]
We should also swallow the stack trace and show a better UX around failing to parse similar to how we do it for ignored profiles.

**Comment by museadmin** [comment]
Thanks for looking at this. 

Turns out that the role_arn line on line 26 had a : character after it. So a typo in my part that I didn't spot. 

Strangely when I removed the spaces on this new profile I'd added, PyCharm stopped reporting an error and I could see all of my profiles in the IDE. Later, when I was having issues switching role, I then spotted I also had the duff character.

Unfortunately I'm on a different laptop at the moment but I think the line looked like this:

role_arn: = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx etc.

**Comment by abrooksv** [comment]
Ah, the identifier regex is `[A-Za-z0-9\-_]+`. It would probably have made more sense to tell you that it did not match that regex instead of the space issue. I will leave this open as a feature request to fix the stack trace issues. I can't improve the message itself without a PR out to the Java SDK

**Comment by abrooksv** [comment]
I did `role_arn:= arn:aws:iam:` and `role_arn: = arn:aws:` and both load the file but report `Profile 'foo' is not using role-based, session-based, or basic credentials upon refresh.

**Comment by abrooksv** [comment]
I can trigger it if I have a row with just `foo` on it though. So, we should fix it no matter what so that it shows the Profiles Failed to Load notification and more info box can pass through the SDK's error, in this case `Expected an '=' sign defining a property on line X`

**Comment by abrooksv** [comment]
Improved error message will be in next release
