### ISSUE TITLE
AWS Toolkit 1.3 plugin in PyCharm 2019.1.3 crashed without reason

### ISSUE THREAD

**Issue by micgrivas** [aws/aws-toolkit-jetbrains#1012]
In PyCharm 2019.1.3 , the AWS Toolkit 1.3 is installed and appeared to crash suddenly. 
No intentional usage of the plugin.  Stack-trace: 

Details: Current thread: Thread[ApplicationImpl pooled thread 41,4,Idea Thread Group] 979934015
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1397423446

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1087)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:173)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.getDocument(RangeMarkerImpl.java:139)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.registerInTree(RangeMarkerImpl.java:88)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:83)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:50)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:508)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:243)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:365)
	at com.intellij.codeInsight.daemon.impl.FileStatusMap.combineScopes(FileStatusMap.java:247)
	at com.intellij.codeInsight.daemon.impl.FileStatusMap.access$300(FileStatusMap.java:46)
	at com.intellij.codeInsight.daemon.impl.FileStatusMap$FileStatus.lambda$combineScopesWith$0(FileStatusMap.java:128)
	at gnu.trove.TIntObjectHashMap.transformValues(TIntObjectHashMap.java:628)
	at com.intellij.codeInsight.daemon.impl.FileStatusMap$FileStatus.combineScopesWith(FileStatusMap.java:127)
	at com.intellij.codeInsight.daemon.impl.FileStatusMap$FileStatus.access$900(FileStatusMap.java:97)
	at com.intellij.codeInsight.daemon.impl.FileStatusMap.markFileScopeDirty(FileStatusMap.java:239)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.restart(DaemonCodeAnalyzerImpl.java:577)
	at software.aws.toolkits.jetbrains.services.lambda.upload.LambdaLineMarker$handlerInRemote$2.accept(LambdaLineMarker.kt:106)
	at software.aws.toolkits.jetbrains.services.lambda.upload.LambdaLineMarker$handlerInRemote$2.accept(LambdaLineMarker.kt:32)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$lambdaFunctions$2.run(AwsResourceCache.kt:63)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by abrooksv** [comment]
Need to wrap call in a `runReadAction`
