### ISSUE TITLE
PyCharm crashes when creating nodejs project

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#1064]
**Describe the bug**
Plugin artifact from webstorm branch doesn't work on PyCharm when creating nodejs project with the following exception on project creation.

```
java.lang.ClassCastException: class com.intellij.openapi.module.UnknownModuleType cannot be cast to class com.intellij.openapi.module.WebModuleTypeBase (com.intellij.openapi.module.UnknownModuleType and com.intellij.openapi.module.WebModuleTypeBase are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @1d16f93d)
	at com.intellij.openapi.module.WebModuleTypeBase.getInstance(WebModuleTypeBase.java:24)
	at software.aws.toolkits.jetbrains.services.lambda.nodejs.NodeJsRuntimeGroup.getModuleType(NodeJsRuntimeGroup.kt:44)
	at software.aws.toolkits.jetbrains.services.lambda.RuntimeGroup$getModuleType$1.invoke(RuntimeGroup.kt:46)
	at software.aws.toolkits.jetbrains.services.lambda.RuntimeGroup$getModuleType$1.invoke(RuntimeGroup.kt:31)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:129)
	at software.aws.toolkits.jetbrains.services.lambda.RuntimeGroup.getModuleType(RuntimeGroup.kt:46)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectBuilder.setupRootModel(SamProjectGeneratorIntelliJShims.kt:51)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator$generateProject$$inlined$runInEdt$lambda$1.compute(actions.kt:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$19(ApplicationImpl.java:1064)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1020)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1064)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:141)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:33)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.lambda$doGenerateProject$2(AbstractNewProjectStep.java:202)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:266)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:207)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$AbstractCallback.consume(AbstractNewProjectStep.java:161)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.actionPerformed(ProjectSettingsStepBase.java:135)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
 - OS: 
 - JetBrains' Product:
 - JetBrains' Product Version:
 - Toolkit Version:
 - SAM CLI Version:
 - JVM/Python Version:

**Additional context**

**Comment by zhangzhx** [comment]
This was fixed in the latest webstorm branch.
