### ISSUE TITLE
Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider:

### ISSUE THREAD

**Issue by jebricker** [aws/aws-toolkit-jetbrains#1105]
An error after the most recent IntelliJ update 

IntelliJ 2019.2 Ultimate Build
 Build #IU- 192-5728.98 built  on July 23 2019

Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: aws_lambda-_Local_ HelloWorldFunction_ factoryName_ Local.xml

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.createAsDataClass(ReflectionUtil.java:469)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:402)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:376)
	at com.intellij.execution.configurations.RunConfigurationBase.createOptions(RunConfigurationBase.java:57)
	at com.intellij.execution.configurations.RunConfigurationBase.<init>(RunConfigurationBase.java:52)
	at com.intellij.execution.configurations.LocatableConfigurationBase.<init>(LocatableConfigurationBase.java:19)
	at software.aws.toolkits.jetbrains.services.lambda.execution.LambdaRunConfigurationBase.<init>(LambdaRunConfigurationBase.kt:27)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfiguration.<init>(LocalLamdaRunConfiguration.kt:50)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfigurationFactory.createTemplateConfiguration(LocalLamdaRunConfiguration.kt:42)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfigurationFactory.createTemplateConfiguration(LocalLamdaRunConfiguration.kt:41)
	at com.intellij.execution.configurations.ConfigurationFactory.createTemplateConfiguration(ConfigurationFactory.java:65)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:185)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:65)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:48)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:22)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:62)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:176)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:194)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:43)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:48)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:192)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.reload(SchemeManagerImpl.kt:253)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:617)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:62)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:405)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:355)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:122)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:97)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:44)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:248)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:197)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:231)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:49)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.requestLoadWorkspaceAndProjectRunConfiguration(ProjectRunConfigurationInitializer.kt:47)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.access$requestLoadWorkspaceAndProjectRunConfiguration(ProjectRunConfigurationInitializer.kt:24)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$1.projectComponentsInitialized(ProjectRunConfigurationInitializer.kt:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:102)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:446)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:242)
	at com.sun.proxy.$Proxy58.projectComponentsInitialized(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:270)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:285)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:599)
	at com.intellij.platform.PlatformProjectOpenProcessor.tryLoadProject(PlatformProjectOpenProcessor.java:280)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareAndOpenProject(PlatformProjectOpenProcessor.java:254)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$doOpenProject$0(PlatformProjectOpenProcessor.java:198)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:552)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.util.ReflectionUtil.createAsDataClass(ReflectionUtil.java:445)
	... 75 more
Caused by: java.lang.NoSuchMethodError: com.intellij.openapi.components.BaseState.map$default(Lcom/intellij/openapi/components/BaseState;Ljava/util/Map;ILjava/lang/Object;)Lcom/intellij/openapi/components/StoredPropertyBase;
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.FunctionOptions.<init>(LocalLambdaOptions.kt:26)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaOptions.<init>(LocalLambdaOptions.kt:14)
	... 80 more

**Comment by abrooksv** [comment]
What version are you on? We have not released 2019.2 support into a stable release yet.

**Comment by jebricker** [comment]
From the top of the message:
IntelliJ 2019.2 Ultimate Build
Build #IU- 192-5728.98 built on July 23 2019

Just updated this morning

**Comment by abrooksv** [comment]
Sorry, what version of the toolkit?

**Comment by jebricker** [comment]
AWS Toolkit 1.4

**Comment by abrooksv** [comment]
Okay. Our eap builds should support it. We are putting the final touches on the stable build now.

**Comment by abrooksv** [comment]
1.5 is out and is pending JetBrains' approval on the marketplace
