### ISSUE TITLE
IDE Fatal Error with 1.5

### ISSUE THREAD

**Issue by jonfreedman** [aws/aws-toolkit-jetbrains#1124]
**Describe the bug**
IntelliJ reports a fatal error with AWS Toolkit 1.5 when indexing a spring boot project

```java
Error while indexing <snip>\src\main\resources\application.yml
To reindex this file IDEA has to be restarted

java.lang.IllegalStateException: There should only be 1 YAML document per file
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate.getTemplateRoot(YamlCloudFormationTemplate.kt:34)
	
```

**Expected behavior**
No errors

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: IntellilJ
 - JetBrains' Product Version: 2019.2
 - Toolkit Version: 1.5
 - SAM CLI Version: aws-cli/1.16.198 Python/3.6.0 Windows/10 botocore/1.12.188
 - JVM/Python Version: 1.8.0_181

**Comment by abrooksv** [comment]
Ah ya, that should be logged as a warning and not shown to you. Thank you

**Comment by abrooksv** [comment]
Also to confirm: that is not a CFN template, correct?

**Comment by jonfreedman** [comment]
Yes the yml file in question is a spring boot config

**Comment by csf6mlp** [comment]
Additional instance of this issue:

Symptoms: 
Event log flashing red error, after selecting and clearing all events, Run/Debug Configuration menu is unresponsive. Need to restart the IDE / re-open the project.

Note: Downgrading the AWS Toolkit plugin to v1.3 and downgrading the IDE to v2019.1, presents no resolution. Not using any template, just free text or linked file.

Environment:
OS: macOS Mojave
JetBrains Product: IntelliJ IDEA : v2019.1
AWS Toolkit Plugin : v1.5
SAM CLI: v0.16.1
JDK: v1.8.0_211

Observation: There are two *.yaml files in the AWS Toolkit build folder. One generate from the plugin and the other from the originating project as the application.yml.

**Comment by mogren** [comment]
I have the same problem, from an old kubernetes config, [aws-k8s-cni.yaml](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.0/aws-k8s-cni.yaml):
```
Error while indexing /amazon-vpc-cni-k8s/config/v1.0/aws-k8s-cni.yaml
To reindex this file IDEA has to be restarted

java.lang.IllegalStateException: There should only be 1 YAML document per file
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate.getTemplateRoot(YamlCloudFormationTemplate.kt:34)
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate.<init>(YamlCloudFormationTemplate.kt:29)
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate$Companion.convertPsiToResource(YamlCloudFormationTemplate.kt:126)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1$1.visitElement(CloudFormationTemplateIndex.kt:67)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLScalarImpl.accept(YAMLScalarImpl.java:183)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.access$acceptNode(CloudFormationTemplateIndex.kt:87)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:60)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:30)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:313)
```

**Comment by jonfreedman** [comment]
It seems this bug is preventing me from being able to even run a Spring Boot configuration from within IntelliJ

I've disabled the plugin until this is fixed

**Comment by abrooksv** [comment]
Fix is in PR

**Comment by G-Rath** [comment]
I'm getting this in a PHP composer based project, but w/o the `Error while indexing part`.

It seems that something about the structure of composer projects triggers the aws toolkit, making it think that it should be doing something to something when it shouldn't.

This is the same project that caused #1157

**Comment by abrooksv** [comment]
Our 1.6-EAP.2019.08.14 contains the fix: https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/67195

Direct download / One time install: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=67195
Opt-in instructions for EAP channel: aws/aws-toolkit-jetbrains#eap-builds
