### ISSUE TITLE
Bug: Open Template Hello World SAM Project & System Does Not Load

### ISSUE THREAD

**Issue by pjonson2** [aws/aws-toolkit-jetbrains#1126]
My environment:

 - OS: Mojave 10.14.5 macOS
 - JetBrains' Product: Pycharm Professional 
 - JetBrains' Product Version: 2019.2
 - Toolkit Version: 1.5
 - SAM CLI Version:  0.14.2
 - JVM/Python Version: 3.6

When I open pycharm the following bug is thrown. I set the virtual env to python 3.6 but my mac is running python 2.7. How do I get pycharm to run python 3.6 where I can use the aws tool kit?

ava.lang.AssertionError: Background task can't be run under write action
	at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:140)
	at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:94)
	at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:84)
	at com.jetbrains.python.sdk.PySdkUtil.getProcessOutput(PySdkUtil.java:76)
	at com.jetbrains.python.sdk.flavors.PythonSdkFlavor.getVersionString(PythonSdkFlavor.java:175)
	at com.jetbrains.python.sdk.flavors.PythonSdkFlavor.getLanguageLevel(PythonSdkFlavor.java:232)
	at com.jetbrains.python.packaging.PyPackageManagerImpl.a(PyPackageManagerImpl.java:353)
	at com.jetbrains.python.packaging.PyPackageManagerImpl.createVirtualEnv(PyPackageManagerImpl.java:298)
	at com.jetbrains.python.sdk.add.PyAddNewVirtualEnvPanel$getOrCreateSdk$task$1.compute(PyAddNewVirtualEnvPanel.kt:92)
	at com.jetbrains.python.sdk.add.PyAddNewVirtualEnvPanel$getOrCreateSdk$task$1.compute(PyAddNewVirtualEnvPanel.kt:87)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:321)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:531)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:459)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runSynchronously(CoreProgressManager.java:324)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:309)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:198)
	at com.jetbrains.python.sdk.PySdkExtKt.createSdkByGenerateTask(PySdkExt.kt:80)
	at com.jetbrains.python.sdk.add.PyAddNewVirtualEnvPanel.getOrCreateSdk(PyAddNewVirtualEnvPanel.kt:97)
	at com.jetbrains.python.newProject.steps.PyAddNewEnvironmentPanel.getOrCreateSdk(PyAddNewEnvironmentPanel.kt:77)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel.getSdk(PyCharmSdkSelectionPanel.kt:92)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel.getSdkSettings(PyCharmSdkSelectionPanel.kt:84)
	at software.aws.toolkits.jetbrains.ui.wizard.SamInitSelectionPanel.getNewProjectSettings(SamInitSelectionPanel.java:178)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGeneratorSettingsPeer.getSettings(SamProjectGenerator.kt:114)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectBuilder.setupRootModel(SamProjectGeneratorIntelliJShims.kt:46)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator$generateProject$$inlined$runInEdt$lambda$1.compute(actions.kt:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$16(ApplicationImpl.java:1004)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:982)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1004)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:141)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:33)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.lambda$doGenerateProject$2(AbstractNewProjectStep.java:204)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:215)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:209)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$AbstractCallback.consume(AbstractNewProjectStep.java:163)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.lambda$actionPerformed$0(ProjectSettingsStepBase.java:137)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:148)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.actionPerformed(ProjectSettingsStepBase.java:137)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by cverlo** [comment]
I am encountering the same error message.   

Pycharm Community 2019.2 on Windows 10 Pro with Python 3.7

**Comment by pThonprogrammer** [comment]
I am also having this issue with Pycharm Community 2019.2 on Windows 10 Pro with Python 3.7 and python 3.6.

**Comment by harish-kamath** [comment]
I have the same problem. Pycharm 2019.2 Professional Edition, Mac Mojave with Python 3.6

**Comment by markkauffman2000** [comment]
Ditto. Mac OS X - High Sierra, Tried both Python 3.6 & 3.7.

**Comment by legoodfellow** [comment]
Same issue for me with Pycharm Professional 2019.2, High Sierra, and Python 3.7

**Comment by brendankeane** [comment]
Same issue.  Ubuntu, PyCharm CE 2019.2, AWS 1.5, Python 3.7

**Comment by abrooksv** [comment]
Our 1.6-EAP.2019.08.14 contains the fix: https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/67195

Direct download / One time install: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=67195
Opt-in instructions for EAP channel: https://github.com/aws/aws-toolkit-jetbrains#eap-builds

**Comment by caoyuanbin** [comment]
I am encountering the same error
PyCharm 2019.2
Mac OS X
JDK: 11.0.3;

**Comment by aarsanjani** [comment]
Same error

**Comment by abrooksv** [comment]
These issues should be fixed in v1.6, please re-open if still facing issues
