### ISSUE TITLE
Memory leak in PyCharmSdkSelectionPanel

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#1129]
Looks like the `ProjectSpecificSettingsStep` needs to be disposed properly

https://github.com/aws/aws-toolkit-jetbrains/blob/master/jetbrains-core/src/software/aws/toolkits/jetbrains/ui/wizard/PyCharmSdkSelectionPanel.kt#L37

```
2019-07-31 16:04:22,839 [  71353]  ERROR - api.util.objectTree.ObjectTree - Memory leak detected: 'AWS Serverless Application (null)' of class software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel$newSdkPanel$1
See the cause for the corresponding Disposer.register() stacktrace:
 
java.lang.RuntimeException: Memory leak detected: 'AWS Serverless Application (null)' of class software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel$newSdkPanel$1
See the cause for the corresponding Disposer.register() stacktrace:

	at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:236)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:149)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:145)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:234)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:769)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:744)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:733)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:729)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:696)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:691)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$3.windowClosing(WelcomeFrame.java:111)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.objectTree.ObjectNode.<init>(ObjectNode.java:54)
	at com.intellij.openapi.util.objectTree.ObjectTree.createNodeFor(ObjectTree.java:108)
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:72)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:92)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.createPanel(ProjectSettingsStepBase.java:91)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel$newSdkPanel$1.createPanel(PyCharmSdkSelectionPanel.kt:48)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel.newSdkPanel(PyCharmSdkSelectionPanel.kt:60)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel.access$newSdkPanel(PyCharmSdkSelectionPanel.kt:28)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel$sdkSelectionPanel$2.invoke(PyCharmSdkSelectionPanel.kt:31)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel$sdkSelectionPanel$2.invoke(PyCharmSdkSelectionPanel.kt:28)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel.getSdkSelectionPanel(PyCharmSdkSelectionPanel.kt)
	at software.aws.toolkits.jetbrains.ui.wizard.PyCharmSdkSelectionPanel.getSdkSelectionPanel(PyCharmSdkSelectionPanel.kt:28)
	at software.aws.toolkits.jetbrains.ui.wizard.SamInitSelectionPanel.addSdkPanel(SamInitSelectionPanel.java:95)
	at software.aws.toolkits.jetbrains.ui.wizard.SamInitSelectionPanel.runtimeUpdate(SamInitSelectionPanel.java:91)
	at software.aws.toolkits.jetbrains.ui.wizard.SamInitSelectionPanel.<init>(SamInitSelectionPanel.java:63)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGeneratorSettingsPeer$samInitSelectionPanel$2.invoke(SamProjectGenerator.kt:108)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGeneratorSettingsPeer$samInitSelectionPanel$2.invoke(SamProjectGenerator.kt:107)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGeneratorSettingsPeer.getSamInitSelectionPanel(SamProjectGenerator.kt)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGeneratorSettingsPeer.getComponent(SamProjectGenerator.kt:136)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGeneratorSettingsPeer.buildUI(SamProjectGenerator.kt:124)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.createAndFillContentPanel(ProjectSettingsStepBase.java:245)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.createPanel(ProjectSettingsStepBase.java:92)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.lambda$null$1(FlatWelcomeFrame.java:983)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.lambda$createActionGroupPanel$2(FlatWelcomeFrame.java:983)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1802)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1816)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.JList.setValueIsAdjusting(JList.java:2146)
	at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(BasicListUI.java:2796)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:818)
	... 9 more
2019-07-31 16:04:22,848 [  71362]  ERROR - api.util.objectTree.ObjectTree - PyCharm 2019.2  Build #PY-192.5728.105 
2019-07-31 16:04:22,850 [  71364]  ERROR - api.util.objectTree.ObjectTree - JDK: 1.8.0_202; VM: Java HotSpot(TM) 64-Bit Server VM; Vendor: Oracle Corporation 
2019-07-31 16:04:22,886 [  71400]  ERROR - api.util.objectTree.ObjectTree - OS: Mac OS X 
2019-07-31 16:04:22,888 [  71402]  ERROR - api.util.objectTree.ObjectTree - Plugin to blame: AWS Toolkit version: 1.6-SNAPSHOT 
```

**Comment by xylo** [comment]
Does someone understand this?   Isn't Disposer.register() used to clean up resources?  How can a clean up (this function) throw a memory leak error while if you omit the cleaning you don't get this error and everything looks fine.

**Comment by abrooksv** [comment]
Disposer.register adds it to a parent->child tree of Disposables. You then have to call Disposer.dispose(parent), and that will dispose the subtree of the disposer tree.

What looks to be happening is IntelliJ is disposing the Application on exit (which should be the last root in the tree), and is then saying, "Hey, this root is still in the tree after everything is closed, you leaked something".

It doesn't affect the functionality, we just keep things in memory we should not be. Hope that clears it up.

**Comment by xylo** [comment]
@abrooksv Thanks. I think I used Disposer.register() in a wrong way then.

**Comment by hunterwerlla** [comment]
Looked at this a bit, and it is a big pain because it has to probably be plumbed all the way up to `SamProjectGenerator`
