### ISSUE TITLE
tons of java.lang.IllegalStateException: Template does not start with a mapping

### ISSUE THREAD

**Issue by G-Rath** [aws/aws-toolkit-jetbrains#1157]
**Describe the bug**
aws toolkit repeatedly throws an exception.

For now I don't know how to reproduce it exactly - I'll update this issue if I figure out the steps.

I can say that I was working on a PHP project when this happened, of which I'd just run `composer install`, and then triggered a project sync - so it started indexing libraries from `vendor`.

It triggered a *lot* - to the point where I think it soft-froze my IJ requiring me to crash it.

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: IntelliJ Ultimate
 - JetBrains' Product Version: IntelliJ IDEA 2019.2  Build #IU-192.5728.98
 - Toolkit Version: 1.6-EAP.2019.08.01
 - SAM CLI Version:
 - JVM/Python Version: JDK: 11.0.2; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 

The stacktraces are typically all the same, except some of them have a line at the top, such as:

> During querying provider Run line marker (class com.intellij.execution.lineMarker.RunLineMarkerProvider)

or

> In file: file://C:/Users/G-Rath/workspace/projects-ackama/madison_api/vendor/sentry/sentry/src/Breadcrumb.php

These were two stacktraces I copied out before my IJ crashed, and I looked at the log and realised it was b/c of so many exceptions happening:
<details>
<summary>Stacktrace</summary>

```
java.lang.IllegalStateException: Template does not start with a mapping
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate.getTemplateRoot(YamlCloudFormationTemplate.kt:38)
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate.<init>(YamlCloudFormationTemplate.kt:29)
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate$Companion.convertPsiToResource(YamlCloudFormationTemplate.kt:126)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1$1.visitElement(CloudFormationTemplateIndex.kt:67)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLScalarImpl.accept(YAMLScalarImpl.java:183)
	at org.jetbrains.yaml.psi.impl.YAMLScalarTextImpl.accept(YAMLScalarTextImpl.java:132)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.access$acceptNode(CloudFormationTemplateIndex.kt:87)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:60)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:30)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:313)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:108)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:269)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:251)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1603)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:634)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1562)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1549)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1528)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1699)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1696)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:76)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:46)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1718)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:736)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:702)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:306)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:282)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:121)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:109)
	at org.jetbrains.plugins.groovy.lang.stubs.GroovyShortNamesCache.getClassesByFQName(GroovyShortNamesCache.java:79)
	at org.jetbrains.plugins.groovy.lang.psi.impl.javaView.GroovyClassFinder.findClass(GroovyClassFinder.java:43)
	at org.jetbrains.plugins.groovy.lang.psi.impl.javaView.GroovyLightInnerClassFinder.findClass(GroovyLightInnerClassFinder.kt:20)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:116)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:93)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.lambda$nullabilityAnnotationsNotAvailable$0(NullableStuffInspectionBase.java:415)
	at com.intellij.util.containers.ContainerUtilRt.find(ContainerUtilRt.java:475)
	at com.intellij.util.containers.ContainerUtilRt.find(ContainerUtilRt.java:468)
	at com.intellij.util.containers.ContainerUtil.find(ContainerUtil.java:946)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.nullabilityAnnotationsNotAvailable(NullableStuffInspectionBase.java:415)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.buildVisitor(NullableStuffInspectionBase.java:81)
	at com.intellij.codeInspection.LocalInspectionTool.buildVisitor(LocalInspectionTool.java:123)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:53)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1101)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:58)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:268)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:200)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
</details>

<details>
<summary>Stacktrace</summary>

```
During querying provider Run line marker (class com.intellij.execution.lineMarker.RunLineMarkerProvider)

java.lang.IllegalStateException: Template does not start with a mapping
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate.getTemplateRoot(YamlCloudFormationTemplate.kt:38)
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate.<init>(YamlCloudFormationTemplate.kt:29)
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate$Companion.convertPsiToResource(YamlCloudFormationTemplate.kt:126)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1$1.visitElement(CloudFormationTemplateIndex.kt:67)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLScalarImpl.accept(YAMLScalarImpl.java:183)
	at org.jetbrains.yaml.psi.impl.YAMLScalarTextImpl.accept(YAMLScalarTextImpl.java:132)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:94)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.access$acceptNode(CloudFormationTemplateIndex.kt:87)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:60)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:30)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:313)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:108)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:269)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:251)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1673)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1603)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:634)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1562)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1549)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1528)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1699)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1696)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:76)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:46)
	at com.intellij.util.indexing.FileBasedIndexImpl.forceUpdate(FileBasedIndexImpl.java:1718)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:736)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:702)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:306)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:282)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:121)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:109)
	at com.jetbrains.php.PhpIndexImpl.getByName(PhpIndexImpl.java:807)
	at com.jetbrains.php.PhpIndexImpl.getByFQN(PhpIndexImpl.java:787)
	at com.jetbrains.php.PhpIndexImpl.getInterfacesByFQN(PhpIndexImpl.java:847)
	at com.jetbrains.php.PhpClassHierarchyUtils$4.appendNextElements(PhpClassHierarchyUtils.java:70)
	at com.jetbrains.php.PhpClassHierarchyUtils$4.appendNextElements(PhpClassHierarchyUtils.java:64)
	at com.jetbrains.php.PhpClassHierarchyUtils$8.appendNextElements(PhpClassHierarchyUtils.java:114)
	at com.jetbrains.php.PhpClassHierarchyUtils$8.appendNextElements(PhpClassHierarchyUtils.java:109)
	at com.jetbrains.php.PhpClassHierarchyUtils.process(PhpClassHierarchyUtils.java:143)
	at com.jetbrains.php.PhpClassHierarchyUtils.processSupers(PhpClassHierarchyUtils.java:171)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl.findMethodByName(PhpClassImpl.java:893)
	at com.jetbrains.php.phpunit.PhpUnitUtil.isTestClass(PhpUnitUtil.java:94)
	at com.jetbrains.php.phpunit.PhpUnitUtil.lambda$isTestClass$2(PhpUnitUtil.java:85)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at com.jetbrains.php.phpunit.PhpUnitUtil.isTestClass(PhpUnitUtil.java:85)
	at com.jetbrains.php.phpunit.PhpUnitUtil.isTestMethodInternal(PhpUnitUtil.java:175)
	at com.jetbrains.php.phpunit.PhpUnitUtil.isTestMethod(PhpUnitUtil.java:160)
	at com.jetbrains.php.phpunit.PhpUnitTestRunLineMarkerProvider.getInfo(PhpUnitTestRunLineMarkerProvider.java:32)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:171)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:96)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
</details>

I posted all the stacktraces from the log, but I hit the 65536 character limit, so I've put [them in a gist](https://gist.githubusercontent.com/G-Rath/d3385612f5d96cc08949962c650c08ea/raw/ddbc5602cd9e73b2278a6884275bf222a98fb06e/aws-toolkit%2520plugin%2520exception%2520logs).

**Comment by zhangzhx** [comment]
Do you have any yaml files (files ending with `.yml` or `.yaml`) in your project? #1152 could potentially fix the issue.

**Comment by G-Rath** [comment]
For sure - there's at least one `.yml` file in the vendor directory :)

vendors being vendors, at least one of them has shipped their library w/ it's `travis.yml` :joy:

**Comment by zhangzhx** [comment]
Ah, that should be the root cause that the travis yaml file is not a valid CloudFormation's yaml file. The CR posted above should fix this issue.

**Comment by G-Rath** [comment]
Awesome, I figured it was that, and that it was probably already fixed, but wanted to get it tracked against an issue to prevent duplication :)

`travis.yml` is the one I confirmed being there, but I'm sure there are other `YAML` files.

Any idea of an ETA on a fix? I've actually had to disable this plugin for now due to the amount of exceptions I'd get (not just this one either).

**Comment by zhangzhx** [comment]
I don't have an ETA for now, but we'll release the fix into an EAP version first. Stay tuned. I'll let you know once it is released.

**Comment by abrooksv** [comment]
Our 1.6-EAP.2019.08.14 contains the fix: https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/67195

Direct download / One time install: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=67195
Opt-in instructions for EAP channel: https://github.com/aws/aws-toolkit-jetbrains#eap-builds
