### ISSUE TITLE
Toolkit throws unhandled exception "No active credential provider configured" on startup

### ISSUE THREAD

**Issue by zhangzhx** [aws/aws-toolkit-jetbrains#1161]
**Describe the bug**
The toolkit throws unhandled exception when 

**To reproduce**
1. Create a new SAM project.
2. Toolkit throws an exception when no active credential is configured.

**Expected behavior**
No exception is thrown.

**Screenshots**
```
software.aws.toolkits.core.credentials.CredentialProviderNotFound: No active credential provider configured
	at software.aws.toolkits.jetbrains.core.credentials.DefaultProjectAccountSettingsManager.getActiveCredentialProvider(ProjectAccountSettingsManager.kt:155)
	at software.aws.toolkits.jetbrains.core.credentials.ProjectAccountSettingsManagerKt.activeCredentialProvider(ProjectAccountSettingsManager.kt:115)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerNode.<init>(AwsExplorerNode.kt:22)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerServiceRootNode.<init>(AwsExplorerServiceRootNode.kt:15)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.CacheBackedAwsExplorerServiceRootNode.<init>(AwsExplorerServiceRootNode.kt:24)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationServiceNode.<init>(CloudFormationExplorerNodes.kt:33)
	at software.aws.toolkits.jetbrains.core.explorer.AwsExplorerService$CLOUDFORMATION.buildServiceRootNode(AwsExplorerService.kt:18)
	at software.aws.toolkits.jetbrains.core.explorer.AwsExplorerService$CLOUDFORMATION.buildServiceRootNode(AwsExplorerService.kt:17)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerRootNode.getChildren(AwsExplorerRootNode.kt:22)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerRootNode.getChildren(AwsExplorerRootNode.kt:16)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:37)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:414)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:332)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:326)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:346)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:582)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:476)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:442)
	at software.aws.toolkits.jetbrains.ui.tree.Command$Processor.lambda$process$1(Command.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker.invokeSafely(Invoker.java:147)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker.lambda$invokeLater$0(Invoker.java:93)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:306)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Your Environment**
 - OS: 
 - JetBrains' Product:
 - JetBrains' Product Version:
 - Toolkit Version:
 - SAM CLI Version:
 - JVM/Python Version:

**Additional context**

**Comment by zhangzhx** [comment]
The fix was merged into master. Closing.
