### ISSUE TITLE
Unable to create new project (aws usage...)

### ISSUE THREAD

**Issue by glebsap** [aws/aws-toolkit-jetbrains#1168]
**Describe the bug**
PyCharm new project wizard doesn't allow for creation of new AWS project. Instead it only shows the notice at bottom (see screenshot) "usage: aws [options] <command> <subcommand> ..." and the "create" button is grayed out.

![](https://intellij-support.jetbrains.com/hc/user_images/GYAgEN0C3o5aJfTLmo5J1w.jpeg)

**To reproduce**
1. Open PyCharm
2. Launch "Create new project" Wizard
3. Select "AWS Serverless Application"
4. Hit "create"

**Expected behavior**
New AWS Serverless Application project is created

**Screenshots**

**Your Environment**
Install
2. Install AWS CLI latest via pip3: aws-cli/1.16.220 Python/3.7.4 Darwin/18.7.0 botocore/1.12.210
3. Install SAM CLI, 
4. Install AWS Toolkit (latest version: 1.5)
 - OS: MacOS X 10.14.6
 - JetBrains' Product: PyCharm Professional
 - JetBrains' Product Version: 2019.2
 - Toolkit Version: 1.5
 - AWS Version: via pip3: aws-cli/1.16.220 Python/3.7.4 Darwin/18.7.0 botocore/1.12.210
 - SAM CLI Version: 0.19.0
 - JVM/Python Version: Python 3.7.4

**Additional context**
First time I'm installing AWS CLI / AWS Toolkit.

In the PyCharm logfile I see:

```
2019-08-18 00:13:03,094 [ 134200]   INFO - ageJson.NpmRegistryServiceImpl - Found 3 dist-tags, 266 versions for @angular/cli in 153ms 

2019-08-18 00:13:03,548 [ 134654]   INFO - ces.lambda.sam.SamVersionCache - Evaluating /usr/local/bin/aws 

2019-08-18 00:13:03,550 [ 134656]   INFO - ces.lambda.sam.SamVersionCache - InfoResult for /usr/local/bin/aws is either missing, or stale. Checking again 

2019-08-18 00:13:03,590 [ 134696]   INFO - ces.lambda.sam.SamVersionCache - Evaluating /usr/local/bin/aws 

2019-08-18 00:13:04,090 [ 135196]   INFO - ces.lambda.sam.SamVersionCache - Evaluating /usr/local/bin/aws 

2019-08-18 00:13:04,358 [ 135464]   INFO - ces.lambda.sam.SamVersionCache - Failed to evaluate /usr/local/bin/aws 

java.lang.IllegalStateException: usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]

To see help text, you can run:




  aws help

  aws <command> help

  aws <command> <subcommand> help

aws: error: the following arguments are required: command

	at software.aws.toolkits.jetbrains.services.lambda.sam.SamVersionCache.getFileInfo(SamVersionCache.kt:21)

	at software.aws.toolkits.jetbrains.services.lambda.sam.SamVersionCache.getFileInfo(SamVersionCache.kt:11)

	at software.aws.toolkits.jetbrains.utils.FileInfoCache$evaluate$4.run(FileInfoCache.kt:56)

	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)

2019-08-18 00:13:04,358 [ 135464]   INFO - ces.lambda.sam.SamVersionCache - Evaluating /usr/local/bin/aws 
```

**Comment by abrooksv** [comment]
It looks like you have accidentally set the SAM CLI location to the AWS CLI location.
