### ISSUE TITLE
Invalid SAM CLI executable configured 2

### ISSUE THREAD

**Issue by enochdwelo** [aws/aws-toolkit-jetbrains#1178]
When I try to set my SAM CLI executable I receive the following error: "Cannot Save Settings: Invalid SAM CLI executable configured"

Very similar to #577  but not quite.

**Screenshots**
![Screen Shot 2019-08-23 at 10 53 08 AM](https://user-images.githubusercontent.com/45176614/63609706-e0de2f80-c594-11e9-8b17-47b240c141be.png)

**Your Environment**
 - OS: MACOSX 10.14.6
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2019.2.1
 - Toolkit Version: 1.5
 - SAM CLI Version: version 0.19.0
 - JVM/Python Version: Python 3.7.4

SAM CLI runs just fine when run directly from my console

**Comment by zhangzhx** [comment]
Thanks for reporting this issue. What is the result by running `/usr/local/bin/sam --version` in your terminal?

**Comment by shipmaster** [comment]
I ran into this exact issue using SAM CLI 0.22.0 installed using homebrew which is the recommended version in the doc. I am also using PyCharm 2019.2 on Mac OS 10.14.6

**Comment by kiiadi** [comment]
Does the SAM CLI run successfully from a terminal? Is it the same executable? eg. if you run a `which sam` is that the path as what's configured in the IDE?

**Comment by shipmaster** [comment]
It does run successfully from the terminal and its the same executable.
$ which sam
/usr/local/bin/sam
$ sam --version
SAM CLI, version 0.22.0

And the log from the IDE log points to the same path

java.lang.IllegalStateException: Traceback (most recent call last):
  File "/usr/local/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==0.22.0' distribution was not found and is required by the application
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamVersionCache.getFileInfo(SamVersionCache.kt:21)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamVersionCache.getFileInfo(SamVersionCache.kt:11)
	at software.aws.toolkits.jetbrains.utils.FileInfoCache$evaluate$4.run(FileInfoCache.kt:56)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by flado** [comment]
```
/usr/local/bin/sam
SAM CLI, version 0.31.0
```

```
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019

```



![image](https://user-images.githubusercontent.com/4745441/68740274-6e7e6800-0636-11ea-9e13-2b6435b890c4.png)

**Comment by justinmk3** [comment]
- How are you starting the IDE (from a shell, or from a GUI icon)?
- Does your environment have `$PYTHONPATH` or `$PYTHONHOME` set? Try this from the IDE:
  1. open Terminal
  2. `env | grep PYTHON`
- Have you set the SAM CLI path in the AWS Toolkit preferences? If so, what was set there? Screenshot of dialog follows:

![Screen Shot 2019-11-13 at 12 08 06 PM](https://user-images.githubusercontent.com/55561878/68800256-98bc2f80-060e-11ea-929d-a83a13a31544.png)


## Analysis

All reports here mention `/usr/local/lib/python3.7/site-packages/...` But I would expect homebrew-installed `sam` to invoke the python it ships with, from the homebrew location similar to:

    /usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/...

If I rename `aws_sam_cli-0.31.0-py3.7.egg-info` at that location, I can provoke a similar error:

```
$ cd /usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages
$ mv aws_sam_cli-0.31.0-py3.7.egg-info aws_sam_cli-0.31.0-py3.7.egg-info.bk
$ sam
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==0.31.0' distribution was not found and is required by the application

```

**Comment by flado** [comment]
it seems that /usr/local/bin/sam is a link to the _sam_ location : 

`0 lrwxr-xr-x  1 flado  admin    36B  8 Nov 15:26 **/usr/local/bin/sam** -> ../Cellar/aws-sam-cli/0.31.0/bin/sam`

By setting the full path as: **/usr/local/Cellar/aws-sam-cli/0.31.0/bin/sam** in the IDE / SAM CLI exe the issue is not present anymore. It might be that the plugin does not follow links?

**Comment by justinmk3** [comment]
> By setting the full path as: /usr/local/Cellar/aws-sam-cli/0.31.0/bin/sam in the IDE / SAM CLI exe the issue is not present anymore

@flado good info, thanks! What happens if you set the path to `/usr/local/bin/sam` explicitly? 

I am wondering if the auto-discovered `sam` decided by the IDE/toolkit is different than `/usr/local/bin/sam`.

**Comment by abrooksv** [comment]
> it seems that /usr/local/bin/sam is a link to the _sam_ location :
> 
> `0 lrwxr-xr-x 1 flado admin 36B 8 Nov 15:26 /usr/local/bin/sam -> ../Cellar/aws-sam-cli/0.31.0/bin/sam`
> 
> By setting the full path as: **/usr/local/Cellar/aws-sam-cli/0.31.0/bin/sam** in the IDE / SAM CLI exe the issue is not present anymore. It might be that the plugin does not follow links?

Pretty sure the raw string eventually makes it down to Java's ProcessBuilder class.

**Comment by flado** [comment]
@justinmk3 The auto-discovery of `/usr/local/bin/sam` seems to be working fine ... also when i setup manually as: /usr/local/bin/sam I get : 

![image](https://user-images.githubusercontent.com/4745441/68813554-e8a7fe80-06c1-11ea-9f97-d9fc88402d02.png)

**Comment by justinmk3** [comment]
Strange. I suppose it wouldn't hurt to resolve the symlink, but we might be hiding the root cause then...

**Comment by abrooksv** [comment]
If you go to Help->Debug Log Settings... and paste `#com.intellij.execution.configurations.GeneralCommandLine`, and try again, debug lines will show in the idea.log (Help->Show logs in finder...)

Search for GeneralCommandLine in the log

**Comment by flado** [comment]
@abrooksv the Stacktrace in IntelliJ:

```
2019-11-14 12:28:14,741 [13345457]   INFO - ces.lambda.sam.SamVersionCache - Evaluating /usr/local/bin/sam 
2019-11-14 12:28:14,742 [13345458]  DEBUG - figurations.GeneralCommandLine - Executing [/usr/local/bin/sam --info] 
2019-11-14 12:28:14,742 [13345458]  DEBUG - figurations.GeneralCommandLine - Building process with commands: [/usr/local/bin/sam, --info] 
2019-11-14 12:28:14,950 [13345666]   INFO - ces.lambda.sam.SamVersionCache - Failed to evaluate /usr/local/bin/sam 
java.lang.IllegalStateException: Traceback (most recent call last):
  File "/usr/local/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==0.31.0' distribution was not found and is required by the application
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamVersionCache.getFileInfo(SamVersionCache.kt:21)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamVersionCache.getFileInfo(SamVersionCache.kt:11)
	at software.aws.toolkits.jetbrains.utils.FileInfoCache.getValue(FileInfoCache.kt:24)
	at software.aws.toolkits.jetbrains.utils.FileInfoCache.getValue(FileInfoCache.kt:18)
	at software.aws.toolkits.jetbrains.utils.CachingAsyncEvaluator$evaluate$4.run(CachingAsyncEvaluator.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by abrooksv** [comment]
Oh...it looks like the additional log lines were not added until 2019.3

**Comment by justinlarose** [comment]
I had aws-sam-cli already installed via Homebrew, but I installed the python package via `pip install aws-sam-cli`and this resolved the "DistributionNotFound" problem.

**Comment by justinmk3** [comment]
@justinlarose Thanks for noting that.

> Oh...it looks like the additional log lines were not added until 2019.3

@flado are you still experiencing this issue? If so, can you update PyCharm to 2019.3.x (and also update AWS Toolkit), then  [get the debug log](https://github.com/aws/aws-toolkit-jetbrains/issues/1178#issuecomment-553669183) and post the result here?

**Comment by forgivegod** [comment]
Still happens in 2020.1.1

**Comment by justinmk3** [comment]
Recent version of the toolkit/Intellij should expose more useful logs for this now. If you're experiencing this issue, please try the instructions here and post the logs: https://github.com/aws/aws-toolkit-jetbrains/issues/1178#issuecomment-553669183

**Comment by forgivegod** [comment]
related issue for 2020.01.01 / 1.16-201 : https://github.com/aws/aws-toolkit-jetbrains/issues/1757

**Comment by Pauldic** [comment]
I hard this issue on Mac following the documentation's guide but resolved it by setting `$PYTHONPATH` to my python path in `~/.bash_profile`

**Comment by breedloj** [comment]
Closing due to inactivity. Feel free to reopen if you are still experiencing issues.
