### ISSUE TITLE
Error while getting SAM executable version.

### ISSUE THREAD

**Issue by gamename** [aws/aws-toolkit-jetbrains#1261]
**Describe the bug**
When I try to create a lambda function on PyCharm, the sam build process hangs and I get the following error in the IDE:
```
Error while getting SAM executable version.

java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.jetbrains.concurrency.AsyncPromise.get(AsyncPromise.kt:21)
	at org.jetbrains.concurrency.AsyncPromise.blockingGet(AsyncPromise.kt:92)
	at software.aws.toolkits.jetbrains.utils.CachingAsyncEvaluator.evaluateBlocking(CachingAsyncEvaluator.kt:77)
	at software.aws.toolkits.jetbrains.utils.CachingAsyncEvaluator.evaluateBlocking$default(CachingAsyncEvaluator.kt:75)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion.getVersionString(SamCommon.kt:115)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion.getVersionString$default(SamCommon.kt:110)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaBuilder$buildLambdaFromTemplate$2.run(LambdaBuilder.kt:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To reproduce**
1. Right-click on the "Lambda" section of the "AWS Explorer" window and choose "Create new AWS Lambda"
2. Fill out the dialog box with the needed lambda function information 
3. Hit the "Create Function" button at he bottom right of the dialog
4. Click on the "Build" tool window and I get the following
![image](https://user-images.githubusercontent.com/42153/66658385-fa037400-ec06-11e9-82e8-8366a8534f1e.png)
5. I immediately get the error stack trace (above).

**Expected behavior**
Create the lambda function 

**Screenshots**

**Your Environment**
 - OS: Mac OS Catalina (10.15) 
 - JetBrains' Product: Pycharm
 - JetBrains' Product Version:
```PyCharm 2019.2.3 (Professional Edition)
Build #PY-192.6817.19, built on September 25, 2019
Licensed to Tennis Smith
You have a perpetual fallback license for this version
Subscription is active until October 18, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.windowSystem.autoShowProcessPopup=true, ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Jenkins Control Plugin, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, com.github.holgerbrandl.pasteimages/, com.godwin.json.parser, com.leinardi.pycharm.pylint, com.potterhsu.jsonviewer, com.atlassian.bitbucket.references, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.asciidoctor.intellij.asciidoc, com.perl5, org.intellij.plugins.hcl, com.jetbrains.intellij.datalore, BashSupport, com.intellij.plugin.adernov.powershell, AWSCloudFormation, aws.toolkit, com.intellij.kubernetes, org.logtalk, zielu.gittoolbox
```
 - Toolkit Version:  1.7-EAP.2019.10.08
 - SAM CLI Version: 
```
$ sam --version
SAM CLI, version 0.22.0
```
 - JVM/Python Version: Python 3.7.3 

**Additional context**

**Comment by hunterwerlla** [comment]
Hello, do you happen to have a virus scanner on your machine of some sort? Can you run `time sam --version`. I can reproduce this on my machine on first run because we use the default 500 ms timeout:
```
time sam --version
SAM CLI, version 0.17.0

real	0m1.158s
user 0m0.271s
sys	0m0.240s
```

**Comment by gamename** [comment]
@hunterwerlla 
Hi,

This is what I get:
```
$ time sam --version
SAM CLI, version 0.22.0
sam --version  0.54s user 0.15s system 78% cpu 0.877 total
```

**Comment by gamename** [comment]
This has cleared for some reason. Dunno why.  Closing

**Comment by bishopandco** [comment]
FWIW: This gotcha always gets me when I don't have docker running.

**Comment by forgivegod** [comment]
Still happens in 2020.1.1

**Comment by hunterwerlla** [comment]
@forgivegod Can you open a new issue and attach that portion of your IDEA.log file? Is docker running?
