### ISSUE TITLE
Rider/Edit Configuration reports Error: lambda handler validation is in progress

### ISSUE THREAD

**Issue by koendhondt** [aws/aws-toolkit-jetbrains#1299]
**Describe the bug**
When attempting to add a Lambda run configuration in Rider 2019.2.3 on MacOS, it is not possible to define the handler. The completion takes forever and never returns a match. The dialog always displays the following message at the bottom of the window:
Error: Lambda handler validation is in progress

**To reproduce**
- Create a new project, select Lambda Empty Function in the Wizard
- Go to: Run -> Edit Configurations...
- Select +, Lambda, Local
- Select Runtime: dotnetcore2.1
- Start typing Handler name: this takes a long time, upon every character entered, the lookup appears to do something. Until the name to the class is specifed (LambdaEmptyFunction::LambdaEmptyFunction.Function), the following error message is shown: 'Error: Cannot find handler 'LambdaEmptyFunction::LambdaEmpty' in project, nor are completions offered (pressing ctrl+space results in 'No suggestions'.
- Once the proper path to the handler has been specified,  LambdaEmptyFunction::LambdaEmptyFunction.Function::FunctionHandler, the error message 'Error: lambda handler validation is in progress' appears and does not go away. The Apply button can be pressed.
- If the apply button is pressed, and you subsequently attempt to run the configuration, you are taken back to the 'Run/Debug configurations' dialog 

**Expected behavior**
The feature works as expected, providing proper completion and accepting the correct handler location, or an option is provided to disable this behavior.

**Your Environment**
 - OS: MacOS Mojave 10.14.6
 - JetBrains' Product: Rider
 - JetBrains' Product Version: 2019.2.3
 - Toolkit Version: aws-jetbrains-toolkit-1.8-SNAPSHOT (master, git log shows 931384e51d9d818ce06c7d7bbe2bcfbe61689f8b as last commit)
 - SAM CLI Version: SAM CLI, version 0.22.0
 - JVM/Python Version: jvm 1.8.0_202, Python 2.7.10, Python 3.7.4

The IDE reports a Fatal Error as well, examining it shows the following stacktrace, indicating that the handler completion detection code is timing out each time input is entered in the 'Handler' field of the Run/Debug configurations dialog:

java.util.concurrent.TimeoutException: Sync execution of rpc `SolutionModel.solutions.[1].lambdaModel.determineHandlers` is timed out in 3000 ms
	at com.jetbrains.rd.framework.impl.RdCall$sync$freezeTime$1.invoke(RdTask.kt:132)
	at com.jetbrains.rd.framework.impl.RdCall$sync$freezeTime$1.invoke(RdTask.kt:50)
	at com.jetbrains.rd.util.PlatformDependentKt.measureTimeMillis(PlatformDependent.kt:80)
	at com.jetbrains.rd.framework.impl.RdCall.sync(RdTask.kt:126)
	at software.aws.toolkits.jetbrains.services.lambda.completion.DotNetHandlerCompletion.getLookupElements(DotNetHandlerCompletion.kt:22)
	at software.aws.toolkits.jetbrains.services.lambda.completion.HandlerCompletionProvider.fillCompletionVariants(HandlerCompletionProvider.kt:47)
	at com.intellij.util.textCompletion.TextCompletionContributor.fillCompletionVariants(TextCompletionContributor.java:58)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:325)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:317)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by abrooksv** [comment]
Fix is in master, will land in next EAP

**Comment by koendhondt** [comment]
> Fix is in master, will land in next EAP

Thanks, I'll keep an eye on the EAP page for the next build; the currently available EAP build (1.8-EAP.2019.10.29 ) does not appear to contain the fix.

**Comment by koendhondt** [comment]
Question (and if this is the wrong place to ask, please point me to the correct one): the completion does not work when you define a 'public object FunctionHandler' function handler (we are using it for synchronous processing in an SES email input rule). The handler works properly when deployed on our account but the plugin does not recognize the handler. Is this a bug, or is 'public object ...' an invalid return type for lambda's?

**Comment by abrooksv** [comment]
> Question (and if this is the wrong place to ask, please point me to the correct one): the completion does not work when you define a 'public object FunctionHandler' function handler (we are using it for synchronous processing in an SES email input rule). The handler works properly when deployed on our account but the plugin does not recognize the handler. Is this a bug, or is 'public object ...' an invalid return type for lambda's?

Can you cut a new issue and include a small hello world snippet showing the full function?
