### ISSUE TITLE
Timeout occurs when number of lambdas in target account is large

### ISSUE THREAD

**Issue by axdsilva** [aws/aws-toolkit-jetbrains#1414]
GIVEN:
    AWS tooklit has been successfully installed
WHEN
    In AWS explorer the drop down icon is clicked to list lambda function
THEN
    I get "Error Loading resources" on UI (Please see attached) AND
    A timeout exception is got in the idea log file:
```2019-12-05 00:34:17,841 [1698744]   INFO - vices.lambda.LambdaServiceNode - Failed to get children 
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$Companion.wait(AwsResourceCache.kt:125)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$Companion.access$wait(AwsResourceCache.kt:119)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$DefaultImpls.getResourceNow(AwsResourceCache.kt:72)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.getResourceNow(AwsResourceCache.kt:214)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$DefaultImpls.getResourceNow$default(AwsResourceCache.kt:71)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.CacheBackedAwsExplorerServiceRootNode.getChildrenInternal(AwsExplorerServiceRootNode.kt:29)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.ResourceParentNode$DefaultImpls.getChildren(ResourceParentNode.kt:20)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerServiceRootNode.getChildren(AwsExplorerServiceRootNode.kt:14)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerServiceRootNode.getChildren(AwsExplorerServiceRootNode.kt:14)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:37)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:414)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:332)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:326)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:346)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:582)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:476)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:442)
	at software.aws.toolkits.jetbrains.ui.tree.Command$Processor.lambda$process$1(Command.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker.invokeSafely(Invoker.java:147)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker.lambda$invokeLater$0(Invoker.java:93)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:306)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
NFR: Should this timeout be configurable on the plugin
PS: I am able to create lambdas from AWS explorer.

**Comment by abrooksv** [comment]
Current timeout is hard coded to 5s, this should be higher since the explorer is already async in nature.

**Comment by axdsilva** [comment]
When can you provide a fix, so that I can use this. If the list is large, I cannot "see" my lambda

**Comment by abrooksv** [comment]
Roughly how many do you have, so we can validate new value will work

**Comment by axdsilva** [comment]
About 600 or so lambdas

**Comment by abrooksv** [comment]
1.10 has increased the limit
