### ISSUE TITLE
IntelliJ IDEA on Windows 10 throws java.io.IOException when trying to view EventBridge Schema

### ISSUE THREAD

**Issue by chris271** [aws/aws-toolkit-jetbrains#1444]
**Describe the bug**
When using the "View Schema" option for Event Bridge schemas, IntelliJ IDEA for Windows 10 throws a java.io.IOException.

**To reproduce**

1. Open 'AWS Explorer' in main IntelliJ IDEA window.
2. Expand 'Schemas' -> 'aws.events'
3. Right-click any event and select 'View Schema'
4. See error below for 'aws.autoscaling@AWSAPICallViaCloudTrail':
```
Could not fetch and display schema aws.cloudwatch@CloudWatchAlarmStateChange contents
				java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Invalid file name: 'Profile:default.us-east-1.aws.events.aws.cloudwatch@CloudWatchAlarmStateChange.1.json'
				at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
				at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
				at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
				at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
				at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
				at software.aws.toolkits.jetbrains.services.schemas.SchemaPreviewer$openFileInEditor$1.run(SchemaViewer.kt:143)
				at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
				at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
				... (show balloon)
```

**Expected behavior**
The schema should be retrieved and shown for the selected EventBridge schema.

**Screenshots**
![image](https://user-images.githubusercontent.com/21958258/71091746-b59ad400-2173-11ea-9b90-1afcb861fcdf.png)

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: IntelliJ IDEA
 - JetBrains' Product Version: IntelliJ IDEA 2019.3.1 (Ultimate Edition) Build #IU-193.5662.53, built on December 18, 2019
 - Runtime version: 11.0.5+10-b520.17 amd64
 - VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Windows 10 10.0
 - GC: ParNew, ConcurrentMarkSweep
 - Memory: 970M
 - Cores: 8
 - Non-Bundled Plugins: AWSCloudFormation, Batch Scripts Support, CMD Support, Pythonid, aws.toolkit, com.amazon.devsync.plugin, com.andrey4623.rainbowcsv, com.developerphil.adbidea, com.intellij.kubernetes, com.intellij.lang.jsgraphql, io.snyk.snyk-intellij-plugin, net.seesharpsoft.intellij.plugins.csv, org.intellij.plugins.hcl, org.intellij.scala, org.jetbrains.plugins.go, org.toml.lang, org.rust.lang
 - Toolkit Version: 1.9-193
 - SAM CLI Version: SAM CLI, version 0.17.0
 - JVM/Python Version: Python 3.7.2 and Java(TM) SE Runtime Environment (build 1.8.0_231-b11)

**Comment by nikp** [comment]
Likely related to the special character ":" from the profile in the file name

**Comment by justinmk3** [comment]
closed by https://github.com/aws/aws-toolkit-jetbrains/pull/1497
