### ISSUE TITLE
Cannot find s3 buckets after PyCharm update today 

### ISSUE THREAD

**Issue by gamename** [aws/aws-toolkit-jetbrains#1462]
**Describe the bug**
After updating PyCharm to 2019.3.1, any dialog box that should list s3 buckets gets the following error:
```
8:29 AM	Failed loading resources
					software.amazon.awssdk.services.s3.model.NoSuchBucketException: The specified bucket does not exist. (Service: S3, Status Code: 404, Request ID: DEA88E3FC3691E99)
					at software.amazon.awssdk.services.s3.model.NoSuchBucketException$BuilderImpl.build(NoSuchBucketException.java:117)
					at software.amazon.awssdk.services.s3.model.NoSuchBucketException$BuilderImpl.build(NoSuchBucketException.java:77)
					at software.amazon.awssdk.services.s3.internal.handlers.ExceptionTranslationInterceptor.modifyException(ExceptionTranslationInterceptor.java:73)
					at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyException(ExecutionInterceptorChain.java:175)
					at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.runModifyException(ExceptionReportingUtils.java:54)
					at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.reportFailureToInterceptors(ExceptionReportingUtils.java:38)
```

**To reproduce**
1. Upgrade PyCharm to 2019.3.1
2. Try to update the code of an existing lambda function by right-clicking on the name in the "AWS Explorer" window and selecting "Update Function Code"
3. When the dialog box comes up, the s3 bucket area will show 'loading' for a second, then will show the following error
![image](https://user-images.githubusercontent.com/42153/71261619-6c798a00-2303-11ea-861e-647b7a329669.png)

**Expected behavior**
There should be a fold-down list of s3 buckets available 

**Your Environment**
 - OS:  Mac OS Catalina 
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version:
 - Toolkit Version: 1.9-193
 - SAM CLI Version: 0.22.0
 - JVM/Python Version: 3.7 

**Additional context**

**Comment by abrooksv** [comment]
Can you provide the full stack trace so I can see where in the toolkit this call is coming from please.

**Comment by gamename** [comment]
@abrooksv 

```
software.amazon.awssdk.services.s3.model.NoSuchBucketException: The specified bucket does not exist. (Service: S3, Status Code: 404, Request ID: 4B40BE7BEDE2B376) at software.amazon.awssdk.services.s3.model.NoSuchBucketException$BuilderImpl.build(NoSuchBucketException.java:117) at software.amazon.awssdk.services.s3.model.NoSuchBucketException$BuilderImpl.build(NoSuchBucketException.java:77) at software.amazon.awssdk.services.s3.internal.handlers.ExceptionTranslationInterceptor.modifyException(ExceptionTranslationInterceptor.java:73) at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyException(ExecutionInterceptorChain.java:175) at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.runModifyException(ExceptionReportingUtils.java:54) at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.reportFailureToInterceptors(ExceptionReportingUtils.java:38) at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:39) at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73) at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44) at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55) at software.amazon.awssdk.services.s3.DefaultS3Client.headBucket(DefaultS3Client.java:4097) at software.amazon.awssdk.services.s3.S3Client.headBucket(S3Client.java:8832) at software.aws.toolkits.core.s3.RegionalBucketsKt.regionForBucket(RegionalBuckets.kt:10) at software.aws.toolkits.core.utils.S3ClientUtilsKt$listBucketsByRegion$1.invoke(S3ClientUtils.kt:12) at software.aws.toolkits.core.utils.S3ClientUtilsKt$listBucketsByRegion$1.invoke(S3ClientUtils.kt) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:133) at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:176) at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698) at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728) at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719) at software.aws.toolkits.jetbrains.services.s3.S3Resources$listBucketsByActiveRegion$1.invoke(S3Resources.kt:18) at software.aws.toolkits.jetbrains.services.s3.S3Resources$listBucketsByActiveRegion$1.invoke(S3Resources.kt:13) at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:178) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetch(AwsResourceCache.kt:337) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetchIfNeeded(AwsResourceCache.kt:323) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.access$fetchIfNeeded(AwsResourceCache.kt:214) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:252) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:214) at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1.run(AwsResourceCache.kt:251) at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by abrooksv** [comment]
Can you double check you have permission s3:ListBucket on your role? We haven't modified this code a while

**Comment by gamename** [comment]
@abrooksv 

Yes, I'm certain I have those permissions.  I was using PyCharm with s3 just fine an hour before the upgrade. After the upgrade, I can't use s3 anymore.

**Comment by gamename** [comment]
I also verified I have permissions by testing via the CLI

**Comment by gamename** [comment]
I completely exited the application. Then restarted it again.  Problem cleared. Weird.

**Comment by alexchiri** [comment]
I started having this issue today when right-clicking on template.yaml and selecting "Deploy Serverless Application". It started happening out of a sudden. I restarted PyCharm and also erased all settings and tried again. At the same time, the bucket that was configured for that stack I cannot touch in any way. It is still shown in S3, but I cannot delete it (even though I am logged in as the root user). Strange behavior with S3 around the same time, buckets that I deleted in the past show up, but they cannot be deleted or see their contents. Seems to me to be a larger issue with S3.

**Comment by goacoustic** [comment]
The bug still exists. and it's bound to the S3 distributed nature. Sometimes, after removing bucket from S3, it is still shown on the console UI and visible with the `aws s3 ls` command. If you try to do `aws s3 ls <deleted_bucket_name>`, you'll get an error  like `An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist`

Bucket eventually cleaned up by S3, but until this happens, AWS toolkit will throw this kind of exceptions, which blocks deploying lambdas or opening S3 subtree in the AWS Explorer
  
```
software.amazon.awssdk.services.s3.model.NoSuchBucketException: The specified bucket does not exist. (Service: S3, Status Code: 404, Request ID: D974C0108249514C) at software.amazon.awssdk.services.s3.model.NoSuchBucketException$BuilderImpl.build(NoSuchBucketException.java:117) at software.amazon.awssdk.services.s3.model.NoSuchBucketException$BuilderImpl.build(NoSuchBucketException.java:77) at software.amazon.awssdk.services.s3.internal.handlers.ExceptionTranslationInterceptor.modifyException(ExceptionTranslationInterceptor.java:73) at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyException(ExecutionInterceptorChain.java:175) at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.runModifyException(ExceptionReportingUtils.java:54) at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.reportFailureToInterceptors(ExceptionReportingUtils.java:38) at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:39) at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120) at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73) at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44) at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55) at software.amazon.awssdk.services.s3.DefaultS3Client.headBucket(DefaultS3Client.java:4079) at software.amazon.awssdk.services.s3.S3Client.headBucket(S3Client.java:8796) at software.aws.toolkits.core.s3.RegionalBucketsKt.regionForBucket(RegionalBuckets.kt:10) at software.aws.toolkits.core.utils.S3ClientUtilsKt$listBucketsByRegion$1.invoke(S3ClientUtils.kt:12) at software.aws.toolkits.core.utils.S3ClientUtilsKt$listBucketsByRegion$1.invoke(S3ClientUtils.kt) at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:133) at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156) at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:176) at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:702) at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:732) at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:723) at software.aws.toolkits.jetbrains.services.s3.resources.S3Resources$listBucketsByActiveRegion$1.invoke(S3Resources.kt:39) at software.aws.toolkits.jetbrains.services.s3.resources.S3Resources$listBucketsByActiveRegion$1.invoke(S3Resources.kt:18) at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:180) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetch(AwsResourceCache.kt:339) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetchIfNeeded(AwsResourceCache.kt:325) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.access$fetchIfNeeded(AwsResourceCache.kt:216) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:254) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:216) at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908) at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1.run(AwsResourceCache.kt:253) at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834)
```
