### ISSUE TITLE
AWS Explorer timeout when expanding CloudFormation

### ISSUE THREAD

**Issue by miensol** [aws/aws-toolkit-jetbrains#1468]
**Describe the bug**
It's not possible to list CloudFormation stacks in AWS Explorer. The account I've tested it with has more than 10 stacks.

**To reproduce**
Expand the CloudFormation node in AWS Explorer panel connected to account that has more than a few stacks.

![aws-explorer-timeout](https://user-images.githubusercontent.com/357191/71555209-cd067680-2a29-11ea-817c-07c64c25f308.gif)

The following exception can be found in logs when expanding CloudFormation node in AWS Explorer

```
2019-12-29 10:46:00,551 [53816729]   INFO - tion.CloudFormationServiceNode - Failed to get children 
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$Companion.wait(AwsResourceCache.kt:125)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$Companion.access$wait(AwsResourceCache.kt:119)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$DefaultImpls.getResourceNow(AwsResourceCache.kt:72)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.getResourceNow(AwsResourceCache.kt:214)
	at software.aws.toolkits.jetbrains.core.AwsResourceCache$DefaultImpls.getResourceNow$default(AwsResourceCache.kt:71)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.CacheBackedAwsExplorerServiceRootNode.getChildrenInternal(AwsExplorerServiceRootNode.kt:29)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.ResourceParentNode$DefaultImpls.getChildren(ResourceParentNode.kt:20)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerServiceRootNode.getChildren(AwsExplorerServiceRootNode.kt:14)
	at software.aws.toolkits.jetbrains.core.explorer.nodes.AwsExplorerServiceRootNode.getChildren(AwsExplorerServiceRootNode.kt:14)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:37)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:414)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:332)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:326)
	at software.aws.toolkits.jetbrains.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:346)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:582)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:476)
	at software.aws.toolkits.jetbrains.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:442)
	at software.aws.toolkits.jetbrains.ui.tree.Command$Processor.lambda$process$1(Command.java:51)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker.invokeSafely(Invoker.java:147)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker.lambda$invokeLater$0(Invoker.java:93)
	at software.aws.toolkits.jetbrains.ui.tree.Invoker$BackgroundThread.lambda$offer$0(Invoker.java:306)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected**
The list of stacks loads.

**Environment**
PyCharm 2019.3.1 (Professional Edition)
Build #PY-193.5662.61, built on December 18, 2019
You have a perpetual fallback license for this version
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: AWSCloudFormation, aws.toolkit (1.9-193 Dec 18, 2019)

**Comment by abrooksv** [comment]
The timeout was increased to 30s in master, but has not been released yet

**Comment by abrooksv** [comment]
Release is out with increased timeout
