### ISSUE TITLE
java.lang.ExceptionInInitializerError Webstorm fresh install when clicking "configure AWS connection"

### ISSUE THREAD

**Issue by zlittj** [aws/aws-toolkit-jetbrains#1532]
**Describe the bug**
Unable to configure AWS connection on latest Webstorm build for Linux.

Error Log: 
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:59)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialProviderFactoryEP$instance$1.getInstanceClass(ExtensionPointCredentialsProviderRegistry.kt:31)
	at com.intellij.openapi.util.LazyInstance.compute(LazyInstance.java:19)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialProviderFactoryEP.getHandler(ExtensionPointCredentialsProviderRegistry.kt:34)
	at software.aws.toolkits.jetbrains.core.credentials.ExtensionPointCredentialsProviderRegistry$listFactories$1$1.invoke(ExtensionPointCredentialsProviderRegistry.kt:41)
	at software.aws.toolkits.jetbrains.core.credentials.ExtensionPointCredentialsProviderRegistry$listFactories$1$1.invoke(ExtensionPointCredentialsProviderRegistry.kt:37)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull(LogUtils.kt:20)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull$default(LogUtils.kt:19)
	at software.aws.toolkits.jetbrains.core.credentials.ExtensionPointCredentialsProviderRegistry.listFactories(ExtensionPointCredentialsProviderRegistry.kt:40)
	at software.aws.toolkits.jetbrains.core.credentials.ExtensionPointCredentialsProviderRegistry.listFactories(ExtensionPointCredentialsProviderRegistry.kt:37)
	at software.aws.toolkits.core.credentials.DefaultToolkitCredentialsProviderManager.reloadFactories(ToolkitCredentialsProviderManager.kt:85)
	at software.aws.toolkits.core.credentials.DefaultToolkitCredentialsProviderManager.<init>(ToolkitCredentialsProviderManager.kt:42)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager.<init>(CredentialManager.kt:41)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:18)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$Companion.getInstance(CredentialManager.kt:27)
	at software.aws.toolkits.jetbrains.core.credentials.ProjectAccountSettingsManager.recentlyUsedCredentials(ProjectAccountSettingsManager.kt:175)
	at software.aws.toolkits.jetbrains.core.credentials.ChangeAccountSettingsActionGroup$createChildrenProvider$1.compute(ChangeConnectionSettingsMenu.kt:46)
	at com.intellij.util.CachedValueImpl.doCompute(CachedValueImpl.java:37)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.util.CachedValueImpl.getValue(CachedValueImpl.java:48)
	at software.aws.toolkits.jetbrains.utils.actions.ComputableActionGroup.getChildren(ComputableActionGroup.kt:24)
	at com.intellij.ui.popup.ActionStepBuilder.calcMaxIconSize(ActionStepBuilder.java:83)
	at com.intellij.ui.popup.ActionStepBuilder.buildGroup(ActionStepBuilder.java:70)
	at com.intellij.ui.popup.ActionPopupStep.createActionItems(ActionPopupStep.java:111)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:265)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:205)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:172)
	at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:360)
	at com.intellij.openapi.ui.popup.JBPopupFactory.createActionGroupPopup(JBPopupFactory.java:286)
	at software.aws.toolkits.jetbrains.core.credentials.SettingsSelector.settingsPopup(AwsSettingsPanel.kt:88)
	at software.aws.toolkits.jetbrains.core.credentials.SettingsSelector.settingsPopup(AwsSettingsPanel.kt:85)
	at software.aws.toolkits.jetbrains.core.explorer.ExplorerToolWindow$1.hyperlinkUpdate(ExplorerToolWindow.kt:66)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:201)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:126)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: User limit of inotify watches reached
	at java.base/sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:266)
	at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:265)
	at java.base/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:366)
	at java.base/java.lang.Thread.run(Thread.java:834)

**To reproduce**
1. Download fresh install of Webstorm.
2. Click "Configure AWS connection" in either the AWS Explorer or along the bottom bar. 

**Expected behavior**
Option opens to add a config file, or select a profile from the credentials config.

**Your Environment**
 - OS: Ubuntu Linux
 - JetBrains' Product: Webstorm 
 - JetBrains' Product Version: 2019.3.2 
 - Toolkit Version: 1.10-193
 - SAM CLI Version: 0.40.0
 - JVM/Python Version: 

**Additional context**
I have tried uninstalling multiple times with no success.

**Comment by abrooksv** [comment]
Hey, it looks like your inotify limit on your OS is too low. Can you try increasing that?

**Comment by zlittj** [comment]
Yeah that was it, thanks for the quick reply.

**Comment by abrooksv** [comment]
You're welcome, thank you for trying the toolkit.
