### ISSUE TITLE
Failed to switch to profile

### ISSUE THREAD

**Issue by Kirizan** [aws/aws-toolkit-jetbrains#1560]
**Describe the bug**
When trying to load any profile, I am getting the error "The security token included in the request is invalid. (Service: Sts, Status Code: 403, Request ID: fe913f0b-e84d-438e-a882-99484d7f51f8)" I know the security token is valid however, since I can run AWS commands from the CLI.

Suggested simliar issues: 
#1443 - I do not have any indentation on the configuration file. This is not the same issue as that issue
#499 - My issue is not related to the SAM configuration, it does this even if I'm not doing a serverless application
#778 - While this might help, this is a suggestion and not an issue.
#498 - This issue was solved by installing SAM. I do have SAM installed, but my issue is still happening.

**To reproduce**
1.  Load Pycharm
2. Select a profile from the AWS Profile explorer

**Expected behavior**
The profile is loaded

**Your Environment**
- OS: MacOS 10.15.3
- JetBrains product: Pycharm
- JetBrains product version: Professional 2019.3.3
- Original AWS Toolkit version: 1.11-EAP.2020.02.11-193 (The current non-EAP toolkit does not work due to the certificate store issue.)
- Current AWS Toolkit version: 1.11-193 -- This issue was not fixed when updated to the current release.
- SAM CLI version: 0.43.0
- JVM/Python version: 3.7.4

**Additional context**
Log entry:

```
2020-02-25 14:30:10,613 [1443829]   WARN - tProjectAccountSettingsManager - Failed to switch to profile 'Profile:checkmarx-dev-exec' 
software.amazon.awssdk.services.sts.model.StsException: The security token included in the request is invalid. (Service: Sts, Status Code: 403, Request ID: 2e5250c2-7af0-49c8-8910-2f129a48deaf)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:81)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:61)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:74)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:114)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:87)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:61)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:198)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:122)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:148)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:102)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.sts.DefaultStsClient.assumeRole(DefaultStsClient.java:265)
	at software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider.getUpdatedCredentials(StsAssumeRoleCredentialsProvider.java:68)
	at software.amazon.awssdk.services.sts.auth.StsCredentialsProvider.updateSessionCredentials(StsCredentialsProvider.java:68)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:132)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:89)
	at software.amazon.awssdk.services.sts.auth.StsCredentialsProvider.resolveCredentials(StsCredentialsProvider.java:78)
	at software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider.resolveCredentials(StsAssumeRoleCredentialsProvider.java:42)
	at software.aws.toolkits.jetbrains.core.credentials.CorrectThreadCredentialsProvider.resolveCredentials(CorrectThreadCredentialsProvider.kt:27)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileToolkitCredentialsProvider.resolveCredentials(ProfileToolkitCredentialsProvider.kt:54)
	at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:72)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:88)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.sts.DefaultStsClient.assumeRole(DefaultStsClient.java:265)
	at software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider.getUpdatedCredentials(StsAssumeRoleCredentialsProvider.java:68)
	at software.amazon.awssdk.services.sts.auth.StsCredentialsProvider.updateSessionCredentials(StsCredentialsProvider.java:68)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:132)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:89)
	at software.amazon.awssdk.services.sts.auth.StsCredentialsProvider.resolveCredentials(StsCredentialsProvider.java:78)
	at software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider.resolveCredentials(StsAssumeRoleCredentialsProvider.java:42)
	at software.aws.toolkits.jetbrains.core.credentials.CorrectThreadCredentialsProvider.resolveCredentials(CorrectThreadCredentialsProvider.kt:27)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileToolkitCredentialsProvider.resolveCredentials(ProfileToolkitCredentialsProvider.kt:54)
	at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:72)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:88)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.sts.DefaultStsClient.getCallerIdentity(DefaultStsClient.java:905)
	at software.amazon.awssdk.services.sts.StsClient.getCallerIdentity(StsClient.java:1682)
	at software.aws.toolkits.jetbrains.services.sts.StsResources$ACCOUNT$1.invoke(StsResources.kt:13)
	at software.aws.toolkits.jetbrains.services.sts.StsResources$ACCOUNT$1.invoke(StsResources.kt:10)
	at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:180)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetch(AwsResourceCache.kt:339)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetchIfNeeded(AwsResourceCache.kt:325)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.access$fetchIfNeeded(AwsResourceCache.kt:216)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:254)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:216)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1.run(AwsResourceCache.kt:253)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

.aws/config:

```
[default]
aws_access_key_id = default
aws_secret_access_key = default
output = json

[profile checkmarx-dev]
output = json
role_arn = arn:aws:iam::<ACCN>:role/<login role>
source_profile = default

[profile checkmarx-dev-exec]
role_arn = arn:aws:iam::<ACCN>:role/<role with access>
source_profile = checkmarx-dev
```

.aws/credentials:
```
[checkmarx-dev]
output = json
region = us-east-1
aws_access_key_id = <ACCESS KEY>
aws_secret_access_key = <SECRET KEY>
aws_session_token = <SESSION TOKEN>
```

**Comment by abrooksv** [comment]
It looks like you are mixing and matching credential sources for `checkmarx-dev`

Is there a reason that in config it uses source_profile, but in credentials you have it using static credentials?

`source_profile` takes precedence in the toolkit.

**Comment by Kirizan** [comment]
The way our company is setup we have to pull the access key/secret key programmatically every hour, and they are put in the credentials file. Since we are using multiple AWS accounts for different projects, I need to be able to have multiple credentials in the file (I can't just put everything under default).

I have tried putting the key information under the default profile in the config file just to see if I could get it to work, however that still gives the same "invalid token" error. I know the credentials were correct, since I made sure to refresh them before putting them in the config file.

If you try to remove the source_profile (or have the profile chain end on anything that isn't default), the toolkit won't load the profile at all.

All of this works without any issue using the AWS CLI without a problem. All I need to do is change the profile flag and I can run commands against different accounts.

Does the toolkit have the ability to read an environment variables from somewhere? I could look into create a specific config file for the toolkit and point the toolkit at that file using the environment variables.

**Comment by abrooksv** [comment]
Sorry, let me clarify. 

We support any number of profiles and what you describe (the source_profile chain) is valid, and tested (https://github.com/aws/aws-toolkit-jetbrains/blob/a52497c1c9905da7b1595c82fcd48f7170907f68/jetbrains-core/tst/software/aws/toolkits/jetbrains/core/credentials/ProfileCredentialProviderFactoryTest.kt#L311)

The issue I was referring to is the config and credentials files are merged when loaded. So from the IDE's perspective it sees:

```
[default]
aws_access_key_id = default
aws_secret_access_key = default
output = json

[profile checkmarx-dev]
output = json
role_arn = arn:aws:iam::<ACCN>:role/<login role>
source_profile = default
region = us-east-1
aws_access_key_id = <ACCESS KEY>
aws_secret_access_key = <SECRET KEY>
aws_session_token = <SESSION TOKEN>

[profile checkmarx-dev-exec]
role_arn = arn:aws:iam::<ACCN>:role/<role with access>
source_profile = checkmarx-dev
```

I am not sure what credentials you are actually trying to use for `checkmarx-dev`, but the toolkit should be using double assumed-role (`checkmarx-dev-exec` -> `checkmarx-dev` -> `default`). The order of precedence is here: https://github.com/aws/aws-toolkit-jetbrains/blob/a52497c1c9905da7b1595c82fcd48f7170907f68/jetbrains-core/src/software/aws/toolkits/jetbrains/core/credentials/profiles/ProfileCredentialProviderFactory.kt#L171

>Does the toolkit have the ability to read an environment variables from somewhere? I could look into create a specific config file for the toolkit and point the toolkit at that file using the environment variables. 

No, because the Env Vars are picked up once at startup (and never on Mac) so they would get out of date and require you to restart the IDE

**Comment by Kirizan** [comment]
Okay, I understand a bit better how the toolkit is using the two account. I agree about the properties location, let's see what's misconfigured before dealing with work arounds.

We authenticate through SSO and our internal AD. That authentication is assigned to the role in the checkmarx-dev profile. The only permissions associated with this role is the ability to assume the role checkmarx-dev-exec.

The role attached to checkmarx-dev-exec is the role that has permissions that can be used to do work.

One the CLI, I can point to the profile checkmarx-dev-exec and commands work as expected. If I point the AWS CLI to the profile checkmarx-dev I get the error "The security token included in the request is invalid".

Is there a way to enable debug logging to see the path the toolkit is taking through the assume role chain?

**Comment by abrooksv** [comment]
No there is not today.

Does it work if you remove the access key, secret key, session key from the credentials file and have a clean chain? Or are they required? It seems they are already expired if the CLI is giving you the same error.

**Comment by Kirizan** [comment]
> Does it work if you remove the access key, secret key, session key from the credentials file and have a clean chain? Or are they required?

If I remove the information from the credentials file, it doesn't work on the CLI or the tool. Which makes sense, because the account I log into my computer with doesn't have any permissions in our AWS environment. It's my admin account (which I cannot use to log in locally with) that has permissions to SSO into AWS. We also do not have the ability to create user accounts directly into the account, the authentication must go through the SSO.

>  It seems they are already expired if the CLI is giving you the same error.

The credentials hadn't expired. When I use "--profile checkmarx-dev" I get the error about the bad security token. If I then use "--profile checkmarx-dev-exec" the command works without an issue on the CLI. I can freely go back and forth, "checkmarx-dev" always fails, "checkmarx-dev-exec" always succeeds (until the hour is up and the credentials do expire).

I also tried building the config file how you said the IDE perceives it (by combining the credential file information) and then removing the credential file. The profiles were found, but the toolkit was still unable to switch to the profile.

How is the toolkit assuming the role? Is it differently than the CLI does it? I'm wondering if the toolkit required different permissions than the CLI.

**Comment by Kirizan** [comment]
I just updated to AWS Toolkit version 1.11-193 and this issue is still present.

**Comment by abrooksv** [comment]
I asked around, it seems to live in the "undocumented behavior" realm due to the mixing of the types of credentials in the same named profile.

**Comment by strowk** [comment]
I have the same problem now. At first it was working fine, but next day - stopped. I've updated credentials file and AWS CLI was working fine, but AWS Explorer said that token is expired. "Invalidate caches and restart" solved that, so I guess problem is that plugin caches token and does not see that underlying credentials file has changed and cache should be updated.

**Comment by abrooksv** [comment]
We have not tracked this down yet. We are relying on the JetBrains API for file watching but it only seems to notify the toolkit if the file is edited inside of the the ide. Outside modification only sometimes works.

**Comment by abrooksv** [comment]
Looked into this more. If the config/credentials files have not been opened in the IDE, the VirtualFileSystem of the IDE does not know about them. This means it ignores any notifications from the OS that the files were modified, even though we told it to watch those files.

Current work around is to open the files in the IDE to trigger the refresh. After that, it should continue to see updates while the IDE is open.
