### ISSUE TITLE
IntelliJ won't start with AWS Toolkit enabled - Resolve Proxy Port problem

### ISSUE THREAD

**Issue by SteveCaptainRogers** [aws/aws-toolkit-jetbrains#1755]
**Describe the bug**
I've just installed the AWS toolkit 

**To reproduce**

Install and enable AWS Tookit
Restart IntelliJ
See error on startup

**Expected behavior**
For the AWS toolkit to be enabled and working

**Screenshots**

**Your Environment**
- OS: Mac OS 10.15.4
- JetBrains product: IntelliJ
- JetBrains product version: IntelliJ IDEA 2019.3.5 (Ultimate Edition)
Build #IU-193.7288.26, built on May 6, 2020
Non-Bundled Plugins: Batch Scripts Support, CMD Support, Pythonid

- AWS Toolkit version: 1.14-193
- SAM CLI version: SAM CLI, version 0.48.0
- JVM/Python version: Runtime version: 11.0.6+8-b520.66 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Additional context**

My proxt settings in IntelliJ are set, and the Check Connection option comes back with success
![image](https://user-images.githubusercontent.com/60455117/81886190-68664580-95df-11ea-8e3f-c15f31c62ff8.png)

Here is the error received on startup of IntelliJ

Plugin 'aws.toolkit' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NumberFormatException: For input string: ""
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.base/java.lang.Integer.parseInt(Integer.java:662)
    at java.base/java.lang.Integer.parseInt(Integer.java:770)
    at java.base/java.util.Optional.map(Optional.java:265)
    at software.amazon.awssdk.http.apache.ProxyConfiguration.resolvePort(ProxyConfiguration.java:199)
    at software.amazon.awssdk.http.apache.ProxyConfiguration.<init>(ProxyConfiguration.java:66)
    at software.amazon.awssdk.http.apache.ProxyConfiguration.<init>(ProxyConfiguration.java:38)
    at software.amazon.awssdk.http.apache.ProxyConfiguration$DefaultClientProxyConfigurationBuilder.build(ProxyConfiguration.java:407)
    at software.amazon.awssdk.http.apache.ProxyConfiguration$DefaultClientProxyConfigurationBuilder.build(ProxyConfiguration.java:298)
    at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.<init>(ApacheHttpClient.java:394)
    at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.<init>(ApacheHttpClient.java:392)
    at software.amazon.awssdk.http.apache.ApacheHttpClient.builder(ApacheHttpClient.java:125)
    at software.aws.toolkits.jetbrains.core.AwsSdkClient$sdkHttpClient$2.invoke(AwsSdkClient.kt:30)
    at software.aws.toolkits.jetbrains.core.AwsSdkClient$sdkHttpClient$2.invoke(AwsSdkClient.kt:23)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at software.aws.toolkits.jetbrains.core.AwsSdkClient.getSdkHttpClient(AwsSdkClient.kt)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryPublisher$Companion.createDefaultTelemetryClient(DefaultTelemetryPublisher.kt:95)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryPublisher$Companion.access$createDefaultTelemetryClient(DefaultTelemetryPublisher.kt:86)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryPublisher.<init>(DefaultTelemetryPublisher.kt:24)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService.<init>(TelemetryService.kt:78)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
    at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
    at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
    at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:44)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
    at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
    at com.intellij.serviceContainer.ConstructorParameterResolver.resolveInstance(ConstructorParameterResolver.kt:64)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:45)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
    at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$3(ApplicationImpl.java:346)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:346)
    at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:204)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:398)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by SteveCaptainRogers** [comment]
I was provided a work around from someone at AWS.
Edit the IntelliJ vmoptions file to set the ports

vi ~/Library/Preferences/IntelliJIdea2019.3/idea.vmoptions 
Change
-Dhttp.proxyPort
-Dhttps.proxyPort
to
-Dhttp.proxyPort=8080
-Dhttps.proxyPort=8080

**Comment by abrooksv** [comment]
Is there a reason you are setting proxy settings in the IDE settings page as well as VM options?

I am not sure there is much we can do here from our end in the toolkit

The Java SDK V2 spins up default proxy settings when we go to create the Apache client. We later override those settings that disables the system properties and tell the SDK to pull the proxy config from the IDE's settings page.

The IDE actually seems to complain if you set both and they differ to the idea.log

**Comment by SteveCaptainRogers** [comment]
@abrooksv following on from your comment I tried one more thing and removed completely the proxy settings from the vmoptions, and it also works. 
So it works if those settings are not in vmptions and also if they are in vmoptions with a valid value, but not if they are in with a blank value.
TBH I have no idea how those settings ended up in the vmoptions - I certainly did not add them, so not sure if they are added by default on install, or if some action I performed through IntelliJ set them.

As far as I am concerned you can close the ticket as it is no longer causing me an issue. Thanks for you help.

**Comment by abrooksv** [comment]
Thank you for reaching out, sorry for the subpar experience but glad it is working for you now.
