### ISSUE TITLE
Access to .aws-sam directory denied

### ISSUE THREAD

**Issue by Dmitry2055** [aws/aws-toolkit-jetbrains#1763]
**Describe the bug**
Sometimes when attempting to re-run/debug a lambda on Windows the build fails with stacktrace:
```
"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" build Function --template C:\path\to\project\.aws-sam\build\template.yaml --build-dir C:\path\to\project\.aws-sam\build --use-container
Starting Build inside a container
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 67, in __enter__
    self._build_dir = self._setup_build_dir(self._build_dir, self._clean)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 89, in _setup_build_dir
    shutil.rmtree(build_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 404, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 402, in _rmtree_unsafe
OSError: [WinError 145] The directory is not empty: 'C:\\path\\to\\project\\.aws-sam\\build'
```

Subsequent attempts to Run/Debug result in different stacktrace:
```
"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" build Function --template C:\path\to\project\.aws-sam\build\template.yaml --build-dir C:\path\to\project\.aws-sam\build --use-container --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='Function' and CodeUri='C:/path/to/project'
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 258, 'exitReason': 'PermissionError', 'exitCode': 255, 'requestId': 'b648eb6c-2e72-4cfd-96ba-0792804ea349', 'installationId': '6bc97f54-aef1-4102-aafa-1e91304dec55', 'sessionId': '73349678-6b97-4f96-bbb2-d7c334ad3041', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.49.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 67, in __enter__
    self._build_dir = self._setup_build_dir(self._build_dir, self._clean)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 89, in _setup_build_dir
    shutil.rmtree(build_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 377, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 374, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\path\\to\\project\\.aws-sam\\build\\Function'
```

**To reproduce**
1. Select AWS Lambda Run/Debug configuration for the function
2. Click on 'Run' or 'Debug'
3. Wait until function ends
4. Click on 'Run' or 'Debug'
3. Go to 'Build' > 'Build Output'
4. See error message

**Expected behavior**
A Lambda is built and executed

**Screenshots**
First-time error:
![aws-toolkit-pycharm-output](https://user-images.githubusercontent.com/16222405/82121470-ef5d1e80-9795-11ea-8d70-4b67b485943b.png)
Subsequent errors: 
![image](https://user-images.githubusercontent.com/16222405/82121752-0bfa5600-9798-11ea-8136-57872f9f7c1c.png)

**Your Environment**
- OS: Windows 10
- JetBrains product: PyCharm
- JetBrains product version: 2020.1.1
- AWS Toolkit version: 1.14-201
- SAM CLI version: 0.49.0
- JVM/Python version: java version "1.8.0_181"/Python 3.8.1

**Additional context**
Inaccessible directory as seen from Explorer even though I'm admin: 
![aws-toolkit-bug](https://user-images.githubusercontent.com/16222405/82121472-f421d280-9795-11ea-90b4-19fa4b0df371.png)
Directory can be deleted after PC restart.
Reinstalling SAM CLI didn't help.
Also didn't observe such behavior when using SAM CLI.

**Comment by abrooksv** [comment]
Can you access it if you close the IDE?

**Comment by Dmitry2055** [comment]
> Can you access it if you close the IDE?

No, still getting 'Access Denied' for `...\.aws-sam\build\Function` directory

**Comment by abrooksv** [comment]
Which runtime are you using so I can track down the correct code path?

**Comment by Dmitry2055** [comment]
> Which runtime are you using so I can track down the correct code path?
python3.8, if you mean Lambda runtime

**Comment by abrooksv** [comment]
> > Which runtime are you using so I can track down the correct code path?
> 
> python3.8, if you mean Lambda runtime

I did, thank you

**Comment by ruifaguiar** [comment]
I have also this problem with JAVA8 for runtime.
The problem if temporary solved by restarting docker service. But will happen again on the next iteration.

**Comment by graesj** [comment]
I have the exact same problem with Java 11 and Maven.

If I run the "chkdsk" [1] command in the .aws-build folder in Administrator: Windows Powershell between the builds I am able re re-run it without the same error. Hope this works as a temporary solution for you as well.

[1] https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chkdsk

**Comment by abrooksv** [comment]
I am trying to come up with a way to replicate this. All the active devs on the toolkit run OSX and given the current situation in the world I can't walk down to IT and grab a Windows laptop.

**Comment by abrooksv** [comment]
I was not able to reproduce this given the steps.

Can you try following this so we can see what has the lock? https://gallery.technet.microsoft.com/How-to-find-out-which-c0d4e60e

**Comment by paolobelluticm** [comment]
The locking process is `Docker Desktop.exe`.

But it's more than a common lock. The `Function` subdirectory cannot be accessed in any way, not even with an administrator shell to retrieve its security metadata:
```
PS [lambda project directory]> Get-Acl .\.aws-sam\build\Function
Get-Acl : Access is denied
```
The path up to `.aws-sam\build`, in contrast, is sane:
```
PS [lambda project directory]> Get-Acl .\.aws-sam\build\

Path  Owner                        Access
----  -----                        ------
build PAOLOBELLUTIXPS\PaoloBelluti NT AUTHORITY\SYSTEM Allow  FullControl...
```

**Comment by abrooksv** [comment]
Is your docker desktop up to date. I'm curious if it's this

Fixed a file sharing issue that caused Docker Desktop to lock random files. Fixes docker/for-win#5624 and docker/for-win#5575.

I was running on a brand new windows machine with latest docker desktop for Windows and could not reproduce

**Comment by aforslow** [comment]
For me, it works if I remove the lambda docker container, i.e.
`docker ps -a`

> CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                         PORTS                                                      NAMES
> ce53555e4f2e        lambci/lambda:java11   "/var/rapid/init --b…"   24 minutes ago      Exited (1) 21 minutes ago                                                                 <container_name>

`docker rm <container_name>`

After that, I can run `sam build` again.

**Comment by sidharthramesh** [comment]
I have the same issue on Windows 10. Restarting Docker fixes it. Is this a docker issue?

**Comment by georgematthew** [comment]
I am also seeing this behavior. After the first sam build, subsequent attempts to run sam build fail to delete the existing build directory with the following error:
`PermissionError: [WinError 5] Access is denied: 'C:\\Users\\User\\Projects\\project\\.aws-sam\\build\\InventoryFunction'`

Attempts to manually delete the build directory also fail.

**Comment by PCI-API** [comment]
Getting the same error on my machine as well. Even trying to run a simple hello world built in AWS lambda function on intellij with no code changes will result in a successful run on the first go, but the same "PermissionError" or "OSError" on subsequent runs. Any assistance on this would be greatly appreciated.

**Comment by sidharthramesh** [comment]
I have noticed that running `sam local invoke <function>` a couple of times also somehow solves it. This might have something to do with `sam local invoke` not properly removing the container on exit sometimes?

**Comment by 50l3r** [comment]
I have the same problem. Docker desktop lock the build folder even if not exist docker containers:

![](https://i.gyazo.com/262f65f1395bd48987c7bd4cd6cd35ce.png)

**Comment by danerlt** [comment]
I am running into the same issue.

trackback:
```
C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" build Function --template D:\work\qar_backend\.aws-sam\build\template.yaml --build-dir D:\work\qar_backend\.aws-sam\build
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 69, in __enter__
    self._build_dir = self._setup_build_dir(self._build_dir, self._clean)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 91, in _setup_build_dir
    shutil.rmtree(build_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 377, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 374, in _rmtree_unsafe
PermissionError: [WinError 5] 拒绝访问。: 'D:\\work\\qar_backend\\.aws-sam\\build\\Function'

```

**Comment by lapickett** [comment]
I am facing the same exact issue, and am forced to restart docker each time I want to locally run my AWS function again.

**Comment by AbsentmindedInsanity** [comment]
I have this same issue with latest docker build and pycharm

**Comment by Shrined** [comment]
I have the same exact issue as well.

**Comment by Shrined** [comment]
`Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 69, in __enter__
    self._build_dir = self._setup_build_dir(self._build_dir, self._clean)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 91, in _setup_build_dir
    shutil.rmtree(build_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 377, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 374, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\....'
`

**Comment by abrooksv** [comment]
Docker issue: https://github.com/docker/for-win/issues/6938

**Comment by researchdeveloping** [comment]
The same problem on Windows with Dotnet lambda via AWS Toolkit in Ridler (as I suppose is Docker problem).

**Comment by andrevega3** [comment]
I and others I know have this same issue regularly. We use pycharm and python. Restarting docker is now part of the development process lol

**Comment by strel0k** [comment]
Just encountered the same issue here. Error log is more or less the same as the above:

    File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
    File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
    File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
    [...]
    File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 91, in _setup_build_dir
    shutil.rmtree(build_dir)
    File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
    File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
    File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
    File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 404, in _rmtree_unsafe
    File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 402, in _rmtree_unsafe
    PermissionError: [WinError 5] Access is denied: 'C:\\Users\\D\\Google Drive\\xxxxxxxxxxxxx\\.aws-sam\\build\\Function\\.serverless'

**Comment by sidharthramesh** [comment]
Using SAM on Windows was close to unusable due to this issue. However, using docker in WSL2 mode, I can confirm that the issue has been resolved. With the new windows update, even Windows Home users can run docker using WSL2. The **files you're working on must be kept within the Linux subsystem directory for usable speeds**. Except for that, this has been a game-changer for me.
