### ISSUE TITLE
Memory leak in CloudWatch Logs (noticed while closing the IDE)

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#1798]
Version is 1.16 master

Reproduce by closing the IDE with the CW Logs tool window open

```
2020-05-27 14:38:05,873 [ 585545]  ERROR - tellij.openapi.util.ObjectTree - Memory leak detected: 'software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogGroupActor@49e52e9b' of class software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogGroupActor
See the cause for the corresponding Disposer.register() stacktrace:
 
java.lang.RuntimeException: Memory leak detected: 'software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogGroupActor@49e52e9b' of class software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogGroupActor
See the cause for the corresponding Disposer.register() stacktrace:

	at com.intellij.openapi.util.ObjectTree.assertIsEmpty(ObjectTree.java:226)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:130)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:621)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:578)
	at com.intellij.openapi.application.ex.ApplicationEx.exit(ApplicationEx.java:85)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$null$3(MacOSApplicationProvider.java:84)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$submit$7(MacOSApplicationProvider.java:175)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.ObjectNode.<init>(ObjectNode.java:35)
	at com.intellij.openapi.util.ObjectTree.createNodeFor(ObjectTree.java:106)
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:70)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:65)
	at com.intellij.openapi.application.constraints.ExpirationKt.tryRegisterDisposable(Expiration.kt:124)
	at com.intellij.openapi.application.constraints.ExpirationKt.cancelJobOnDisposal(Expiration.kt:148)
	at com.intellij.openapi.application.constraints.DisposableExpiration$job$2.invoke(Expiration.kt:79)
	at com.intellij.openapi.application.constraints.DisposableExpiration$job$2.invoke(Expiration.kt:76)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.openapi.application.constraints.DisposableExpiration.getJob(Expiration.kt)
	at com.intellij.openapi.application.constraints.DisposableExpiration.getJob(Expiration.kt:76)
	at com.intellij.openapi.application.constraints.AbstractExpiration.invokeOnExpiration(Expiration.kt:54)
	at com.intellij.openapi.application.constraints.ExpirationKt.invokeOnExpiration(Expiration.kt:104)
	at com.intellij.openapi.application.constraints.ExpirationKt.cancelJobOnExpiration(Expiration.kt:107)
	at com.intellij.openapi.application.constraints.ExpirableContinuationInterceptor.interceptContinuation(ConstrainedCoroutineDispatcher.kt:44)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.intercepted(ContinuationImpl.kt:112)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.intercepted(IntrinsicsJvm.kt:137)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogActor.tableLoading(LogActor.kt:158)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogActor.loadAndPopulate(LogActor.kt:125)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogGroupActor.loadInitial(LogActor.kt:310)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogActor.handleMessages(LogActor.kt:100)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.LogActor$1.invokeSuspend(LogActor.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by hunterwerlla** [comment]
I looked into this and it seems like cancellable coroutine is what is leaking (from this block)
```
    private suspend fun tableLoading() = withContext(edtContext) {
        table.setPaintBusy(true)
        table.emptyText.text = message("loading_resource.loading")
    }
```
which is strange
