### ISSUE TITLE
Intermittent SAM template generation failure

### ISSUE THREAD

**Issue by hunterwerlla** [aws/aws-toolkit-jetbrains#1978]
- On Mac
- SAM 1.0

```
2020-08-10 14:45:44,083 [  54179]  ERROR - intellij.openapi.progress.Task - java.lang.RuntimeException: Could not execute `sam init`!: [Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git, Error: Unstable state when updating app templates. Check that you have permissions to create/delete files in the AWS SAM shared directory or file an issue at https://github.com/awslabs/aws-sam-cli/issues] 
java.util.concurrent.CompletionException: java.lang.RuntimeException: Could not execute `sam init`!: [Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git, Error: Unstable state when updating app templates. Check that you have permissions to create/delete files in the AWS SAM shared directory or file an issue at https://github.com/awslabs/aws-sam-cli/issues]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at software.aws.toolkits.jetbrains.core.executables.DefaultExecutableManager$getExecutable$1.run(ExecutableManager.kt:125)
```

**Comment by rli** [comment]
closing due to age and haven't seen any other customer reports
