### ISSUE TITLE
Retry does not re-read credentials file

### ISSUE THREAD

**Issue by strowk** [aws/aws-toolkit-jetbrains#2275]
**Describe the bug**
When I update credentials file, plugin does not see new creds.

**To reproduce**
1. prepare profile and credentials in ~/.aws/config and ~/.aws/credentials
1. make creds in ~/.aws/credentials wrong
1. start Intellij Idea (plugin should already be installed)
1. as expected - plugin will show "Invalid AWS Connection"
1. fix creds in file ~/.aws/credentials
1. click Retry
1. still invalid connection
1. restart IDE
1. now it's connected OK

**Expected behavior**
Retry should really retry everything, including reading creds file. No IDE restart should be needed.

**Your Environment**
- OS: Ubuntu 20.04
- JetBrains product: Intellij Idea
- JetBrains product version: 2020.3
- AWS Toolkit version: 1.22-203
- SAM CLI version: --not important--
- JVM/Python version: jdk8

**Additional context**
In real use bug happens because credentials file has token from SSO and it becomes invalid after 12 hours, however toolkit keeps caching it somehow and even "Retry" does not work as expected. Firstly "Retry" must be fixed. Once it is figured out how to reload creds, it ideally should be done automatically on some sort of regular schedule.

**Comment by abrooksv** [comment]
We instruct IntelliJ to watch the credentials file and notify us of changes so we re-parse it but a few people have reported issues with this but we have not been able to reproduce it.

Could you try the following:

Try to edit the credentials file through the IDE by hitting the Edit Credentials File menu item under All Credentials.
<img width="448" alt="Screen Shot 2020-12-09 at 9 46 26 AM" src="https://user-images.githubusercontent.com/8992246/101666733-6d6b6600-3a03-11eb-8c96-bd22d28a4190.png">

Make some changes (even just new lines) and hit Cntrl+S to force a save.

If that works, that indicates it is the ProfileWatcher class not getting updates.

We have added debug logs to this that can be enabled by going to: Help->Diagnostic Tools->Debug Log Settings and adding:

```
software.aws.toolkits.jetbrains.core.credentials.profiles
```

and open the logs through the Help menu as well and look for logs for ProfileWatcher

e.g.
```
ProfileWatcher - Starting profile watcher, profile locations: [...] 
ProfileWatcher - Received events: [...] 
ProfileWatcher - Profile file change detected, scheduling refresh 
```

**Comment by strowk** [comment]
I tried doing following - 

1. break credentials file
1. open IDE, see "Unable to connect to AWS"
1. Click dropdown in AWS Explorer, All Credentials, Edit Credentials Files
1. fixed token and save - did not work at first, I've seen message "Non-Project Files Protection"
1. selected "I wanted to edit this file anyway" and pressed ok
1. clicked retry in AWS Explorer
1. same error
1. restarted IDE 
1. AWS explorer works
1. added "software.aws.toolkits.jetbrains.core.credentials.profiles" in the Debug Log Settings 
1. exited from IDE
1. broken creds file again
1. opened IDE
1. again Edit Credentials files
1. fixed token
1. Retry 
1. same error
1. restarted IDE 
1. it worked

In logs I found this 
```
2020-12-08 13:35:01,429 [ 109123]   INFO - ntials.profiles.ProfileWatcher - Starting profile watcher, profile locations: [/home/user/.aws/config, /home/user/.aws/credentials] 
2020-12-08 13:35:01,432 [ 109126]   INFO - ntials.profiles.ProfileWatcher - Added watch roots: [/home/user/.aws] 
```
(times here even before I did all tests and changed log config, so it appears no matter debug or not).

Later when debug was enabled I see  
```
2020-12-09 19:35:36,793 [  34074]  DEBUG - ntials.profiles.ProfileWatcher - Received events: [VfsEvent[update: file:///home/tim/.aws/credentials]] 
2020-12-09 19:35:36,793 [  34074]   INFO - ntials.profiles.ProfileWatcher - Profile file change detected, scheduling refresh 
 
```
but then still 
```
2020-12-09 19:35:39,881 [  37162]   WARN - edentials.AwsConnectionManager - Failed to switch to profile 'Profile:my-profile' 
software.amazon.awssdk.services.sts.model.StsException: The security token included in the request is invalid (Service: Sts, Status Code: 403, Request ID: 682b3e14-8945-43ae-ad9a-8c2aaae87b17, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:133)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:159)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:112)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.sts.DefaultStsClient.assumeRole(DefaultStsClient.java:288)
	at software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider.getUpdatedCredentials(StsAssumeRoleCredentialsProvider.java:67)
	at software.amazon.awssdk.services.sts.auth.StsCredentialsProvider.updateSessionCredentials(StsCredentialsProvider.java:80)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:132)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:89)
	at software.amazon.awssdk.services.sts.auth.StsCredentialsProvider.resolveCredentials(StsCredentialsProvider.java:91)
	at software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider.resolveCredentials(StsAssumeRoleCredentialsProvider.java:41)
	at software.aws.toolkits.jetbrains.core.credentials.CorrectThreadCredentialsProvider.resolveCredentials(CorrectThreadCredentialsProvider.kt:27)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$AwsCredentialProviderProxy.resolveCredentials(CredentialManager.kt:73)
	at software.aws.toolkits.core.credentials.ToolkitCredentialsProvider.resolveCredentials(ToolkitCredentialsProvider.kt)
	at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:76)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:97)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.sts.DefaultStsClient.getCallerIdentity(DefaultStsClient.java:982)
	at software.amazon.awssdk.services.sts.StsClient.getCallerIdentity(StsClient.java:1611)
	at software.aws.toolkits.jetbrains.services.sts.StsResources$ACCOUNT$1.invoke(StsResources.kt:12)
	at software.aws.toolkits.jetbrains.services.sts.StsResources$ACCOUNT$1.invoke(StsResources.kt:10)
	at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:224)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetch(AwsResourceCache.kt:379)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.fetchIfNeeded(AwsResourceCache.kt:365)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache.access$fetchIfNeeded(AwsResourceCache.kt:260)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:293)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1$result$1.apply(AwsResourceCache.kt:260)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$getCachedResource$1.run(AwsResourceCache.kt:292)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Here's the message I received when tried firstly to edit credentials file like you suggested:

![Screenshot from 2020-12-09 19-29-58](https://user-images.githubusercontent.com/25692644/101673471-7f76f400-3a57-11eb-9e0a-5cdda6a4435b.png)

**Comment by abrooksv** [comment]
What type of credentials are you using?

**Comment by strowk** [comment]
We have some sort of SSO integration with AWS. In credentials file there are `aws_access_key_id`,  `aws_session_token` and `valid_until`. Token is usually valid for a limited amount of time and after relogin I have to restart IDE too. Additional custom CLI tool updates the file when I login with it.

**Comment by abrooksv** [comment]
That should be fine, we are detecting the profile as having the all the required keys since you are able to select it.

We do a comparison of the profile and if the values in it change, we notify the sub-components of the toolkit to invalidate everything that used that credential profile. I am not sure where it would be breaking down. Looks like we will need to add more logs.

Off topic: `credential_process` based profile is probably the most compatible route for your use case since not all SDKs can handle re-parsing of the credentials file. (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html)

**Comment by assiotis** [comment]
I have the same exact problem, seems to be due to caching somewhere in the AWS SDK. 

In my case, I have a common set of credentials and different profiles with different role ARNs I can assume. Thus the `StsAssumeRoleCredentialsProvider` is at play.  In `ProfileCredentialProviderFactory.kt` which eventually gets called during a refresh, some variables are captured by closure in the `Supplier` provided to builder via refreshRequest(), including the session name. If I change the `role_session_name` in my config to something else, the refresh happens successfully. 

To reproduce, modify the OPs original steps slightly as follows:

1a. Prepare ~/.aws/credentials:
```
[default]
aws_security_token = blablabla
aws_secret_access_key = blablabla
aws_session_token = blablabla
aws_access_key_id = blablabla
```

1b. Prepare ~/.aws/config
```
[profile main-infra-admin]
role_arn = arn:aws:iam:::role/role-name
source_profile = default
role_session_name = mysession
```

2. make creds in ~/.aws/credentials wrong
3. start Intellij Idea (plugin should already be installed)
4. as expected - plugin will show "Invalid AWS Connection"
5. fix creds in file ~/.aws/credentials
6. click Retry
7. still invalid connection
8. In ~/.aws/config/, change `role_session_name = mysession2`
9. Observe flawless reloading of credentials, retry does not even appear

**Comment by abrooksv** [comment]
Thank you for the detailed reproduction steps @assiotis , I now see the issue, and it's that changing the source_profile does not invalidate the profiles that depend upon it.

**Comment by anshupitlia-tw** [comment]
I am still facing this issue.

**Comment by juparker37** [comment]
This is still happening in `PyCharm 2024.1.4 (Professional Edition)` `Build #PY-241.18034.82, built on June 24, 2024`
