### ISSUE TITLE
Error after installing the plugin

### ISSUE THREAD

**Issue by Jonatha1983** [aws/aws-toolkit-jetbrains#2313]
Just installed the plugin and cannot create new project, the create new project panel is not showing at all and I see the following exception:
```java.lang.IllegalStateException: ServiceManager.getServic…ctionManager::class.java) must not be null
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager$Companion.getInstance(AwsConnectionManager.kt:244)
	at software.aws.toolkits.jetbrains.ui.connection.AwsConnectionSettingsSelector.<init>(AwsConnectionSettingsSelector.kt:28)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SchemaSelectionPanel.<init>(SchemaSelectionPanel.kt:28)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectGenerator.<init>(SamProjectGenerator.kt:42)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectGeneratorIntelliJAdapter.createTemplates(SamProjectGeneratorIntelliJShims.kt:191)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectGeneratorIntelliJAdapter.createTemplates(SamProjectGeneratorIntelliJShims.kt:190)
	at com.intellij.ide.projectWizard.ProjectTypeStep.getTemplatesMap(ProjectTypeStep.java:231)
	at com.intellij.ide.projectWizard.ProjectTypeStep.fillTemplatesMap(ProjectTypeStep.java:272)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:103)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:51)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:40)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:20)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:198)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:396)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:364)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
...
```

IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Licensed to Taboola.com Ltd

Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 6077M
Cores: 8
Registry: analyze.exceptions.on.the.fly=true, debugger.watches.in.variables=false, ide.browser.jcef.headless.enabled=true, ide.balloon.shadow.size=0, git.merge.conflicts.toolwindow=true
Non-Bundled Plugins: PlantUML integration, com.intellij.ideolog, org.jetbrains.plugins.go-template, AWSCloudFormation, com.intellij.kubernetes, com.taboola.RelengsTools, org.jetbrains.kotlin, no.tornado.tornadofx.idea, io.ktor.intellij.plugin, com.jetbrains.php, aws.toolkit

**Comment by rli** [comment]
`AwsConnectionManager.kt:244` is a weird place to be getting an exception. Part of the stack trace looks missing; can you share the whole thing?

Does the issue persists after restarting the IDE?

**Comment by Jonatha1983** [comment]
```
java.lang.IllegalStateException: ServiceManager.getServic…ctionManager::class.java) must not be null
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager$Companion.getInstance(AwsConnectionManager.kt:244)
	at software.aws.toolkits.jetbrains.ui.connection.AwsConnectionSettingsSelector.<init>(AwsConnectionSettingsSelector.kt:28)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SchemaSelectionPanel.<init>(SchemaSelectionPanel.kt:28)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectGenerator.<init>(SamProjectGenerator.kt:42)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectGeneratorIntelliJAdapter.createTemplates(SamProjectGeneratorIntelliJShims.kt:191)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectGeneratorIntelliJAdapter.createTemplates(SamProjectGeneratorIntelliJShims.kt:190)
	at com.intellij.ide.projectWizard.ProjectTypeStep.getTemplatesMap(ProjectTypeStep.java:231)
	at com.intellij.ide.projectWizard.ProjectTypeStep.fillTemplatesMap(ProjectTypeStep.java:272)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:103)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:51)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:40)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:20)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:198)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:396)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:364)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-12-30 21:23:50,020 [ 203493]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.3  Build #IU-203.5981.155 
2020-12-30 21:23:50,020 [ 203493]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-12-30 21:23:50,020 [ 203493]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2020-12-30 21:23:50,020 [ 203493]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: AWS Toolkit version: 1.22-203 
2020-12-30 21:23:50,020 [ 203493]  ERROR - llij.ide.plugins.PluginManager - Last Action: NewProject 
```
Yes it persists. 
I also tried to uninstall and reinstall the plugin but same issue.

**Comment by Jonatha1983** [comment]
Also in the IDEA Fatal Error dialog the link to report to AWS bring the user in here:
https://aws.amazon.com/

I think the link can be change to the github issue or some other place related to the plugin - can I contribute in that ?

**Comment by rli** [comment]
> I think the link can be change to the github issue or some other place related to the plugin - can I contribute in that ?

The link is keyed to the "vendor URL" property in the [plugin.xml](https://github.com/aws/aws-toolkit-jetbrains/blob/master/jetbrains-core/resources/META-INF/plugin.xml#L55), if you'd like to submit a PR, otherwise it'd only be a couple minutes for us to do it.
