### ISSUE TITLE
Cannot connect to AWS Aurora MySQL DBCluster due to "missing class" error

### ISSUE THREAD

**Issue by Bissector** [aws/aws-toolkit-jetbrains#2344]
**Describe the bug**
I have serverless AWS Aurora MySQL DBCluster up and running, but when I try to connect to it from IntelliJ IDEA 2020.2 with AWS Toolkit installed (latest version).  I am consistently getting error described below.

**To reproduce**
1. Go to 'Database' tool window
2. Click on 'New' to add new datasource
3. Choose settings: Connection type='URL only', Driver='MySQL', Authentication='SecretsManager Auth', Credentials='Profile:XXX', Region='eu-central-1', Secret Name/ARN='XXXXXX', URL='jdbc:mysql://_cluster_name_.cluster-XXXXXXXX.eu-central-1.rds.amazonaws.com:3306
4. Click on 'Test connection'
5. See error 'Missing class Could not initialize class software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService.'

**Expected behavior**
Expecting to connect to my db cluster.

**Screenshots**
<img width="737" alt="Screen Shot 2021-01-14 at 08 22 34" src="https://user-images.githubusercontent.com/39087892/104552535-b2f20300-5641-11eb-8507-b5a00e43820a.png">

**Your Environment**
- OS: MacOS Catalina 10.15.7
- JetBrains product: IntelliJ IDEA Ultimate
- JetBrains product version: 2020.2.3
- AWS Toolkit version: 1.22-202
- SAM CLI version: aws cli 2.1.18
- JVM/Python version: 1.8.0_271

**Comment by hunterwerlla** [comment]
@Bissector That is very strange, it seems like the plugin was not installed properly. Can you open the idea.log file using `help->show log in finder/explorer` and copy paste the stacktrace produced when this happens? After that, can you try uninstalling and reinstalling the plugin?

**Comment by Bissector** [comment]
I still can't connect to my DB due to connection timeout, but this is my problem.

**Reinstalling the plugin helped, thank you.**

FYI stacktrace was:
```
2021-01-15 09:19:33,181 [92009758]   WARN - alects.mysql.MysqlErrorHandler - Could not initialize class software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService 
java.lang.NoClassDefFoundError: Could not initialize class software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.serviceContainer.BaseComponentAdapter.getImplementationClass(BaseComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:107)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:413)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:395)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:20)
	at software.aws.toolkits.jetbrains.services.telemetry.TelemetryService$Companion.getInstance(TelemetryService.kt:78)
	at software.aws.toolkits.telemetry.RdsTelemetry.getCredentials(TelemetryDefinitions.kt:6249)
	at software.aws.toolkits.telemetry.RdsTelemetry.getCredentials$default(TelemetryDefinitions.kt:6247)
	at software.aws.toolkits.jetbrains.datagrip.auth.SecretsManagerAuth$intercept$2.invokeSuspend(SecretsManagerAuth.kt:84)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
