### ISSUE TITLE
Invalid AWS Connection - Failed to validate your AWS credentials - my credentials are correct I can use aws cli/sam.

### ISSUE THREAD

**Issue by martin-trimdata** [aws/aws-toolkit-jetbrains#2423]
Hello,
IntelliJ is unable to load my AWS credentials.  The credentials are under the default section in the C:\\Users\\myuser\\.aws\\credentials file and I am able to run AWS CLI just fine from powershell, such as aws s3 sync etc. which use the same credentials. 

When I click on the more info field I get this error:

Failed to validate your AWS credentials
Unable to connect to AWS:
CLIENT_ENDPOINT
![image](https://user-images.githubusercontent.com/78177994/107110334-f8ef5080-6814-11eb-9c83-21ce2ebc5e5e.png)

OS: Win10 20H2 64-bit
IntelliJ IDEA 2020.2.3 CE latest update (Jan 25)
AWS toolkit: 1.23-203

**Comment by abrooksv** [comment]
Can you look for errors in the idea.log file (You should be able to find it in the Help menu of the IDE).

The log line should contain `Failed to switch to profile`

**Comment by martin-trimdata** [comment]
Hello and thank you for responding.  
I am trying to connect to us-east-1, which is specified in the config file under the .aws folder under the same [default] profile.

Here is the log excerpt from idea.log:
2021-02-06 01:31:38,532 [1185951]   WARN - edentials.AwsConnectionManager - Failed to switch to profile 'Profile:default' 
java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: CLIENT_ENDPOINT
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager.validate(AwsConnectionManager.kt:242)
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager$validateCredentials$1.run(AwsConnectionManager.kt:172)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchFieldError: CLIENT_ENDPOINT
	at software.amazon.awssdk.awscore.client.handler.AwsClientHandlerUtils.createExecutionContext(AwsClientHandlerUtils.java:96)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.createExecutionContext(AwsSyncClientHandler.java:68)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:97)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:94)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.sts.DefaultStsClient.getCallerIdentity(DefaultStsClient.java:982)
	at software.amazon.awssdk.services.sts.StsClient.getCallerIdentity(StsClient.java:1611)
	at software.aws.toolkits.jetbrains.services.sts.StsResources$ACCOUNT$1.invoke(StsResources.kt:12)
	at software.aws.toolkits.jetbrains.services.sts.StsResources$ACCOUNT$1.invoke(StsResources.kt:10)
	at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:230)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$fetch$value$1.invokeSuspend(AwsResourceCache.kt:402)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	... 7 more

**Comment by abrooksv** [comment]
Can you try uninstalling and re-installing the plugin? It seems like a possibly corrupted install. It can't find a field inside of the SDK. That usually means a version mismatch between the jars.

**Comment by martin-trimdata** [comment]
I had tried uninstalling and reinstalling it, but I had actually just disabled it.  I completely removed the plugin and redownloaded it from the marketplace now, and thank you, it connects now.
