### ISSUE TITLE
java.lang.IllegalStateException: Unknown service schemas in aws-us-gov @ isServiceGlobal(ToolkitRegionProvider.kt:49)

### ISSUE THREAD

**Issue by rrrix** [aws/aws-toolkit-jetbrains#2435]
**Describe the bug**

Exception on application/plugin startup when using AWS GovCloud (`aws-us-gov` partition). https://gist.github.com/rrrix/6b0c3847015b425aeb07d193a5a933e3 

```
12:57 PM	Failed loading resources
java.lang.IllegalStateException: Unknown service schemas in aws-us-gov
at software.aws.toolkits.core.region.ToolkitRegionProvider.isServiceGlobal(ToolkitRegionProvider.kt:49)
at software.aws.toolkits.core.ToolkitClientManager.getClient(ToolkitClientManager.kt:54)
at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:229)
at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$fetch$value$1.invokeSuspend(AwsResourceCache.kt:402)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(... (show balloon)
```

**To reproduce**

My `default` AWS CLI profile is an IAM user for AWS GovCloud, using `us-gov-west-1` as the default region.

`aws sts get-caller-identity` looks like:

```yaml
$ aws sts get-caller-identity --region us-gov-west-1 --profile default --output yaml | grep 'Arn'
Arn: arn:aws-us-gov:iam::XXXXXXXXXXXX:user/user.name
```

* Installed toolkit version `1.23-203`
* Using PyCharm Professional 2020.3.3
* AWS CLI v2 `aws-cli/2.1.26 Python/3.9.1 Darwin/19.6.0 source/x86_64 prompt/off`

**Expected behavior**

No exceptions :) 

**Screenshots**

https://gist.github.com/rrrix/6b0c3847015b425aeb07d193a5a933e3 

**Your Environment**
- OS: MacOS Catalina 10.15.7
- JetBrains product: PyCharm Professional
- JetBrains product version: 2020.3.3
- AWS Toolkit version: 1.23-203
- SAM CLI version: `1.18.1`
- JVM version: 11.0.9.1+11-b1145.77 x86_64
- Python version: 3.9.1 (python.org)

**Comment by abrooksv** [comment]
Thanks for the bug report, the call being triggered on start up is pending release. 

The gov cloud issue is new though and we should gracefully handle that situation.
