### ISSUE TITLE
Telemetry system does not respect dispose life cycle correctly

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#2531]
```
software.aws.toolkits.jetbrains.services.s3.S3VirtualBucketTest > getUrlError STANDARD_ERROR
    ERROR: Cannot create software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager because container is already disposed: Project(name=project_null_1qcyKDEiIBCNx6BL0OarpnWFsmj, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\ContainerAdministrator\AppData\Local\Temp\project_null_1qcyKDEiIBCNx6BL0OarpnWFsmj.ipr) (disposed)
    com.intellij.serviceContainer.AlreadyDisposedException: Cannot create software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager because container is already disposed: Project(name=project_null_1qcyKDEiIBCNx6BL0OarpnWFsmj, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\ContainerAdministrator\AppData\Local\Temp\project_null_1qcyKDEiIBCNx6BL0OarpnWFsmj.ipr) (disposed)
    	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:522)
    	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:498)
    	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
    	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
    	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager$Companion.getInstance(AwsConnectionManager.kt:258)
    	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManagerKt.activeRegion(AwsConnectionManager.kt:326)
    	at software.aws.toolkits.jetbrains.services.telemetry.TelemetryService.record(TelemetryService.kt:40)
    	at software.aws.toolkits.telemetry.AwsTelemetry.validateCredentials(TelemetryDefinitions.kt:1336)
    	at software.aws.toolkits.telemetry.AwsTelemetry.validateCredentials(TelemetryDefinitions.kt:1384)
    	at software.aws.toolkits.telemetry.AwsTelemetry.validateCredentials$default(TelemetryDefinitions.kt:1382)
    	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager$validateCredentials$1.run(AwsConnectionManager.kt:180)
    	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)

```

**Comment by abrooksv** [comment]
We should do a `getServiceIfCreated` on the `AwsConnectionManager`, if it return null use unknown vaues for region / account ID
