### ISSUE TITLE
[Flaky Test] Integration tests leak threads for SAM invoke

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#2541]
```

java.lang.AssertionError: Thread leaked: Thread[/root/.pyenv/shims/sam local invoke --template /tmp/unitTest5481060011023599364/.aws-sam/build/template.yaml --event /tmp/Test-event.json --debug-port 45413,4,main] (alive) WAITING
--
--- its stacktrace:
at java.base@11.0.10/java.lang.Object.wait(Native Method)
at java.base@11.0.10/java.lang.Object.wait(Object.java:328)
at java.base@11.0.10/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
at app//com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:38)
at app//com.intellij.execution.process.ProcessWaitFor$$Lambda$396/0x00000001004c7440.run(Unknown Source)
at app//com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
at app//com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:33)
at app//com.intellij.execution.process.ProcessWaitFor$$Lambda$394/0x00000001004c7c40.run(Unknown Source)
at java.base@11.0.10/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@11.0.10/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.10/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
at java.base@11.0.10/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
at java.base@11.0.10/java.security.AccessController.doPrivileged(Native Method)
at java.base@11.0.10/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
at java.base@11.0.10/java.lang.Thread.run(Thread.java:829)
---
(diagnostic: 0: java.lang.Object : false . wait : false 2: java.lang.ProcessImpl : false . waitFor : false)
 
Leaking threads dump:
"/root/.pyenv/shims/sam local invoke --template /tmp/unitTest5481060011023599364/.aws-sam/build/template.yaml --event /tmp/Test-event.json --debug-port 45413" (alive) WAITING
at java.base@11.0.10/java.lang.Object.wait(Native Method)
at java.base@11.0.10/java.lang.Object.wait(Object.java:328)
at java.base@11.0.10/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
at app//com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:38)
at app//com.intellij.execution.process.ProcessWaitFor$$Lambda$396/0x00000001004c7440.run(Unknown Source)
at app//com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
at app//com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:33)
at app//com.intellij.execution.process.ProcessWaitFor$$Lambda$394/0x00000001004c7c40.run(Unknown Source)
at java.base@11.0.10/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@11.0.10/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.10/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
at java.base@11.0.10/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
at java.base@11.0.10/java.security.AccessController.doPrivileged(Native Method)
at java.base@11.0.10/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
at java.base@11.0.10/java.lang.Thread.run(Thread.java:829)


```

Looks like we are not fully waiting for the run configuration to finish

**Comment by abrooksv** [comment]
Looks like the 4min future timed out (so it gave up leaving orphaned process), not that we werent waiting long enough

Test output:
````
2021-04-06 01:01:28 DEBUG CliBasedStep:73 - [STDERR] 
2021-04-06 01:01:28 DEBUG CliBasedStep:73 - [STDERR] Mounting /tmp/unitTest5481060011023599364/.aws-sam/build/Function as /var/task:ro,delegated inside runtime container
2021-04-06 01:01:29 DEBUG CliBasedStep:73 - [STDERR] START RequestId: 12416fae-9d3d-4f2a-b703-9bcb6f2bbfe7 Version: $LATEST
2021-04-06 01:01:29 DEBUG CliBasedStep:73 - [STDERR] Debugger listening on ws://0.0.0.0:45413/1ba59a64-c001-45d0-ad3b-c09d6048fc39
2021-04-06 01:01:29 DEBUG CliBasedStep:73 - [STDERR] For help, see: https://nodejs.org/en/docs/inspector
2021-04-06 01:03:29 WARN  BaseOSProcessHandler:26 - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: /root/.pyenv/shims/sam local invoke --template /tmp/unitTest5481060011023599364/.aws-sam/build/template.yaml --event /tmp/Test-event.json --debug-port 45413
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:32)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:49)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:37)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:24)
	at com.intellij.execution.process.KillableColoredProcessHandler.<init>(KillableColoredProcessHandler.java:29)
	at software.aws.toolkits.jetbrains.utils.execution.steps.CliBasedStep$execute$processHandler$1.<init>(CliBasedStep.kt:49)
	at software.aws.toolkits.jetbrains.utils.execution.steps.CliBasedStep.execute(CliBasedStep.kt:49)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run(Step.kt:24)
	at software.aws.toolkits.jetbrains.utils.execution.steps.ParallelStep$execute$$inlined$forEach$lambda$1.run(ParallelStep.kt:36)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Seems we never attached to the debugger.

BuildID: Linux_Integration_Tests-2020-3-Pipeline:73b21cb7-de02-4e52-a3c8-e93a57d0e7a0

**Comment by rli** [comment]
Closing since this appears to be fixed now
