### ISSUE TITLE
Lambda Rider - Resharper RPC timed out in 3000 ms

### ISSUE THREAD

**Issue by koengroten** [aws/aws-toolkit-jetbrains#2566]
When right clicking on one of my AWS Lambda's inside the AWS Explorer my IDE freezes and I get and after a while I get an IDE error occurred message.

**To reproduce**

1.  Add AWS explorer window
2. Navigate to Lamba and unfold
3. Right click my Lambda function.
4. My IDE Freezes here. *Context-menu does pop up after a while.*
5. Click update function code
6. IDE Freezes again

**Expected behavior**

1. Right click lambda function for context-menu
2. context-menu pops up without freezing.
3. Click Update function code without freezing.
4. Click update.
5. I have now updated my lambdas function code.

**Screenshots**

**Your Environment**
- OS: Ubuntu 20.04 LTS
- JetBrains product:Rider
- JetBrains product version:2021.1.1
- AWS Toolkit version:1.26-211
- SAM CLI version:1.21.1
- JVM: 11.0.10+9-Ubuntu-0ubuntu1.20.04 (if i have the correct thing)
- Python version: 2.7.18

**Additional context**
It did work for me in the rider 2020 version.

Hope you have enough info

Thanks in advance!

**Exception**
update failed for AnAction(software.aws.toolkits.jetbrains.services.lambda.actions.GoToHandlerAction) with ID=lambda.function.gotohandler

java.util.concurrent.TimeoutException: Sync execution of rpc `RiderClientFromEBS.SolutionModel.solutions.[1].backendPsiHelperModel.findPublicMethod` is timed out in 3000 ms
	at com.jetbrains.rd.framework.impl.RdCall$sync$freezeTime$1.invoke(RdTask.kt:215)
	at com.jetbrains.rd.framework.impl.RdCall$sync$freezeTime$1.invoke(RdTask.kt:167)
	at com.jetbrains.rd.util.PlatformDependentKt.measureTimeMillis(PlatformDependent.kt:90)
	at com.jetbrains.rd.framework.impl.RdCall.sync(RdTask.kt:209)
	at software.aws.toolkits.jetbrains.services.lambda.dotnet.DotNetLambdaHandlerResolver.getFieldIdByHandlerName(DotNetLambdaHandlerResolver.kt:69)
	at software.aws.toolkits.jetbrains.services.lambda.dotnet.DotNetLambdaHandlerResolver.findPsiElements(DotNetLambdaHandlerResolver.kt:30)
	at software.aws.toolkits.jetbrains.services.lambda.Lambda.findPsiElementsForHandler(Lambda.kt:44)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaFunctionNode.handlerPsi(LambdaExplorerNodes.kt:49)
	at software.aws.toolkits.jetbrains.services.lambda.actions.GoToHandlerAction.getHandler(GoToHandlerAction.kt:39)
	at software.aws.toolkits.jetbrains.services.lambda.actions.GoToHandlerAction.update(GoToHandlerAction.kt:22)
	at software.aws.toolkits.jetbrains.core.explorer.actions.ExplorerNodeAction.update(AbstractActions.kt:86)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$1(ActionUtil.java:170)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:510)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$1(ActionUpdater.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:105)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:492)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:333)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:308)
	at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:307)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1511)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:307)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:199)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupWithTimeout$11(ActionUpdater.java:215)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.withTimeout(ProgressIndicatorUtils.java:310)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:207)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:105)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:117)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.lambda$show$1(ActionPopupMenuImpl.java:130)
	at com.intellij.util.TimeoutUtil.run(TimeoutUtil.java:104)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:129)
	at software.aws.toolkits.jetbrains.core.explorer.ExplorerToolWindow$createTree$2.invokePopup(ExplorerToolWindow.kt:228)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:36)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6649)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by koengroten** [comment]
Skipping back to rider 2020.3 worked for me.

**Comment by abrooksv** [comment]
Resharper backend error:
```
--- EXCEPTION #1/3 [NullReferenceException]
Message = “Object reference not set to an instance of an object.”
ExceptionPath = Root.InnerException.InnerException
ClassName = System.NullReferenceException
HResult = E_POINTER=COR_E_NULLREFERENCE=80004003
Source = JetBrains.ReSharper.Psi
StackTraceString = “
  at JetBrains.ReSharper.Psi.Modules.PsiModuleExtensions.GetPsiModules(IProject project)
     at JetBrains.ReSharper.Host.Features.Services.PsiHelperHost.FindMethod(Lifetime lifetime, Int32 projectId, String className, String methodName, String targetFrameworkPresentableName, Func`2 methodFilter)
     at JetBrains.ReSharper.Host.Features.Services.PsiHelperHost.FindPublicMethod(Lifetime lifetime, String className, String methodName, Int32 projectId)
     at JetBrains.ReSharper.Host.Features.Services.PsiHelperHost.<>c__DisplayClass4_1.<.ctor>b__5()
     at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
     at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__1(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
”

--- Outer ---
```

**Comment by koengroten** [comment]
Tested on 1.27-EAP.2021.05.25-211 in rider 2021.1.2 works as expected thanks!

**Comment by abrooksv** [comment]
> Tested on 1.27-EAP.2021.05.25-211 in rider 2021.1.2 works as expected thanks!

Thank you for confirming the fix
