### ISSUE TITLE
SAM Fails when creating a new project

### ISSUE THREAD

**Issue by jeremyforan** [aws/aws-toolkit-jetbrains#2583]
**Describe the bug**

I create a new AWS Serverless Application in Pycharm using the AWS Toolkit Plugin.

Package type: Image
Runtime: python3.8
SAM Template: AWS SAM Hello World
Environment: Pipenv

I hit 'create' and get an error that the SAM failed. 

**To reproduce**

1. Go to 'File'
2. Click on 'New Project'
3. Configure project:
    Package type: Image
    Runtime: python3.8
    SAM Template: AWS SAM Hello World
    Environment: Pipenv

4. Hit 'Create'

I get the following error
```
java.lang.RuntimeException: Could not execute `sam init`!: [Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates, Error: Multiple lambda image application templates found. This should not be possible, please raise an issue.]
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner$execute$1.apply(SamInitRunner.kt:55)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner$execute$1.apply(SamInitRunner.kt:22)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner.execute(SamInitRunner.kt:33)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder.runSamInit(SamProjectGeneratorIntelliJShims.kt:94)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.consume(SamProjectGeneratorIntelliJShims.kt:76)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.consume(SamProjectGeneratorIntelliJShims.kt:73)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$8(ModuleRootModificationUtil.java:128)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:136)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:127)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1.run(SamProjectGeneratorIntelliJShims.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 11.3 (20E232)
- JetBrains product: PyCharm 2021.1.1 (Professional Edition)
- JetBrains product version:  #PY-211.7142.13, built on April 21, 2021
- AWS Toolkit version: 1.26-211
- SAM CLI version: SAM CLI, version 1.23.0
- JVM/Python version: 3.8

**Additional context**

**Comment by abrooksv** [comment]
Related SAM CLI issue: https://github.com/aws/aws-sam-cli/issues/2846

**Comment by justinmk3** [comment]
Related: https://github.com/aws/aws-sam-cli-app-templates/issues/95

**Comment by wolfpaulus** [comment]
java.lang.RuntimeException: Could not execute `sam init`!: [Cloning from https://github.com/aws/aws-sam-cli-app-templates, Error: Multiple lambda image application templates found. Please specify one using the --app-template parameter.]

**Comment by abrooksv** [comment]
Looks like SAM CLI has released a fix but we need to re-write our logic to pass the new argument:

https://github.com/aws/aws-sam-cli/issues/2846#issuecomment-854154902
