### ISSUE TITLE
Property CodeUri not found in HelloWorldFunction after SAM init

### ISSUE THREAD

**Issue by autohandle** [aws/aws-toolkit-jetbrains#2605]
**Describe the bug**

**To reproduce**

o new project
- Package Type: Image
- Create
- Runtime: python3.7 (python3.8 has its own problems)

**Expected behavior**

expected a new project, got an error
examining template.html, it doesn't have a: CodeUri, and
PackageType:Image is underlined in red

**Screenshots**

**Your Environment**
- OS: macOS Big Sur, 11.3.1
- JetBrains product: pycharm 2021.1
- JetBrains product version: Build #PY-211.7142.13, built on April 21, 2021
- AWS Toolkit version: 1-26-211
- SAM CLI version: SAM CLI, version 1.23.0
- JVM/Python version:

**Additional context**

```
java.lang.IllegalStateException: Property CodeUri not found in HelloWorldFunction
	at software.aws.toolkits.jetbrains.services.cloudformation.SamFunction.getScalarProperty(Resources.kt:42)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion$getCodeUrisFromTemplate$$inlined$runReadAction$1$lambda$1.invoke(SamCommon.kt:57)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion$getCodeUrisFromTemplate$$inlined$runReadAction$1$lambda$1.invoke(SamCommon.kt:22)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:773)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion$getCodeUrisFromTemplate$$inlined$runReadAction$1.compute(actions.kt:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:834)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion.getCodeUrisFromTemplate(SamCommon.kt:71)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectTemplate.addSourceRoots(SamProjectWizard.kt:71)
	at software.aws.toolkits.jetbrains.services.lambda.python.PythonSamProjectTemplate.postCreationAction(PythonSamProjectWizard.kt:54)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder.runPostSamInit(SamProjectGeneratorIntelliJShims.kt:124)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.consume(SamProjectGeneratorIntelliJShims.kt:78)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.consume(SamProjectGeneratorIntelliJShims.kt:73)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$8(ModuleRootModificationUtil.java:128)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:136)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:127)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1.run(SamProjectGeneratorIntelliJShims.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by autohandle** [comment]
i soldered on & updated template.yml:

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      PackageType: Image
      CodeUri: hello_world

i had to add Handler & Runtime — it is still red underlining PackageType, it ran locally, but when i deployed, i got an error:

Waiting for changeset to be created..
Error: Failed to create changeset for the stack: PycharmLambdaSwerverlessImage, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [HelloWorldFunction] is invalid. Runtime, Handler, Layers cannot be present when PackageType is of type `Image`
Create Change Set has failed: Command did not exist successfully, exit code: 1
PycharmLambdaSwerverlessImage has failed: Command did not exist successfully, exit code: 1

i also ran it from the command line:

(base) MacBookPro2018:lambda david$ /usr/local/homebrew/bin/sam deploy --debug --template-file /Users/david/Documents/amazonws/lambda/ServerlessImageProject/.aws-sam/build/packaged-template.yaml --stack-name PycharmLambdaServerlessImage --s3-bucket pycharm-lambda-serverless-image --image-repository XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/lambda --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-execute-changeset --profile developer --region us-west-2
2021-05-18 11:30:18,700 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-18 11:30:18,701 | Using config file: samconfig.toml, config environment: default
2021-05-18 11:30:18,701 | Expand command line arguments to:
2021-05-18 11:30:18,701 | --template_file=/Users/david/Documents/amazonws/lambda/ServerlessImageProject/.aws-sam/build/packaged-template.yaml --stack_name=PycharmLambdaServerlessImage --s3_bucket=pycharm-lambda-serverless-image --image_repository=XXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/lambda --capabilities=('CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM') --no_execute_changeset --fail_on_empty_changeset
2021-05-18 11:30:19,105 | Property ImageUri of HelloWorldFunction is already an ECR URL

	Deploying with following values
	===============================
	Stack name                   : PycharmLambdaServerlessImage
	Region                       : us-west-2
	Confirm changeset            : False
	Deployment image repository  :
                                       XXXXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/lambda
	Deployment s3 bucket         : pycharm-lambda-serverless-image
	Capabilities                 : ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
2021-05-18 11:30:19,131 | No Parameters detected in the template
2021-05-18 11:30:19,171 | 2 stacks found in the template
2021-05-18 11:30:19,172 | No Parameters detected in the template
2021-05-18 11:30:19,195 | 2 resources found in the stack
2021-05-18 11:30:19,195 | No Parameters detected in the template
2021-05-18 11:30:19,215 | Found Serverless function with name='HelloWorldFunction' and ImageUri='XXXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/lambda:helloworldfunction-893ae41eaac9-python3.7-v1'
2021-05-18 11:30:19,216 | --base-dir is not presented, adjusting uri ./hello_world relative to /var/folders/41/y2p9txvd1tn65h_d42f2ffs80000gq/T/tmp4sm0zj9s
2021-05-18 11:30:19,216 | --base-dir is not presented, adjusting uri . relative to /var/folders/41/y2p9txvd1tn65h_d42f2ffs80000gq/T/tmp4sm0zj9s
2021-05-18 11:30:19,216 | No Parameters detected in the template
2021-05-18 11:30:19,235 | Detected Inline Swagger definition
2021-05-18 11:30:19,235 | Auth checks done on swagger are not exhaustive!
HelloWorldFunction may not have authorization defined.
2021-05-18 11:30:19,589 | File with same data is already exists at fadc7bd335e40276f9a95ab82389fc73.template. Skipping upload

Waiting for changeset to be created..
2021-05-18 11:30:24,963 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '673b6103-b979-4ff6-975f-3ee73d755b06', 'installationId': '0a8680ce-cb46-4e10-8d24-c9aa60b5aa69', 'sessionId': '799abb1f-e593-4fbd-a693-e9d5ee379d80', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.9', 'samcliVersion': '1.23.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': 'us-west-2', 'commandName': 'sam deploy', 'duration': 6262, 'exitReason': 'ChangeSetError', 'exitCode': 1}}]}
2021-05-18 11:30:25,126 | Telemetry response: 200
Error: Failed to create changeset for the stack: PycharmLambdaServerlessImage, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [HelloWorldFunction] is invalid. Runtime, Handler, Layers cannot be present when PackageType is of type `Image`

**Comment by abrooksv** [comment]
Image based template for Python should be: 

```
Resources:
  SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 900
    Metadata:
      DockerTag: v1
      DockerContext: hello_world
      Dockerfile: Dockerfile
```

DockerContext is relative path from the template to where the requirements.txt / Dockerfile file is

**Comment by abrooksv** [comment]
Using Handler+Runtime will be used with PackageType: Zip (or not provided which defaults to Zip)

**Comment by autohandle** [comment]
> Image based template for Python should be:
> 
> ```
> Resources:
>   SomeFunction:
>     Type: AWS::Serverless::Function
>     Properties:
>       PackageType: Image
>       Timeout: 900
>     Metadata:
>       DockerTag: v1
>       DockerContext: hello_world
>       Dockerfile: Dockerfile
> ```
> 
> DockerContext is relative path from the template to where the Dockerfile file is

thanks austin, but to be clear (no surprise, i'm a little unsure of myself), i didn't do the new pycharm awt toolkit project wrong — awt toolkit created an incorrect template & i should just overwrite the template by hand (like you suggested) & move on?

**Comment by abrooksv** [comment]
For me it generated:
```
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./hello_world
      Dockerfile: Dockerfile
```

which is a valid template and can be tested locally and deployed, but it does throw a toolkit error when setting up the IntelliJ source roots. We will need to fix that but it should not prevent you from using the template.

**Comment by autohandle** [comment]
> For me it generated:
> 
> ```
> Resources:
>   HelloWorldFunction:
>     Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
>     Properties:
>       PackageType: Image
>       Events:
>         HelloWorld:
>           Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
>           Properties:
>             Path: /hello
>             Method: get
>     Metadata:
>       DockerTag: python3.7-v1
>       DockerContext: ./hello_world
>       Dockerfile: Dockerfile
> ```
> 
> which is a valid template and can be tested locally and deployed, but it does throw a toolkit error when setting up the IntelliJ source roots. We will need to fix that but it should not prevent you from using the template.

tysm austin — that worked for me, both local & remote (ok, except for the init error that you warned me about).  should i close this & or let you do it?

**Comment by abrooksv** [comment]
I'll use this to track the bug fix, we'll close it when we patch it
