### ISSUE TITLE
Exception on startup: Accessing disposed message bus MessageBus...

### ISSUE THREAD

**Issue by evictor** [aws/aws-toolkit-jetbrains#2615]
**Describe the bug**

Observed the following exception in the IntelliJ Event Log tool window on IDE startup. It _may_ have something to do with canceling the loading of a project that uses AWS Toolkit, followed by loading another project that does not. (But that is conjecture and merely corresponds to behavior that preceded the exception.) There were no other noticeable effects. Parts of exception have been **REDACTED** for security/privacy reasons:

```
java.lang.Throwable: Accessing disposed message bus MessageBus(owner=Project(name=**REDACTED**, containerState=DISPOSE_IN_PROGRESS, componentStore=**REDACTED**) (disposed), disposeState= 1)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:371)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
	at com.sun.proxy.$Proxy82.settingsStateChanged(Unknown Source)
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager.setConnectionState$jetbrains_core(AwsConnectionManager.kt:45)
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager.changeFieldsAndNotify(AwsConnectionManager.kt:135)
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager.changeConnectionSettings(AwsConnectionManager.kt:95)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultAwsConnectionManager$loadState$3.invokeSuspend(DefaultAwsConnectionManager.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To reproduce**

This is conjecture—not confirmed reproducible—so may not actually be the cause of the exception:

1. Open a project that utilizes AWS Toolkit.
2. Close the entire IDE.
3. Open the IDE—it begins to load the project you previously had open from step 1.
4. Before the project has finished loading, press the "cancel" button on the progress bar to abort the process.
5. On the resulting IDE startup dialog, open some other project that does not make use of the AWS Toolkit.
6. After the project loads, this is when I observed the exception event in the Event Log.

**Expected behavior**

Strange exceptions aren't thrown. :)

**Screenshots**

N/A

**Your Environment**
- OS: OS X Big Sur 11.3.1 (20E241)
- JetBrains product: IntelliJ IDEA 2021.1.1 (Ultimate Edition)
- JetBrains product version: Build #IU-211.7142.45, built on April 30, 2021
- AWS Toolkit version: 1.26-211
- SAM CLI version: 1.23.0
- JVM version: Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
- Python version: 3.8.3

**Comment by abrooksv** [comment]
Thanks for the bug report, #2619 should take care of this.

Was not able to reproduce due to its a race condition
