### ISSUE TITLE
Uncaught error when starting without internet

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-toolkit-jetbrains#263]
```
Exception occurred downloading

java.io.IOException: Cannot download 'https://aws-toolkit-endpoints.s3.amazonaws.com/endpoints.json': aws-toolkit-endpoints.s3.amazonaws.com
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:420)
	at com.intellij.util.io.RequestBuilder.lambda$saveToFile$1(RequestBuilder.java:67)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at com.intellij.util.io.RequestBuilder.saveToFile(RequestBuilder.java:67)
	at software.aws.toolkits.jetbrains.core.DefaultRemoteResourceResolverProvider$Companion$HttpRequestUrlFetcher.fetch(RemoteResourceResolverProvider.kt:52)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver$internalResolve$downloaded$1.invoke(RemoteResourceResolver.kt:51)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver$internalResolve$downloaded$1.invoke(RemoteResourceResolver.kt:20)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:149)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:109)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:133)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:126)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver.internalResolve(RemoteResourceResolver.kt:59)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver.access$internalResolve(RemoteResourceResolver.kt:20)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver$resolve$1.call(RemoteResourceResolver.kt:27)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver$resolve$1.call(RemoteResourceResolver.kt:20)
	at software.aws.toolkits.jetbrains.core.DefaultRemoteResourceResolverProvider$Companion$RESOLVER_INSTANCE$2$1$1.run(RemoteResourceResolverProvider.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: aws-toolkit-endpoints.s3.amazonaws.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:558)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:329)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:338)
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:416)
	... 24 more
```

**Comment by abrooksv** [comment]
We should not log the error at LOG.error since that will trigger the uncaught error dialog, need to change it to warn.
