### ISSUE TITLE
"Required dataId 'aws.s3.bucketViewer` was missing" when issuing "Refresh" command

### ISSUE THREAD

**Issue by allanlewis** [aws/aws-toolkit-jetbrains#2690]
**Describe the bug**

I issued the "refresh" command (Cmd+R on Mac) and got this stack trace:

```
java.lang.IllegalStateException: Required dataId 'aws.s3.bucketViewer` was missing
	at software.aws.toolkits.jetbrains.core.utils.DataContextUtilsKt.getRequiredData(DataContextUtils.kt:12)
	at software.aws.toolkits.jetbrains.services.s3.objectActions.RefreshTreeAction.performAction(RefreshTreeAction.kt:18)
	at software.aws.toolkits.jetbrains.services.s3.objectActions.S3ObjectAction.actionPerformed(S3ObjectAction.kt:16)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:108)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To reproduce**

* Issue the "Refresh" command.

**Expected behavior**

I expected the IDE to refresh file state, etc.

**Screenshots**

n/a

**Your Environment**
- OS: Mac OS 11.4 (Big Sur)
- JetBrains product: PyCharm
- JetBrains product version: 

```
PyCharm 2021.1.2 (Professional Edition)
Build #PY-211.7442.45, built on June 1, 2021
Licensed to Open Utility / Allan Lewis
Subscription is active until July 11, 2021.
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins: net.seesharpsoft.intellij.plugins.csv (2.17.0), mobi.hsz.idea.gitignore (4.1.0), name.kropp.intellij.makefile (211.6693.108), org.toml.lang (0.2.149.3939-211), aws.toolkit (1.27-211), ru.meanmail.plugin.requirements (2021.4-211)
```

- AWS Toolkit version: 1.27-211
- SAM CLI version: not installed
- JVM/Python version: see above

**Additional context**

**Comment by abrooksv** [comment]
You wouldn't happen to recall what part of the UI you had selected at the time, would you?

**Comment by allanlewis** [comment]
> You wouldn't happen to recall what part of the UI you had selected at the time, would you?

I'm not sure, probably the editor or the directory tree.

**Comment by abrooksv** [comment]
I was able to reproduce it by giving focus to the explorer and pressing CMD+R

**Comment by abrooksv** [comment]
Thanks for the bug report, #2694 looks to be the correct fix

**Comment by allanlewis** [comment]
Thanks for the quick fix 👏
