### ISSUE TITLE
Delete s3 bucket fails

### ISSUE THREAD

**Issue by jrobens** [aws/aws-toolkit-jetbrains#2705]
**Describe the bug**
Delete s3 bucket fails. Class not found error message.

**To reproduce**

Delete an s3 bucket. The bucket is associated to a lambda

**Expected behavior**
Delete the bucket

**Screenshots**

java.lang.NoClassDefFoundError: com/intellij/testFramework/EdtTestUtil
	at software.aws.toolkits.jetbrains.services.s3.bucketActions.DeleteBucketAction.performDelete(DeleteBucketAction.kt:45)
	at software.aws.toolkits.jetbrains.services.s3.bucketActions.DeleteBucketAction.performDelete(DeleteBucketAction.kt:18)
	at software.aws.toolkits.jetbrains.core.explorer.actions.DeleteResourceAction$actionPerformed$1.run(DeleteResourceAction.kt:29)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.intellij.testFramework.EdtTestUtil PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit, id=aws.toolkit, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.1/plugins/aws-toolkit-jetbrains, version=1.27-211, package=null), packagePrefix=null, instanceId=242, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more

**Your Environment**
- OS: Big Sur 11.1
- JetBrains product: IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Licensed to Interlated Pty Ltd / John Robens
Subscription is active until September 7, 2021.
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2493M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: com.jetbrains.plugins.ini4idea (211.6693.44), com.intellij.plugins.watcher (211.6693.44), org.jetbrains.plugins.localization (211.6693.44), org.mule.tooling.intellij.raml (0.13), org.logtalk (1.0.15), com.perl5 (2021.1.2), Karma (211.7442.9), org.jetbrains.plugins.vue (211.7142.13), org.jetbrains.kotlin (211-1.5.20-release-284-IJ7442.40), com.intellij.lang.jsgraphql (2.9.1), com.jetbrains.php (211.7628.25), de.espend.idea.php.annotation (8.0.0), com.jetbrains.php.framework (211.6693.44), com.jetbrains.php.drupal (211.6693.65), com.jetbrains.twig (211.6693.44), fr.adrienbrault.idea.symfony2plugin (0.23.209), de.espend.idea.php.drupal (0.5.1), org.jetbrains.plugins.ruby (211.7628.1), Pythonid (211.7628.24), aws.toolkit (1.27-211)
Kotlin: 211-1.5.20-release-284-IJ7442.40 
- JetBrains product version:
- AWS Toolkit version: 1.27-211
- SAM CLI version: aws-cli/2.2.7 Python/3.9.5 Darwin/20.5.0 source/x86_64 prompt/off

- JVM/Python version:

**Additional context**

**Comment by abrooksv** [comment]
Thank you for the bug report, this got fixed by happenstance in https://github.com/aws/aws-toolkit-jetbrains/commit/45e9028e96a61b0eb05c5f624a13a4289cfa2133 and will be fixed in our next release
