### ISSUE TITLE
Unable to start new AWS Serverless Application when "Image" is selected as Package Type instead of "Zip" in Pycharm

### ISSUE THREAD

**Issue by SashiDareddy** [aws/aws-toolkit-jetbrains#2725]
**Describe the bug**

Unable to start new AWS Serverless Application project when "Image" is selected as Package Type instead of "Zip" in PyCharm.

**To reproduce**

In PyCharm - I go to File > New Project & select "AWS Serverless Application" from the left hand margin and select "Image" as Package Type (if I select "Zip" it works absolutely fine!), Python 3.8 as Runtime with Poetry as my Python environment manager.

**Expected behavior**

It should create a new project which will allow you to create a containerised AWS Lambda function. 

**Screenshots**

Error message in PyCharm - Pycharm says this should be reported to AWS:
java.lang.RuntimeException: Could not execute `sam init`!: [Error: , You must not provide both the --base-image and --app-template parameters., You can run 'sam init' without any options for an interactive initialization flow, or you can provide one of the following required parameter combinations:,     --name and --runtime and --app-template and --dependency-manager,     --name and --package-type and --base-image,     --location,                             ]
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner$execute$1.apply(SamInitRunner.kt:55)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner$execute$1.apply(SamInitRunner.kt:22)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner.execute(SamInitRunner.kt:33)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder.runSamInit(SamProjectGeneratorIntelliJShims.kt:94)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.consume(SamProjectGeneratorIntelliJShims.kt:76)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.consume(SamProjectGeneratorIntelliJShims.kt:73)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$8(ModuleRootModificationUtil.java:128)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:136)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:127)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1.run(SamProjectGeneratorIntelliJShims.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Your Environment**
- OS:  Windows 11 Pro Version 21H2 (OS Build 22000.71)
- JetBrains product: PyCharm
- JetBrains product version: 2021.1.3 (build: PY-211.7628.24)
- AWS Toolkit version: 1.28-211
- SAM CLI version: 1.21.1
- JVM/Python version: Python 3.8, Java version 1.8.0_291

**Additional context**

**Comment by abrooksv** [comment]
Hi @SashiDareddy 

Can you try upgrading SAM CLI?

**Comment by abrooksv** [comment]
Glad it worked, a backwards incompatible change got introduced in one of the SAM CLI versions. Sorry for the inconvenience.
