### ISSUE TITLE
Access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by zbyszekpy** [aws/aws-toolkit-jetbrains#2756]
**Describe the bug**
"Access is allowed from event dispatch thread only" during Local HelloWorld function execution

**To reproduce**
1. Create HelloWorld example
2. Create Local AWS Lambda configuration
3. Press Run or Debug

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: Win 10
- JetBrains product: Rider
- JetBrains product version: 2021.2 212.4746.113
- AWS Toolkit version: 1.30-212
- SAM CLI version: 1.27.2
- JVM/Python version:

**Additional context**
Access is allowed from event dispatch thread only

com.intellij.execution.ExecutionException: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@4b93c738
Current thread: Thread[ApplicationImpl pooled thread 24,4,main] 1758993417
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 181788440
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfiguration.getState(LocalLambdaRunConfiguration.kt:216)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfiguration.getState(LocalLambdaRunConfiguration.kt:66)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:223)
	at software.aws.toolkits.jetbrains.services.lambda.execution.sam.SamRunningState.execute(SamRunningState.kt:82)
	at software.aws.toolkits.jetbrains.services.lambda.execution.sam.SamInvokeRunner$execute$1.call(SamInvokeRunner.kt:76)
	at software.aws.toolkits.jetbrains.services.lambda.execution.sam.SamInvokeRunner$execute$1.call(SamInvokeRunner.kt:31)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:194)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@4b93c738
Current thread: Thread[ApplicationImpl pooled thread 24,4,main] 1758993417
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 181788440
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1030)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1005)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocuments(FileDocumentManagerImpl.java:268)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:259)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:252)
	at software.aws.toolkits.jetbrains.services.lambda.execution.LambdaRunConfigurationBase.resolveInput(LambdaRunConfigurationBase.kt:69)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfiguration.getState(LocalLambdaRunConfiguration.kt:183)
	... 30 more

**Comment by abrooksv** [comment]
Consolidating this under #2762,

if you are NOT using a file as your input, please reopen
