### ISSUE TITLE
Debug is broken on Lambda functions [IDE Fatal Errors]

### ISSUE THREAD

**Issue by macroramesh6** [aws/aws-toolkit-jetbrains#2760]
**Describe the bug**
It was working from the beginning. Recently, I configure the lambda function debug with template.yml file. When I clieck on the debug button It throws IDE Fatal Errors

**To reproduce**

1. Click on the Modify run Configuration from the template.yml file
![image](https://user-images.githubusercontent.com/1827233/128686192-92909c71-d182-4280-9996-47260018f2cd.png)
2. Make sure the AWS credentials and ENV, Inputs etc.,
3. Click debugger button on top-right corner
4. See the error

**Expected behavior**
I should be able to debug the source

**Screenshots**
![image](https://user-images.githubusercontent.com/1827233/128686562-e02beb07-337b-4ea4-8971-02479e0c9efc.png)

**Your Environment**
- OS: macOS Big Sur
- JetBrains product:WebStrom
- JetBrains product version: WbStrom 2021.2 Build WS-212.4746.80
- AWS Toolkit version: 1.30-212
- SAM CLI version: SAM CLI, version 1.24.1
- JVM/Python version: 
JAVA:
Java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

Python
Python 2.7.16

**Additional context**
```
Access is allowed from event dispatch thread only

com.intellij.execution.ExecutionException: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@74dbecc
Current thread: Thread[ApplicationImpl pooled thread 11,4,main] 1178291093
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1552324493
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfiguration.getState(LocalLambdaRunConfiguration.kt:216)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfiguration.getState(LocalLambdaRunConfiguration.kt:66)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:223)
	at software.aws.toolkits.jetbrains.services.lambda.execution.sam.SamRunningState.execute(SamRunningState.kt:82)
	at software.aws.toolkits.jetbrains.services.lambda.execution.sam.SamInvokeRunner$execute$1.call(SamInvokeRunner.kt:76)
	at software.aws.toolkits.jetbrains.services.lambda.execution.sam.SamInvokeRunner$execute$1.call(SamInvokeRunner.kt:31)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@74dbecc
Current thread: Thread[ApplicationImpl pooled thread 11,4,main] 1178291093
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1552324493
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1030)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1005)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocuments(FileDocumentManagerImpl.java:268)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:259)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:252)
	at software.aws.toolkits.jetbrains.services.lambda.execution.LambdaRunConfigurationBase.resolveInput(LambdaRunConfigurationBase.kt:69)
	at software.aws.toolkits.jetbrains.services.lambda.execution.local.LocalLambdaRunConfiguration.getState(LocalLambdaRunConfiguration.kt:197)
	... 29 more

```

**Comment by abrooksv** [comment]
Consolidating these under #2762,

if you are NOT using a file as your input, please reopen
