### ISSUE TITLE
Index out of bounds when using the tail/follow button

### ISSUE THREAD

**Issue by vbujanca** [aws/aws-toolkit-jetbrains#2761]
The follow mode triggers the stacktrace below (no filters enabled, default sort etc).

**To reproduce**
open up a log stream, without any other action (eg sorting/filtering) enable the log follow mode from the third button on the left side of the window.

The ide logs an unknown error and the following stacktrace excerpt.

```
java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.checkAgainstModel(DefaultRowSorter.java:932)
	at java.desktop/javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:872)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4275)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4123)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
	at com.intellij.ui.table.TableView.tableChanged(TableView.java:98)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:232)
	at com.intellij.util.ui.ListTableModel.addRows(ListTableModel.java:192)
```

using the refresh button or sorting etc trigger some other stacktraces, not posted here since without using the follow mode (after starting the ide fresh, no errors occur.

**Your Environment**
- OS: Ubuntu 20.04.2, kernel 5.11.0, gnome
- JetBrains product: intelij idea 2021.2
- JetBrains product version: Build #IU-212.4746.92
- AWS Toolkit version: aws.toolkit (1.30-212)
- JVM/Python version: 11.0.11/3.8.10

please let me know if you need any other info/screenshot.

**Comment by abrooksv** [comment]
Looks like I fixed it by accident in #2753, but should update the code to make sure it doesnt regress on accident
