### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by sairoko12** [aws/aws-toolkit-jetbrains#2789]
**Describe the bug**

I had been setting my aws credentials when the IDE launch me an exception that says the following:

```
Unhandled exception in [CoroutineName(software.aws.toolkits.jetbrains.ui.feedback.FeedbackDialog), StandaloneCoroutine{Cancelling}@75225936, com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor@6e1d2b0a[Running, pool size = 4, active threads = 1, queued tasks = 0, completed tasks = 3512]]

java.lang.NoClassDefFoundError: Could not initialize class software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:877)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:48)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:36)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:590)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:19)
	at software.aws.toolkits.jetbrains.services.telemetry.TelemetryService$Companion.getInstance(TelemetryService.kt:111)
	at software.aws.toolkits.telemetry.FeedbackTelemetry.result(TelemetryDefinitions.kt:6447)
	at software.aws.toolkits.telemetry.FeedbackTelemetry.result$default(TelemetryDefinitions.kt:6445)
	at software.aws.toolkits.jetbrains.ui.feedback.FeedbackDialog$doOKAction$1.invokeSuspend(FeedbackDialog.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**To reproduce**
1. Open the AWS Explorer
2. Click on Edit AWS Credentials file
3. The IDE throws the pop up error

**Expected behavior**

I don't know what is the expected behavior because I can't complete the setting up of my credentials 

**Screenshots**
<img width="827" alt="Captura de Pantalla 2021-09-03 a la(s) 2 01 54 a m" src="https://user-images.githubusercontent.com/5692745/131964235-df723301-80c7-4719-b0f8-91fcf35bc62e.png">

**Your Environment**
- OS: macOS BigSur 11.5.2
- JetBrains product: PyCharm
- JetBrains product version: 2021.2.1
- AWS Toolkit version: 1.31-212
- SAM CLI version: 1.30.0
- JVM/Python version: Python 3.7.11

**Additional context**

**Comment by abrooksv** [comment]
There should be another exception in the idea.log (Find it in the Help menu), that explains why the class could not be initialized.

Can you please check to see if you see one?

**Comment by breedloj** [comment]
Closing due to inactivity - please update if you are still experiencing issues.
