### ISSUE TITLE
Unable to debug lambda locally in IntelliJ Ultimate

### ISSUE THREAD

**Issue by bensullivan** [aws/aws-toolkit-jetbrains#2801]
**Your Environment**

- OS: macos 11.5.2
- JetBrains product: IntelliJ Ultimate
- JetBrains product version:2021.2.1
- AWS Toolkit version:1.32-212
- SAM CLI version:1.31.0
- JVM/Python version: JDK Zulu 11.0.11

**Question**

When running my lambda handler locally to debug, I receive the following error

```
Invoking com.rugbycology.adapter.lambda.handler.CreatePossessionHandler (java11)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-java11
Building image...Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 83, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 175, in do_cli
    context.local_lambda_runner.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 130, in invoke
    self.local_runtime.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 217, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 176, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 87, in __init__
    image = LambdaContainer._get_image(lambda_image, runtime, packagetype, imageuri, layers)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 213, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 152, in build
    self._build_image(image if image else image_name, image_tag, downloaded_layers, stream=stream_writer)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 239, in _build_image
    resp_stream = self.docker_client.api.build(
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/docker/api/build.py", line 261, in build
    self._set_auth_headers(headers)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/docker/api/build.py", line 308, in _set_auth_headers
    auth_data = self._auth_configs.get_all_credentials()
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/docker/auth.py", line 310, in get_all_credentials
    auth_data[reg] = self._resolve_authconfig_credstore(
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
    store = self._get_store_instance(credstore_name)
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/docker/auth.py", line 286, in _get_store_instance
    self._stores[name] = credentials.Store(
  File "/usr/local/Cellar/aws-sam-cli/1.31.0/libexec/lib/python3.8/site-packages/docker/credentials/store.py", line 23, in __init__
    raise errors.InitializationError(
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
```

There was nothing install instructions about docker-credential-gcloud.

Please could you advise on appropriate course of action?

Thanks

Ben

**Comment by abrooksv** [comment]
We would not need anything related to GCloud 😄 

It sounds like you might have a misconfigured credential provider configured inside of `~/.docker/config.json`

https://docs.docker.com/engine/reference/commandline/login/#credentials-store

**Comment by bensullivan** [comment]
haha yes I was wondering that myself.  Yes I removed gcr entries from credHelpers and I'm away.  Thanks for your help.

**Comment by abrooksv** [comment]
Glad you found it
