### ISSUE TITLE
IDE Fatal Error when chekcing region

### ISSUE THREAD

**Issue by gonczor** [aws/aws-toolkit-jetbrains#2824]
**Describe the bug**
Error report received when clicking on the AWS extension in the sidebar. I got suggestion to send bug report.

```
java.lang.Throwable: ActionPlaces.isPopupPlace(StatusBarPlace)==false. Use ActionPlaces.getPopupPlace.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.ui.popup.ActionPopupStep.createActionItems(ActionPopupStep.java:118)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:274)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:215)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:182)
	at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:349)
	at com.jetbrains.rdserver.ui.popup.bePopups.impl.BackendBePopupFactory.createActionGroupPopup(BackendBePopupFactory.kt:84)
	at com.intellij.openapi.ui.popup.JBPopupFactory.createActionGroupPopup(JBPopupFactory.java:296)
	at com.jetbrains.rdserver.ui.popup.bePopups.impl.BackendBePopupFactory.createActionGroupPopup(BackendBePopupFactory.kt:218)
	at software.aws.toolkits.jetbrains.core.credentials.SettingsSelector.settingsPopup(AwsSettingsPanel.kt:96)
	at software.aws.toolkits.jetbrains.core.credentials.SettingsSelector.settingsPopup(AwsSettingsPanel.kt:93)
	at software.aws.toolkits.jetbrains.core.credentials.SettingsSelector.settingsPopup$default(AwsSettingsPanel.kt:92)
	at software.aws.toolkits.jetbrains.core.credentials.AwsSettingsPanel.getPopupStep(AwsSettingsPanel.kt:62)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetWrapper$MultipleTextValues$1.onClick(StatusBarWidgetWrapper.java:70)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To reproduce**
Click "AWS: default@[region]" on sidebar.

**Expected behavior**
No error showing up.

**Your Environment**
- OS: macOS
- JetBrains product: PyCharm
- JetBrains product version:
```
PyCharm 2021.2 (Professional Edition)
Build #PY-212.4746.96, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: com.intellij.ideolog (203.0.27.0), org.toml.lang (0.2.151.3997-212), com.jetbrains.intellij.datalore (0.1.13-212), ru.adelf.idea.dotenv (2021.3.0.212), aws.toolkit (1.29-212)
```
- AWS Toolkit version: `aws-cli/2.2.33 Python/3.9.6 Darwin/20.6.0 source/x86_64 prompt/off`
- SAM CLI version: `SAM CLI, version 1.29.0`
- JVM/Python version: As above

**Comment by abrooksv** [comment]
Your plugin version is out of date. Please upgrade it to v1.32

**Comment by gonczor** [comment]
@abrooksv Indeed. I didn't notice that it wasn't in the newest version. Sorry for the trouble :-D
