### ISSUE TITLE
AWS local Run configuration does not work on Apple M1

### ISSUE THREAD

**Issue by remidebette** [aws/aws-toolkit-jetbrains#3003]
**Describe the bug**
When trying to run the sample project `Scikit-learn Machine Learning Inference API` on MacOs M1, the configuration fails.

**To reproduce**
To set up the project:
```bash
$ sam init
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1
What package type would you like to use?
	1 - Zip (artifact is a zip uploaded to S3)
	2 - Image (artifact is an image uploaded to an ECR image repository)
Package type: 2

Which base image would you like to use?
	1 - amazon/nodejs14.x-base
	2 - amazon/nodejs12.x-base
	3 - amazon/nodejs10.x-base
	4 - amazon/python3.9-base
	5 - amazon/python3.8-base
	6 - amazon/python3.7-base
	7 - amazon/python3.6-base
	8 - amazon/python2.7-base
	9 - amazon/ruby2.7-base
	10 - amazon/ruby2.5-base
	11 - amazon/go1.x-base
	12 - amazon/java11-base
	13 - amazon/java8.al2-base
	14 - amazon/java8-base
	15 - amazon/dotnet5.0-base
	16 - amazon/dotnetcore3.1-base
	17 - amazon/dotnetcore2.1-base
Base image: 5

Project name [sam-app]:

Cloning from https://github.com/aws/aws-sam-cli-app-templates

AWS quick start application templates:
	1 - Hello World Lambda Image Example
	2 - PyTorch Machine Learning Inference API
	3 - Scikit-learn Machine Learning Inference API
	4 - Tensorflow Machine Learning Inference API
	5 - XGBoost Machine Learning Inference API
Template selection: 3
```

As expected, the CLIs works without a problem:

```bash
sam build
sam local invoke InferenceFunction --event events/event.json
sam local start-api
```

But when creating a [Local] run configuration, from a local handler or from a template, with or without Build function inside a container, the run always fails with `Validation of sam failed {1}`

Changing the Architecture does not affect the result of the cli or of the run configuration:
```yaml
      Architectures:
        - arm64
```

**Expected behavior**
I expect to be able to run / debug the project in Pycharm

**Screenshots**

**Your Environment**
- OS: MacOs Monterey 12.0.1 M1
- JetBrains product: Pycharm Community
- JetBrains product version: 2021.3
- AWS Toolkit version: 1.36-213
- SAM CLI version: 1.36.0
- JVM/Python version: conda miniforge, python 3.8

**Additional context**
Here are the pycharm logs when the problem happens:

```
2021-12-10 09:41:50,486 [  44979]   INFO - tion.HandlerCompletionProvider - Lambda handler completion provider is not registered for runtime: PYTHON. Completion is not supported. 
2021-12-10 09:41:55,462 [  49955]   INFO - ins.utils.execution.steps.Step - Step SAM Build failed 
java.lang.RuntimeException: Validation of sam failed.
{1}
	at software.aws.toolkits.jetbrains.services.lambda.steps.SamCliStep.getCli(SamCliStep.kt:23)
	at software.aws.toolkits.jetbrains.services.lambda.steps.BuildLambda.constructCommandLine(BuildLambda.kt:28)
	at software.aws.toolkits.jetbrains.utils.execution.steps.CliBasedStep.execute(CliBasedStep.kt:42)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run(Step.kt:24)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run$default(Step.kt:14)
	at software.aws.toolkits.jetbrains.utils.execution.steps.StepWorkflow.execute(StepWorkflow.kt:17)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run(Step.kt:24)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run$default(Step.kt:14)
	at software.aws.toolkits.jetbrains.utils.execution.steps.StepExecutor.execute(StepExecutor.kt:59)
	at software.aws.toolkits.jetbrains.utils.execution.steps.StepExecutor.startWorkflow$lambda-1(StepExecutor.kt:52)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-10 09:41:55,463 [  49956]   INFO - ins.utils.execution.steps.Step - Step StepWorkflow failed 
java.lang.RuntimeException: Validation of sam failed.
{1}
	at software.aws.toolkits.jetbrains.services.lambda.steps.SamCliStep.getCli(SamCliStep.kt:23)
	at software.aws.toolkits.jetbrains.services.lambda.steps.BuildLambda.constructCommandLine(BuildLambda.kt:28)
	at software.aws.toolkits.jetbrains.utils.execution.steps.CliBasedStep.execute(CliBasedStep.kt:42)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run(Step.kt:24)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run$default(Step.kt:14)
	at software.aws.toolkits.jetbrains.utils.execution.steps.StepWorkflow.execute(StepWorkflow.kt:17)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run(Step.kt:24)
	at software.aws.toolkits.jetbrains.utils.execution.steps.Step.run$default(Step.kt:14)
	at software.aws.toolkits.jetbrains.utils.execution.steps.StepExecutor.execute(StepExecutor.kt:59)
	at software.aws.toolkits.jetbrains.utils.execution.steps.StepExecutor.startWorkflow$lambda-1(StepExecutor.kt:52)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by remidebette** [comment]
Hi, 

As a side note, the same works on Windows but gives the same error on Ubuntu LTS.

Is there a plan to fix it? 
In a team of users with various OSes we would need the debbuging tooling to work before being confident to adopt the Lambda Docker solution.

Thank you

**Comment by tygary** [comment]
+1 This is also impacting our organization and our ability to use AWS toolkit.  We have a breadth of environments, and having all M1 macs suddenly not being able to debug lambdas is a serious blocker for us.  Are there any known workarounds?

**Comment by rli** [comment]
Can you either of you confirm that the SAM CLI path in the settings/preferences panel matches what is executed in the terminal?
![image](https://user-images.githubusercontent.com/742829/147981254-ba766938-1d58-45d4-b712-afbf0e92ffae.png)

**Comment by remidebette** [comment]
Hi @rli 
By default the SAM CLI executable was empty in my properties.
Since I installed through brew, I just put `/opt/homebrew/bin/sam`

Now everything works, and I am able to build, run and debug in pycharm as expected. Thank you.

So if I understand properly, right now the empty parameter does not default properly to the CLI default sam and also the error message should say that the CLI sam path should be explicitely put in this parameter?

**Comment by remidebette** [comment]
I see, the code you linked makes sense with what I observed.

Just to be 100% clear, sam is in my path in the same way as other binaries used other extensions successfully (docker, pytest, terraform, etc)
So the `arrayOf("sam")` in the code you shared then does not seem to work as one could expect.

**Comment by Rattapon-Insa** [comment]
> Hi @rli By default the _SAM CLI executable_ parameter was empty in my properties, and I could not see the Auto-detected piece inside. Since I installed through brew for M1 Mac, I just put `/opt/homebrew/bin/sam`
> 
> Now everything works, and I am able to build, run and debug in pycharm as expected. Thank you.
> 
> So if I understand properly, in our case the empty parameter does not auto-detect properly to the CLI default sam and also the error message should say that the CLI sam path should be explicitely put in this _SAM CLI executable_ parameter?
> 
> I understand your PR will fix the error message. It would be good to fix the auto-detection for MacOs and linux in my opinion.




This solution work for me. Tested on Mac M1

**Comment by macsakini** [comment]
On mac m1 it does not work by default and requires you to manipulate the setting in the preferences dialog on IntelliJ.
Requires you to run _brew --prefix aws-sam-cli_ copy the resulting path and copy it manually to the section below.
_Preferences>Tools>AWS>SAM_ CLI executable_

**Comment by shubha26** [comment]
> 

I also installed via brew on my Macbook M1.

shubham@Shubhams-MacBook-Air ~ % whereis sam
**sam: /opt/homebrew/bin/sam**
shubham@Shubhams-MacBook-Air ~ % which sam
**/opt/homebrew/bin/sam**

When I enter this sam-cli path on the Intellij >Preferences>Tools>AWS>SAM CLI executable,
I get the error: 
**Cannot Save Settings
Invalid sam executable : java.util.concurrent.TimeoutException**
