### ISSUE TITLE
FileNotFoundError during local Lambda test build

### ISSUE THREAD

**Issue by farkas-istvan** [aws/aws-toolkit-jetbrains#3160]
**Your Environment**

- OS: Windows 10 Home [build: 19043.1706]
- JetBrains product: IntelliJ IDEA Community Edition 2022.1
- JetBrains product version:  2022.1.0.IC-221.5080.210
- AWS Toolkit version: 1.43-221
- SAM CLI version: 1.50.0
- JVM/Python version: Java Corretto-11.0.15.9.1 (build 11.0.15+9-LTS)

Why am I getting FileNotFoundError during SAM build, when I want to test locally my lambda function?

My stack trace:
`docker ps
"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" build MakeGreeting --template C:\Projects\hardfew-aws-lambda-java-skeleton-service\template.yaml --build-dir C:\Projects\hardfew-aws-lambda-java-skeleton-service\.aws-sam\build
Building codeuri: C:\Projects\hardfew-aws-lambda-java-skeleton-service runtime: java11 metadata: {} architecture: x86_64 functions: ['MakeGreeting']
Test the latest build changes for Java runtime 'SAM_CLI_BETA_MAVEN_SCOPE_AND_LAYER=1 sam build'. These changes will replace the existing flow on 1st of April 2022. Check https://github.com/aws/aws-sam-cli/issues/3639 for more information.
Running JavaGradleWorkflow:GradleBuild
Running JavaGradleWorkflow:JavaGradleCopyArtifacts
Skipping copy operation since source C:\Users\user1\AppData\Local\Temp\tmponprb02p\0df6c3ab8644c08b4b3fe15615f6ac135f6e3165\build\distributions\lambda-build does not exist
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 174, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 251, in do_cli
    ctx.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 191, in run
    build_result = builder.build()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 219, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 75, in build
    result.update(self._build_functions(self._build_graph))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 85, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 156, in build_single_function_definition
    result = self._build_function(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 654, in _build_function
    return self._build_function_in_process(
  File "contextlib.py", line 120, in __exit__
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 54, in mkdir_temp
    shutil.rmtree(temp_dir)
  File "shutil.py", line 740, in rmtree
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  [Previous line repeated 5 more times]
  File "shutil.py", line 618, in _rmtree_unsafe
  File "shutil.py", line 616, in _rmtree_unsafe
FileNotFoundError: [WinError 3] A rendszer nem találja a megadott elérési utat: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmponprb02p\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\upscale\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'
SAM Build has failed: Command did not exit successfully, exit code: 1
42 has failed: Command did not exit successfully, exit code: 1
`
The class file which can not be found, actually exists. The reason why it can not find is maybe the double slashback? If it is, then I don't understand what occurred it. What other information should I provide about the problem?

Thank you!

**Comment by rli** [comment]
Closing in favor of SAM CLI ticket https://github.com/aws/aws-sam-cli/issues/3885
