### ISSUE TITLE
AWS toolkit can fall into deadlock and hang the IDE

### ISSUE THREAD

**Issue by pporvatov** [aws/aws-toolkit-jetbrains#3191]
Below are two threads that fall into deadlock. Note that usually accessing to swing components is prohibited and can lead to unexpected results, use the EDT thread instead

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on javax.swing.UIDefaults@7879d8e8
	at java.base@17.0.3/java.lang.Object.wait(Native Method)
	at java.base@17.0.3/java.lang.Object.wait(Object.java:338)
	at java.desktop/javax.swing.UIDefaults.getFromHashtable(UIDefaults.java:201)
	at java.desktop/javax.swing.UIDefaults.get(UIDefaults.java:171)
	at java.desktop/javax.swing.JTable.getDefaultRenderer(JTable.java:1401)
	at java.desktop/javax.swing.JTable.getDefaultRenderer(JTable.java:1410)
	at java.desktop/javax.swing.JTable.getCellRenderer(JTable.java:5747)
	at com.intellij.ui.table.TableView.getCellRenderer(TableView.java:86)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2209)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2112)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1908)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.table.JBTable.paintComponent(JBTable.java:417)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1122)
	at com.intellij.ui.table.JBTable.paint(JBTable.java:547)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:235)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1668)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1580)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5267)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5077)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base@17.0.3/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.3/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.3/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base@17.0.3/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.3/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.3/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.ide.IdeEventQueue$$Lambda$801/0x00000003007df508.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.ide.IdeEventQueue$$Lambda$800/0x00000003007db548.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.ide.IdeEventQueue$$Lambda$798/0x00000003007d98e8.run(Unknown Source)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:479)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)



"ApplicationImpl pooled thread 305" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on java.awt.Component$AWTTreeLock@3bc3c2ea owned by "AWT-EventQueue-0" Id=31
	at java.desktop/java.awt.Component.setFont(Component.java:1965)
	at java.desktop/java.awt.Container.setFont(Container.java:1780)
	at java.desktop/javax.swing.JComponent.setFont(JComponent.java:2817)
	at java.desktop/javax.swing.LookAndFeel.installColorsAndFont(LookAndFeel.java:213)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.installDefaults(BasicLabelUI.java:368)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.installUI(BasicLabelUI.java:348)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:733)
	at java.desktop/javax.swing.JLabel.setUI(JLabel.java:274)
	at java.desktop/javax.swing.JLabel.updateUI(JLabel.java:288)
	at java.desktop/javax.swing.table.DefaultTableCellRenderer.updateUI(DefaultTableCellRenderer.java:165)
	at java.desktop/javax.swing.JLabel.<init>(JLabel.java:180)
	at java.desktop/javax.swing.JLabel.<init>(JLabel.java:251)
	at java.desktop/javax.swing.table.DefaultTableCellRenderer.<init>(DefaultTableCellRenderer.java:114)
	at java.desktop/javax.swing.table.DefaultTableCellRenderer$UIResource.<init>(DefaultTableCellRenderer.java:407)
	at java.desktop/javax.swing.JTable.lambda$createDefaultRenderers$0(JTable.java:5383)
	at java.desktop/javax.swing.JTable$$Lambda$7674/0x0000000302869ee8.createValue(Unknown Source)
	at java.desktop/javax.swing.UIDefaults.getFromHashtable(UIDefaults.java:226)
	at java.desktop/javax.swing.UIDefaults.get(UIDefaults.java:171)
	at java.desktop/javax.swing.JTable.getDefaultRenderer(JTable.java:1401)
	at java.desktop/javax.swing.JTable.getDefaultRenderer(JTable.java:1410)
	at java.desktop/javax.swing.JTable.getCellRenderer(JTable.java:5747)
	at com.intellij.ui.table.TableView.getCellRenderer(TableView.java:86)
	at com.intellij.ui.table.JBTable.calculateRowHeight(JBTable.java:257)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:238)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4485)
	at com.intellij.ui.table.TableView.tableChanged(TableView.java:96)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:204)
	at com.intellij.util.ui.ListTableModel.setItems(ListTableModel.java:87)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.insights.DetailedLogRecord$1.invokeSuspend(DetailedLogRecord.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base@17.0.3/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base@17.0.3/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.3/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.3/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)
```

**Comment by rli** [comment]
Released in 1.50
