### ISSUE TITLE
AWS Toolkit Does not create complete application structure in IntelliJ IDEA

### ISSUE THREAD

**Issue by gmarshall56** [aws/aws-toolkit-jetbrains#3214]
**Describe the bug**
  AWS toolkit was throwing exceptions when creating a new AWS SAM project
**To reproduce**
Create a new project in Intellij IDEA 2022.1.3 Build #IU-221.5921.22, built on June 21, 2022 using the AWS Servless Application Wizard.  Enter the parameters required for a new project (for me a new lambda project developed with Java):

![AWSToolkitBroken](https://user-images.githubusercontent.com/5943189/178816204-0af136a7-febb-4abc-b8b7-b3f05b123cad.JPG)

The first few times I tried this the toolkit threw this exception:

java.lang.RuntimeException: Could not execute `sam init`!: [Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment), Error: Unstable state when updating repo. Check that you have permissions to create/delete files in C:\Users\xxxxx\AppData\Roaming\AWS SAM directory or file an issue at https://github.com/aws/aws-sam-cli/issues]
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner.execute$lambda-1(SamInitRunner.kt:55)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner.execute(SamInitRunner.kt:33)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder.runSamInit(SamProjectGeneratorIntelliJShims.kt:94)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1.run$lambda-0(SamProjectGeneratorIntelliJShims.kt:76)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$9(ModuleRootModificationUtil.java:147)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:155)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:146)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1.run(SamProjectGeneratorIntelliJShims.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

...now I longer get that exception however the project is not built out correctly in the IDE.  The project only contains an .idea folder. 

**Expected behavior**
Expecting a complete project directory assembled and ready for development work, for example as is shown in _cloud4java's_  [Youtube video](https://www.youtube.com/watch?v=HrluYsEs3DUl)

**Your Environment**
- Windows 10
- Intellij IDEA 2022.1.3 Build #IU-221.5921.22, built on June 21, 2022 
- AWS Toolkit version: 1.46-221
- SAM CLI version: 1.53.0
- JVM/Python version: java version "11.0.4" 2019-07-16 LTS  ALSO happens when using java 8

**Additional context**
It appears this AWS Toolkit version is not ready for public consumption.

**Comment by rli** [comment]
Closing in favor of SAM CLI tracking issue for long paths on Windows: https://github.com/aws/aws-sam-cli/issues/4031

Glad you were able to figure it out.
