### ISSUE TITLE
Unable to open interactive shell on ECS fargate type container

### ISSUE THREAD

**Issue by kid1412621** [aws/aws-toolkit-jetbrains#3228]
**Describe the bug**
```log
kotlin.reflect.full.IllegalCallableAccessException: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class software.aws.toolkits.jetbrains.services.ecs.exec.OpenShellInContainerDialog with modifiers "private"
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:224)
	at kotlin.reflect.jvm.internal.KProperty0Impl.get(KProperty0Impl.kt:35)
	at kotlin.reflect.jvm.internal.KProperty0Impl$Getter.invoke(KProperty0Impl.kt:44)
	at com.intellij.ui.layout.CellKt$toNullable$1.invoke(Cell.kt:90)
	at com.intellij.ui.layout.Cell$comboBox$1.invoke(Cell.kt:354)
	at com.intellij.ui.layout.Cell$comboBox$1.invoke(Cell.kt:224)
	at com.intellij.ui.layout.CellKt.applyToComponent(Cell.kt:197)
	at com.intellij.ui.layout.Cell.comboBox(Cell.kt:352)
	at software.aws.toolkits.jetbrains.services.ecs.exec.OpenShellInContainerDialog$createCenterPanel$1$2.invoke(OpenShellInContainerDialog.kt:114)
	at software.aws.toolkits.jetbrains.services.ecs.exec.OpenShellInContainerDialog$createCenterPanel$1$2.invoke(OpenShellInContainerDialog.kt:63)
	at com.intellij.ui.layout.RowBuilder$DefaultImpls.row(Row.kt:55)
	at com.intellij.ui.layout.Row.row(Row.kt:145)
	at com.intellij.ui.layout.migLayout.MigLayoutRow.row(MigLayoutRow.kt:548)
	at com.intellij.ui.layout.RowBuilder$DefaultImpls.row(Row.kt:59)
	at com.intellij.ui.layout.Row.row(Row.kt:145)
	at com.intellij.ui.layout.LayoutBuilder.row(LayoutBuilder.kt)
	at com.intellij.ui.layout.RowBuilder$DefaultImpls.row$default(Row.kt:58)
	at software.aws.toolkits.jetbrains.services.ecs.exec.OpenShellInContainerDialog.createCenterPanel(OpenShellInContainerDialog.kt:63)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1308)
	at software.aws.toolkits.jetbrains.services.ecs.exec.OpenShellInContainerDialog.<init>(OpenShellInContainerDialog.kt:48)
	at software.aws.toolkits.jetbrains.services.ecs.ExecuteCommandInShellAction$actionPerformed$1$1$1.invoke(ContainerActions.kt:170)
	at software.aws.toolkits.jetbrains.services.ecs.ExecuteCommandInShellAction$actionPerformed$1$1$1.invoke(ContainerActions.kt:169)
	at software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManagerKt.withAwsConnection(AwsConnectionManager.kt:286)
	at software.aws.toolkits.jetbrains.services.ecs.ExecuteCommandInShellAction$actionPerformed$1$invokeSuspend$$inlined$runInEdt$default$1.run(actions.kt:60)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IllegalAccessException: class kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance cannot access a member of class software.aws.toolkits.jetbrains.services.ecs.exec.OpenShellInContainerDialog with modifiers "private"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1102)
	at java.base/java.lang.reflect.Field.get(Field.java:423)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$FieldGetter$BoundInstance.call(CallerImpl.kt:179)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	... 54 more
```

**To reproduce**
1. select ECS cluster;
2. select certain service;
3. select certain container;
4. select open interactive shell;

**Expected behavior**
Open interactive shell successfully.

**Screenshots**

**Your Environment**
- OS: Windows
- JetBrains product: IntelliJ IDEA 2022.2 (Ultimate Edition)
- JetBrains product version: Build #IU-222.3345.118, built on July 26, 2022
- AWS Toolkit version: 1.48-222
- SAM CLI version: 1.53.0
- JVM/Python version: OpenJDK 11

**Additional context**

**Comment by rli** [comment]
Fixed in `1.49`
