### ISSUE TITLE
Error Loading Resources when expanding RDS in AWS Toolkit Explorer

### ISSUE THREAD

**Issue by simonolander** [aws/aws-toolkit-jetbrains#3356]
**Describe the bug**
Expanding the RDS folder in the AWS Toolkit Explorer results in an error shown, and no databases are listed.

The error is
> Error Loading Resources (Rds: InvalidParameterValue)

and the stacktrace in the logs is 
```
software.amazon.awssdk.services.rds.model.RdsException: Unrecognized engine name: aurora (Service: Rds, Status Code: 400, Request ID: 19e5be97-9b8b-42f0-a32a-61acb2ec290e)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.rds.DefaultRdsClient.describeDBClusters(DefaultRdsClient.java:4710)
	at software.amazon.awssdk.services.rds.paginators.DescribeDBClustersIterable$DescribeDbClustersResponseFetcher.nextPage(DescribeDBClustersIterable.java:134)
	at software.amazon.awssdk.services.rds.paginators.DescribeDBClustersIterable$DescribeDbClustersResponseFetcher.nextPage(DescribeDBClustersIterable.java:125)
	at software.amazon.awssdk.core.pagination.sync.PaginatedResponsesIterator.next(PaginatedResponsesIterator.java:58)
	at software.amazon.awssdk.core.pagination.sync.PaginatedItemsIterable$ItemsIterator.<init>(PaginatedItemsIterable.java:58)
	at software.amazon.awssdk.core.pagination.sync.PaginatedItemsIterable.iterator(PaginatedItemsIterable.java:48)
	at software.aws.toolkits.jetbrains.services.rds.resources.RdsResourcesKt$LIST_SUPPORTED_CLUSTERS$1.invoke(RdsResources.kt:73)
	at software.aws.toolkits.jetbrains.services.rds.resources.RdsResourcesKt$LIST_SUPPORTED_CLUSTERS$1.invoke(RdsResources.kt:45)
	at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:242)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$fetch$value$1.invokeSuspend(AwsResourceCache.kt:436)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To reproduce**
1. Go to AWS Toolkit tab
2. Expand RDS
3. See the error message

**Expected behavior**
I expect to see my available databases

**Screenshots**

![Screenshot from 2022-10-25 15-01-48](https://user-images.githubusercontent.com/5345337/197780388-a6af63b4-73d1-4c67-9109-e3d2b235a549.png)

**Your Environment**
- OS: Ubuntu 22.04
- JetBrains product: Datagrip
- JetBrains product version: 2022.2.5
- AWS Toolkit version: 1.52-222
- SAM CLI version: n/a
- JVM version: 17.0.2-tem
- Python version:  3.9.12

**Other information**

The other services, like S3 and SQS seem to work fine.

**Comment by simonolander** [comment]
I can't seem to reproduce this anymore. I don't know what caused the issue or how it was solved, but I'm able to list the RDS instances again.

**Comment by illoyd** [comment]
I have the same issue whereby expanding the RDS leaf shows an error. Hovering over the error, it gives further details:

`Unrecognised engine name: aurora (Service: rds, Status code: 400, Request ID: xxx`

**Comment by simonolander** [comment]
@illoyd That's the same error I had originally. As I wrote in October, the issue went away by itself for me. Wild speculation, but perhaps someone in my organisation added an Aurora database, and then removed it.

**Comment by d1mka988** [comment]
I got the same issue, look like AWS has removed from API 'aurora' engine... but issue is reproduced on eu-* region for me

**Comment by LeeTann** [comment]
I am receiving the same exact error. All the other services seems to work. Any has a solution to get pass this?

**Comment by raffclar** [comment]
I'm also getting this issue. I have some a few Postgres DBs and some Serverless Aurora MySQL DBs.

DataGrip version 2022.2.5
AWS Toolkit version 1.64-222

**Comment by ashleywxwx** [comment]
Not a fix, but might help someone out who's following AWS's tutorial and stuck: The plugin is still authenticating you to AWS, and you should still be able to manually create the database connections you need.

**Comment by rli** [comment]
Issue is that RDS is no longer treating `aurora` as valid in certain regions. Toolkit needs to handle this better

```
$ aws rds describe-db-engine-versions --engine aurora --query "DBEngineVersions[].EngineVersion" --region us-west-2
[
    "5.6.mysql_aurora.1.22.3"
]
$ aws rds describe-db-engine-versions --engine aurora --query "DBEngineVersions[].EngineVersion" --region us-west-1

An error occurred (InvalidParameterValue) when calling the DescribeDBEngineVersions operation: Unrecognized engine name: aurora
```

**Comment by jordantangy** [comment]
I'm not using aurora, I'm using PostgreSQL but I have the same error : 

Error Loading Resource(rds: Invalid parameter value)

When I hover it, it says : Unrecognized engine name : aurora

**Comment by rli** [comment]
Released in 1.68
