### ISSUE TITLE
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException when choosing an input template in Lambda Run Configurations

### ISSUE THREAD

**Issue by ghaiszaher** [aws/aws-toolkit-jetbrains#3359]
**Describe the bug**
I am unable to choose an input template in AWS Lambda run configurations for most of the templates. Only "S3 Delete" and "Scheduled Event" templates work.

**To reproduce**
1. Add a new Lambda run configuration (Local or Remote).
2. Change the input to Text and choose any existing template (except for S3 Delete and Scheduled Event).
3. Nothing is shown upon choosing the template.
4. Close the popup and IntelliJ will report an exception coming from the plugin:
```
Failed to parse Partitions

com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class software.aws.toolkits.core.region.Partitions] value failed for JSON property partitions due to missing (therefore NULL) value for creator parameter partitions which is a non-nullable type
 at [Source: (FileInputStream); line: 5, column: 1] (through reference chain: software.aws.toolkits.core.region.Partitions["partitions"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:518)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
	at software.aws.toolkits.core.region.PartitionParser$parse$1.invoke(Partitions.kt:48)
	at software.aws.toolkits.core.region.PartitionParser$parse$1.invoke(Partitions.kt:47)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull(LogUtils.kt:21)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull$default(LogUtils.kt:20)
	at software.aws.toolkits.core.region.PartitionParser.parse(Partitions.kt:47)
	at software.aws.toolkits.core.region.EndpointsJsonValidator.canBeParsed(Partitions.kt:53)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver.internalResolve(RemoteResourceResolver.kt:69)
	at software.aws.toolkits.core.utils.DefaultRemoteResourceResolver.resolve$lambda$0(RemoteResourceResolver.kt:30)
	at software.aws.toolkits.jetbrains.core.DefaultRemoteResourceResolverProvider$Companion$RESOLVER_INSTANCE$2$1.invoke$lambda$0(RemoteResourceResolverProvider.kt:36)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Expected behavior**
The chosen template should show.

**Screenshots**

Example of an event that doesn't show:
![image](https://user-images.githubusercontent.com/20379416/198221356-0b25220d-5ba5-4ad5-b35c-181672071f57.png)

Example of an event that shows (only S3 Delete and Scheduled Event):
![image](https://user-images.githubusercontent.com/20379416/198221403-0b31b543-98ba-4ffd-89ff-ea17b73a57b2.png)

Exception:
![image](https://user-images.githubusercontent.com/20379416/198221528-95219bbf-fd91-40c2-9d9f-9f069dfe0381.png)

**Your Environment**
- OS: macOS 13.0 (22A380)
- JetBrains product: IntelliJ IDEA Ultimate
- JetBrains product version: 2022.2.3 (Build #IU-222.4345.14, built on October 5, 2022)
- AWS Toolkit version: 1.52-222

**Comment by crashev** [comment]
When will this fix be released?

**Comment by vchikoti1998** [comment]
Released on Jan 13th.
