### ISSUE TITLE
Exception in JetBrains Gateway plugin on empty initials in CawsLetterBadge$Companion.getInitials 

### ISSUE THREAD

**Issue by GregPono** [aws/aws-toolkit-jetbrains#3414]
**Describe the bug**
Exception report submitted via

```
java.util.NoSuchElementException: Char sequence is empty.
	at kotlin.text.StringsKt___StringsKt.first(_Strings.kt:72)
	at software.aws.toolkits.jetbrains.services.caws.CawsLetterBadge$Companion.getInitials(CawsLetterBadge.kt:96)
	at software.aws.toolkits.jetbrains.services.caws.CawsLetterBadge$Companion.access$getInitials(CawsLetterBadge.kt:85)
	at software.aws.toolkits.jetbrains.services.caws.CawsLetterBadge.<init>(CawsLetterBadge.kt:43)
	at software.aws.toolkits.jetbrains.gateway.CawsLoadingPanel.createConnectionSettingsPanel(CawsLoadingPanel.kt:260)
	at software.aws.toolkits.jetbrains.gateway.CawsLoadingPanel.createTitleBar(CawsLoadingPanel.kt:206)
	at software.aws.toolkits.jetbrains.gateway.CawsLoadingPanel.access$createTitleBar(CawsLoadingPanel.kt:59)
	at software.aws.toolkits.jetbrains.gateway.CawsLoadingPanel$doLoadContent$1.invokeSuspend(CawsLoadingPanel.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Your Environment**
Product: Gateway 223.7571.70
Platform: Gateway 223.7571.70
OS: Mac OS X
Java: JetBrains s.r.o. 17.0.5
Action: GatewayPluginsAction
Reporter: name
Date: 25.11.2022 18:03:01

**Comment by rli** [comment]
resolved before public release
