### ISSUE TITLE
Cloud-Watch logs not updated: Access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by cforce** [aws/aws-toolkit-jetbrains#3449]
- No current logs visible.
- Click refresh in Log screen
![image](https://user-images.githubusercontent.com/393286/212640633-14466ece-78ce-49f4-80eb-6ac769fc40fd.png)

Exception is thrown - log is nor refreshed
```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 23,4,main] 407588807
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 456850800
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1042)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1025)
	at com.intellij.ui.SpeedSearchBase.isPopupActive(SpeedSearchBase.java:180)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:63)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:52)
	at com.intellij.ui.speedSearch.SpeedSearchUtil.applySpeedSearchHighlighting(SpeedSearchUtil.java:37)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.editor.LogStreamsStreamColumnRenderer.getTableCellRendererComponent(TableUtils.kt:38)
	at com.intellij.ui.table.JBTable.calculateRowHeight(JBTable.java:260)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:238)
	at java.desktop/javax.swing.JTable.getRowHeight(JTable.java:1064)
	at java.desktop/javax.swing.JTable.getCellRect(JTable.java:2983)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.CloudWatchLogsActor.handleMessages$suspendImpl(CloudWatchActor.kt:197)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.CloudWatchLogsActor$handleMessages$1.invokeSuspend(CloudWatchActor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by cforce** [comment]
There seems to be another exception that raises sometimes

```
Unhandled exception in [CoroutineName(software.aws.toolkits.jetbrains.services.cloudwatch.logs.editor.LogGroupTable), StandaloneCoroutine{Cancelling}@1ffeee08, com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor@2697b29a[Running, pool size = 8, active threads = 3, queued tasks = 0, completed tasks = 687063]]

kotlinx.coroutines.channels.ClosedSendChannelException: Channel was closed
	at kotlinx.coroutines.channels.Closed.getSendException(AbstractChannel.kt:1107)
	at kotlinx.coroutines.channels.AbstractSendChannel.helpCloseAndResumeWithSendException(AbstractChannel.kt:230)
	at kotlinx.coroutines.channels.AbstractSendChannel.access$helpCloseAndResumeWithSendException(AbstractChannel.kt:19)
	at kotlinx.coroutines.channels.AbstractSendChannel.sendSuspend(AbstractChannel.kt:220)
	at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:136)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.editor.LogGroupTable$2$1$1.invokeSuspend(LogGroupTable.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(software.aws.toolkits.jetbrains.services.cloudwatch.logs.editor.LogGroupTable), StandaloneCoroutine{Cancelled}@1ffeee08, com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor@2697b29a[Running, pool size = 8, active threads = 3, queued tasks = 0, completed tasks = 2933841]]

```

**Comment by genachka** [comment]
Bump. Been seeing this for the past 4 months but it's become more frequent. Making using the cloudwatch logs almost useable lately.  Been almost 9 months since it's been reported. Can this please be addressed already?
I'm currently on IntelliJ IDEA 2023.2.1 and AWS Toolkit 1.78-232

**Comment by genachka** [comment]
Bump. 
Is anyone able to address this? Viewing Lambda's cloudwatch logs is utterly useless in this state. 95% of the time it results in exceptions. Can't scroll down the list for more logs when it does. Can't search for content across any period. This was reported almost a year ago and even with 1.79-232 it's just as awful! Please address this.

**Comment by genachka** [comment]
Bump.
Now on 1.84-232 and still awful useless Lambda cloudwatch log viewing. Most of the time can't even open a single log anymore. Clearly with so many months of this being ignored it's not important to anyone to fix over just adding new features than making existing ones work reliably so why have it at all. :(
