### ISSUE TITLE
Exception in plugin AWS Toolkit (1.57-223)

### ISSUE THREAD

**Issue by nadersalehi** [aws/aws-toolkit-jetbrains#3457]
**Describe the bug**
The plugin periodically throws the following exception:

`com.intellij.diagnostic.PluginException: software.aws.toolkits.jetbrains.services.codewhisperer.editor.CodeWhispererEnterHandler PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit, id=aws.toolkit, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.3/aws-toolkit-jetbrains, version=1.57-223, package=null, isBundled=false), packagePrefix=null, instanceId=431, state=active)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.getHandlerChain(DynamicEditorActionHandler.java:136)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.getHandler(DynamicEditorActionHandler.java:96)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.isEnabled(DynamicEditorActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:125)
	at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:111)
	at com.intellij.openapi.editor.actionSystem.EditorAction.updateForKeyboardAccess(EditorAction.java:115)
	at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:720)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$5(ActionUpdater.java:186)
	at com.intellij.diagnostic.telemetry.TraceKt.computeWithSpan(trace.kt:123)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:137)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$UpdateSessionImpl.presentation(ActionUpdater.java:814)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doUpdateActionsInner(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:621)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$15(Utils.java:756)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:428)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:424)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$16(Utils.java:756)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$18(Utils.java:763)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$20(Utils.java:762)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: software.aws.toolkits.jetbrains.services.codewhisperer.editor.CodeWhispererEnterHandler PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit, id=aws.toolkit, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2022.3/aws-toolkit-jetbrains, version=1.57-223, package=null, isBundled=false), packagePrefix=null, instanceId=431, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1519)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:941)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.getHandlerChain(DynamicEditorActionHandler.java:115)
	... 47 more
`

**To reproduce**

1. Activate the plugin

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: Fedora 36
- JetBrains product: IntelliJ IDEA 
- JetBrains product version: 2022.3.1 (Ultimate Edition)
- AWS Toolkit version: 1.57-223
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by zixlin7** [comment]
Please update to latest version and let us know if still having issue
