### ISSUE TITLE
Exception in plugin in AWS Toolkit (1.60-223) Disable plugin...This plugin is not a production of Jetbrains...

### ISSUE THREAD

**Issue by hdnguyen** [aws/aws-toolkit-jetbrains#3473]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
- OS: 
- JetBrains product:
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by rli** [comment]
Do you have any more information to share about your issue?

**Comment by hdnguyen** [comment]
No, just started a new project for AWS SAM application with SAM Template "AWS SAM Hello World" then errored out while it doing "Generating SAM template..."

**Comment by hdnguyen** [comment]
Here the stack trace...
java.lang.RuntimeException: Could not execute `sam init`!: [Cloning from https://github.com/aws/aws-sam-cli-app-templates, Error: Please verify your location. The following types of location are supported:, * Github: gh:user/repo (or) https://github.com/user/repo (or) git@github.com:user/repo.git,           For Git repositories, you must use location of the root of the repository., * Mercurial: hg+ssh://hg@bitbucket.org/repo, * Http(s): https://example.com/code.zip, * Local Path: /path/to/code.zip]
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner$execute$1.invoke(SamInitRunner.kt:55)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner$execute$1.invoke(SamInitRunner.kt:33)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner.execute$lambda$0(SamInitRunner.kt:33)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamInitRunner.execute(SamInitRunner.kt:33)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder.runSamInit(SamProjectGeneratorIntelliJShims.kt:94)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.invoke(SamProjectGeneratorIntelliJShims.kt:76)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1$run$1.invoke(SamProjectGeneratorIntelliJShims.kt:75)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1.run$lambda$0(SamProjectGeneratorIntelliJShims.kt:75)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$10(ModuleRootModificationUtil.java:157)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:165)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:156)
	at software.aws.toolkits.jetbrains.services.lambda.wizard.SamProjectBuilder$setupRootModel$1.run(SamProjectGeneratorIntelliJShims.kt:75)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by hdnguyen** [comment]
PyCharm 2022.3.2
AWS Toolkit: 1.60-223
Ubuntu 64-bit Desktop 20.04
