### ISSUE TITLE
Indexing error starting up new sam project

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-jetbrains#351]
**Describe the bug**

I created a new java project with sam init:
`sam init --runtime java -n hellojava`

When I opened the folder in IntelliJ I got an exception:

```
Error while indexing C:\_mytemp\sam-node\hellojava\src\test\java\helloworld\AppTest.java
To reindex this file IDEA has to be restarted

com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:77)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:774)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:723)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:706)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:336)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:312)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:47)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:85)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:120)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:39)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:125)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:102)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.implementsLambdaHandlerInterface(JavaLambdaHandlerResolver.kt:159)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.findHandlersByClass(JavaLambdaHandlerResolver.kt:129)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.determineHandlers(JavaLambdaHandlerResolver.kt:60)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.determineHandlers(JavaLambdaHandlerResolver.kt:62)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaHandlerIndex$getIndexer$1$1.visitElement(LambdaHandlerIndex.kt:57)
	at com.intellij.psi.impl.source.tree.java.PsiIdentifierImpl.accept(PsiIdentifierImpl.java:42)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaHandlerIndex$Companion.acceptLeafNodes(LambdaHandlerIndex.kt:79)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaHandlerIndex$Companion.acceptLeafNodes(LambdaHandlerIndex.kt:80)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaHandlerIndex$Companion.acceptLeafNodes(LambdaHandlerIndex.kt:80)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaHandlerIndex$Companion.access$acceptLeafNodes(LambdaHandlerIndex.kt:69)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaHandlerIndex$getIndexer$1.map(LambdaHandlerIndex.kt:53)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaHandlerIndex$getIndexer$1.map(LambdaHandlerIndex.kt:20)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:273)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:97)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1668)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1596)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:524)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1555)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1543)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:110)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:230)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:243)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**
 - OS: 
 - JetBrains' Product:
 - JetBrains' Product Version:
 - Toolkit Version:

**Additional context**

**Comment by abrooksv** [comment]
Should be fixed in master

**Comment by abrooksv** [comment]
#356 and #358  should have fixed this, I don't see this issue when I reproduce it

**Comment by kiiadi** [comment]
@awschristou can you re-test this and close if resolved?

**Comment by awschristou** [comment]
I tested this with commit cc35021 and the exception no longer appears. Closing.
