### ISSUE TITLE
Invalid sam executable

### ISSUE THREAD

**Issue by Falcons34** [aws/aws-toolkit-jetbrains#3546]
**Describe the bug**
I've followed the AWS Toolkit for Intellij Ultimate but keep getting this error.
[https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/setup-toolkit.html](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/setup-toolkit.html)

**Cannot Save Settings**

```Invalid sam executable: Traceback (most recent call last): File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 154, in __init__ self._custom_adapter = NpipeHTTPAdapter( NameError: name 'NpipeHTTPAdapter' is not defined  During handling of the above exception, another exception occurred:  Traceback (most recent call last): File "runpy.py", line 194, in _run_module_as_main File "runpy.py", line 87, in _run_code File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in   cli(prog_name="sam") File "C:\Users\profe\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__ return self.main(*args, **kwargs) File "C:\Users\profe\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 781, in main with self.make_context(prog_name, args, **extra) as ctx: File "C:\Users\profe\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 700, in make_context self.parse_args(ctx, args) File "C:\Users\profe\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1212, in parse_args rest = Command.parse_args(self, ctx, args) File "C:\Users\profe\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1048, in parse_args value, args = param.handle_parse_result(ctx, opts, args) File "C:\Users\profe\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1630, in handle_parse_result value = invoke_param_callback(self.callback, ctx, self, value) File "C:\Users\profe\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 123, in invoke_param_callback return callback(ctx, param, value) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 56, in print_info "additional_dependencies": gather_additional_dependencies_info(), File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 37, in gather_additional_dependencies_info "docker_engine": _gather_docker_info(), File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 59, in _gather_docker_info with contextlib.closing(docker.from_env()) as client: File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 84, in from_env return cls( File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 40, in __init__ self.api = APIClient(*args, **kwargs) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 158, in __init__ raise DockerException( docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support```

**To reproduce**
File -> Settings -> Tools -> AWS SAM CLI executable is fine

File -> New -> Project -> AWS Serverless Application -> Next 

**Expected behavior**
New AWS Serverless app created

**Screenshots**
![image](https://user-images.githubusercontent.com/89521528/227436768-f1ed4448-25a2-4e3d-b568-364b1ad962bc.png)
Tools

![image](https://user-images.githubusercontent.com/89521528/227437032-b23b0b45-f909-4287-b678-fd1be5ebd2ad.png)
Project

**Your Environment**
- OS: Window 10
- JetBrains product: Intellij Ultimate
- JetBrains product version: Build #IU-222.4345.14, built on October 5, 2022
- AWS Toolkit version: 1.62-222
- SAM CLI version: SAM CLI, version 1.78.0
- JVM/Python version: 3.8

**Additional context**

**Comment by rli** [comment]
```
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support
```

The issue appears to be coming from SAM CLI
https://github.com/aws/aws-sam-cli/issues/3873
