### ISSUE TITLE
LogStreamsStreamColumnRenderer: Access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by vchikoti1998** [aws/aws-toolkit-jetbrains#3549]
**Describe the bug**
```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 8,4,main] 857946696
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 636498558
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1067)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1050)
	at com.intellij.ui.SpeedSearchBase.isPopupActive(SpeedSearchBase.java:180)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:63)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:52)
	at com.intellij.ui.speedSearch.SpeedSearchUtil.applySpeedSearchHighlighting(SpeedSearchUtil.java:37)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.editor.LogStreamsStreamColumnRenderer.getTableCellRendererComponent(TableUtils.kt:38)
	at com.intellij.ui.table.JBTable.calculateRowHeight(JBTable.java:260)
	at com.intellij.ui.table.JBTable.getRowHeight(JBTable.java:238)
	at java.desktop/javax.swing.JTable.getRowHeight(JTable.java:1065)
	at java.desktop/javax.swing.JTable.getCellRect(JTable.java:2984)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.CloudWatchLogsActor.handleMessages$suspendImpl(CloudWatchActor.kt:197)
	at software.aws.toolkits.jetbrains.services.cloudwatch.logs.CloudWatchLogsActor$handleMessages$1.invokeSuspend(CloudWatchActor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rli** [comment]
same as #3449
