### ISSUE TITLE
Failed to set up software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory@10792785

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#3557]
```
Failed to set up software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory@10792785

java.util.MissingResourceException: Registry key aws.telemetry.region is not defined
    at com.intellij.openapi.util.registry.Registry.getBundleValue(Registry.java:170)
    at com.intellij.openapi.util.registry.RegistryValue._get(RegistryValue.java:233)
    at com.intellij.openapi.util.registry.RegistryValue.get(RegistryValue.java:203)
    at com.intellij.openapi.util.registry.RegistryValue.asString(RegistryValue.java:54)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryPublisher$Companion.createDefaultTelemetryClient(DefaultTelemetryPublisher.kt:100)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryPublisher$Companion.access$createDefaultTelemetryClient(DefaultTelemetryPublisher.kt:95)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryPublisher.<init>(DefaultTelemetryPublisher.kt:25)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService$Companion$publisher$2.invoke(TelemetryService.kt:136)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService$Companion$publisher$2.invoke(TelemetryService.kt:136)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService$Companion.getPublisher(TelemetryService.kt:136)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService$Companion.access$getPublisher(TelemetryService.kt:135)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService.<init>(TelemetryService.kt:133)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
    at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
    at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
    at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
    at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
    at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
    at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
    at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
    at software.aws.toolkits.jetbrains.services.telemetry.TelemetryService$Companion.getInstance(TelemetryService.kt:142)
    at software.aws.toolkits.telemetry.AwsTelemetry.loadCredentials(TelemetryDefinitions.kt:2848)
    at software.aws.toolkits.telemetry.AwsTelemetry.loadCredentials$default(TelemetryDefinitions.kt:2841)
    at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager$1$1$1.invoke(CredentialManager.kt:136)
    at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager$1$1$1.invoke(CredentialManager.kt:122)
    at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.loadProfiles(ProfileCredentialProviderFactory.kt:137)
    at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.setUp(ProfileCredentialProviderFactory.kt:83)
    at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager$1$1.invoke(CredentialManager.kt:122)
    at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager$1$1.invoke(CredentialManager.kt:121)
    at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull(LogUtils.kt:21)
    at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull$default(LogUtils.kt:20)
    at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager.<init>(CredentialManager.kt:121)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
    at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
    at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
    at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
    at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.compute(ServiceComponentAdapter.kt:45)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
    at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
    at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
    at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
    at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
    at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
    at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$Companion.getInstance(CredentialManager.kt:154)
    at software.aws.toolkits.jetbrains.core.credentials.DefaultToolkitConnectionManager.getDefaultConnection(DefaultToolkitConnectionManager.kt:46)
    at software.aws.toolkits.jetbrains.core.credentials.DefaultToolkitConnectionManager.activeConnectionForFeature(DefaultToolkitConnectionManager.kt:73)
    at software.aws.toolkits.jetbrains.services.codewhisperer.explorer.CodeWhispererExplorerActionManager.checkActiveCodeWhispererConnectionType(CodeWhispererExplorerActionManager.kt:127)
    at software.aws.toolkits.jetbrains.services.codewhisperer.explorer.CodeWhispererExplorerActionManagerKt.isCodeWhispererEnabled(CodeWhispererExplorerActionManager.kt:205)
    at software.aws.toolkits.jetbrains.services.codewhisperer.status.CodeWhispererStatusBarManager.updateWidget(CodeWhispererStatusBarManager.kt:55)
    at software.aws.toolkits.jetbrains.services.codewhisperer.startup.CodeWhispererProjectStartupActivity.runActivity(CodeWhispererProjectStartupActivity.kt:36)
    at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
    at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
    at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1$1.run(StartupManagerImpl.kt:82)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
    at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
    at com.intellij.ide.startup.impl.StartupManagerImpl$Companion$addActivityEpListener$1$extensionAdded$1.run(StartupManagerImpl.kt:81)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dfourmanfsquared** [comment]
I'm having this same issue, the plugin is failing after:
![image](https://user-images.githubusercontent.com/107331834/229314334-8068e2c4-59ec-49a9-8b10-9666910a9365.png)
