### ISSUE TITLE
ALT+D fails to provide any suggestions

### ISSUE THREAD

**Issue by jiripik** [aws/aws-toolkit-jetbrains#3584]
```
java.lang.RuntimeException: Cannot invoke (class=CodeWhispererUIChangeListener, method=stateChanged, topic=CodeWhisperer popup state changed)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:657)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy6/jdk.proxy6.$Proxy208.stateChanged(Unknown Source)
	at software.aws.toolkits.jetbrains.services.codewhisperer.popup.CodeWhispererPopupManager.changeStates(CodeWhispererPopupManager.kt:165)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.updateCodeWhisperer(CodeWhispererService.kt:466)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.processCodeWhispererUI(CodeWhispererService.kt:379)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.access$processCodeWhispererUI(CodeWhispererService.kt:76)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService$invokeCodeWhispererInBackground$2$1$1$1.invoke(CodeWhispererService.kt:220)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService$invokeCodeWhispererInBackground$2$1$1$1.invoke(CodeWhispererService.kt:218)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:58)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.diagnostic.PluginException: Positive width should be defined for an inline element by software.aws.toolkits.jetbrains.services.codewhisperer.inlay.CodeWhispererInlayInlineRenderer@c4ac597 [Plugin: aws.toolkit]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.editor.impl.InlineInlayImpl.doUpdate(InlineInlayImpl.java:73)
	at com.intellij.openapi.editor.impl.InlayImpl.<init>(InlayImpl.java:35)
	at com.intellij.openapi.editor.impl.InlineInlayImpl.<init>(InlineInlayImpl.java:26)
	at com.intellij.openapi.editor.impl.InlayModelImpl.addInlineElement(InlayModelImpl.java:150)
	at com.intellij.openapi.editor.impl.InlayModelImpl.addInlineElement(InlayModelImpl.java:137)
	at software.aws.toolkits.jetbrains.services.codewhisperer.inlay.CodeWhispererInlayManager.createCodeWhispererInlays(CodeWhispererInlayManager.kt:37)
	at software.aws.toolkits.jetbrains.services.codewhisperer.inlay.CodeWhispererInlayManager.updateInlays(CodeWhispererInlayManager.kt:19)
	at software.aws.toolkits.jetbrains.services.codewhisperer.popup.CodeWhispererUIChangeListener.stateChanged(CodeWhispererUIChangeListener.kt:55)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
	... 49 more

```

**Comment by leigaol** [comment]
This should have been fixed in the latest v2.0+ AWS Toolkit for JetBrains release https://plugins.jetbrains.com/plugin/11349-aws-toolkit--amazon-q-codewhisperer-and-more/versions. Could you try it with the latest plugin? Thank you!
