### ISSUE TITLE
RDS node failed to load

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#3598]
```
2023-04-14 11:45:45,980 [2789254]   INFO - software.aws.toolkits.jetbrains.services.rds.RdsExplorerParentNode - Failed to get children
java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.services.rds.model.Endpoint.address()" because the return value of "software.amazon.awssdk.services.rds.model.DBInstance.endpoint()" is null
	at software.aws.toolkits.jetbrains.services.rds.resources.RdsResourcesKt$LIST_SUPPORTED_INSTANCES$1.invoke(RdsResources.kt:38)
	at software.aws.toolkits.jetbrains.services.rds.resources.RdsResourcesKt$LIST_SUPPORTED_INSTANCES$1.invoke(RdsResources.kt:17)
	at software.aws.toolkits.jetbrains.core.ClientBackedCachedResource.fetch(AwsResourceCache.kt:283)
	at software.aws.toolkits.jetbrains.core.DefaultAwsResourceCache$fetch$value$1.invokeSuspend(AwsResourceCache.kt:532)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by kevinzhao-upstart** [comment]
any updates on this? I am getting the same error

**Comment by brianmedigate** [comment]
I experienced something similar, and in my case it was because one of my RDS instances was in the middle of being backed up. The backup instance was on the `creating` state, and therefore didn't have an endpoint. I found this by running `aws rds describe-db-instances` and noticed that one of the entries didn't have an `Endpoint` entry.

**Comment by bruuuuuuuce** [comment]
I am seeing this same error. Are there any updates on how to fix this? I have confirmed that my database is not being backed up.

**Comment by bruuuuuuuce** [comment]
I fixed this by manually adding a postgres connection. It seems to be an issue with the toolkit plugin, and not the actual connection to my database
