### ISSUE TITLE
java.lang.Throwable: Inlay operations are not supported for injected editors editing CSS (styled-components)

### ISSUE THREAD

**Issue by jugglingcats** [aws/aws-toolkit-jetbrains#3601]
**Describe the bug**
```java.lang.Throwable: Inlay operations are not supported for injected editors
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.impl.source.tree.injected.InlayModelWindow.logUnsupported(InlayModelWindow.java:157)
	at com.intellij.psi.impl.source.tree.injected.InlayModelWindow.getInlineElementsInRange(InlayModelWindow.java:82)
	at com.intellij.openapi.editor.InlayModel.getInlineElementsInRange(InlayModel.java:139)
	at software.aws.toolkits.jetbrains.services.codewhisperer.inlay.CodeWhispererInlayManager.clearInlays(CodeWhispererInlayManager.kt:51)
```

**To reproduce**
I am editing a Typescript file with styled-components, eg:
![image](https://user-images.githubusercontent.com/526349/232286852-c42e270c-7170-43ee-9030-0818cd762d21.png)

**Expected behavior**
Suggested code should be displayed.

**Your Environment**
Note that copilot plugin is disabled.

```
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Subscription is active until March 1, 2024.
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    com.github.copilot (1.2.5.2507)
    mdx.js (231.8109.91)
    Pythonid (231.8109.175)
    aws.toolkit (1.65-231)

Kotlin: 231-1.8.20-IJ8109.175
```

**Comment by mmelnic** [comment]
looks like it can't work with styled.components yet, have the same issue
