### ISSUE TITLE
Exception occurred attempting to inject region/credentials

### ISSUE THREAD

**Issue by gelu22** [aws/aws-toolkit-jetbrains#3621]
**Your Environment**

- OS: Linux Mint
- JetBrains product: 
- PyCharm 2023.1 (Community Edition)
Build #PC-231.8109.197, built on March 29, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-70-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1740M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.edu (2023.3-2023.1-277)
    aws.toolkit (1.66-231)
- JetBrains product version:
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version: Python 3.10

**Question**
I have constant connection (i think) errors, but AWS Toolkit works - I'm at the start of my education about how it all works, kindly please help me.

```
Exception occurred attempting to inject region/credentials

java.lang.RuntimeException: Configure AWS Connection
	at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension.getConnection(AwsConnectionExtension.kt:100)
	at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension.injectCredentials(AwsConnectionExtension.kt:61)
	at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension.addToTargetEnvironment(AwsConnectionExtension.kt:32)
	at software.aws.toolkits.jetbrains.core.execution.PythonAwsConnectionCommandLineTargetEnvironmentProvider.extendTargetEnvironment(PythonAwsConnectionCommandLineTargetEnvironmentProvider.kt:31)
	at com.jetbrains.python.run.PythonCommandLineState.initEnvironment(PythonCommandLineState.java:675)
	at com.jetbrains.python.run.PythonCommandLineState.buildPythonExecutionFinal(PythonCommandLineState.java:360)
	at com.jetbrains.python.run.PythonCommandLineState.startProcess(PythonCommandLineState.java:324)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:232)
	at com.jetbrains.python.run.PythonScriptCommandLineState.execute(PythonScriptCommandLineState.java:147)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:178)
	at com.jetbrains.python.run.PythonRunner.lambda$execute$2(PythonRunner.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rli** [comment]
The error message needs work, but it's saying that you need select a default connection with IAM credentials, either through the "AWS Toolkit" tab or "AWS Connection Settings" status bar

**Comment by gelu22** [comment]
> The error message needs work, but it's saying that you need select a default connection with IAM credentials, either through the "AWS Toolkit" tab or "AWS Connection Settings" status bar

Thanks, it is very new to me, but also satysfying - Create IAM User, credentials, keys, edit config file in PyCharm - I almost don't know what I am doing, but (slow) learning all this is great!
