### ISSUE TITLE
Read access is allowed from inside read-action (or EDT) only

### ISSUE THREAD

**Issue by amendlik** [aws/aws-toolkit-jetbrains#3624]
**Describe the bug**
Exception from AWS toolkit

**To reproduce**
Not sure yet. It happens a lot, but doesn't seem to affect anything. I only notice it because the red error light flashes.

**Screenshots**
```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 170,4,main] 1097894486 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1737170780
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:133)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:125)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.getModuleForFile(ProjectFileIndexFacade.java:72)
	at com.intellij.psi.search.GlobalSearchScope$FileScope.<init>(GlobalSearchScope.java:823)
	at com.intellij.psi.search.GlobalSearchScope$FileScope.<init>(GlobalSearchScope.java:813)
	at com.intellij.psi.search.GlobalSearchScope.fileScope(GlobalSearchScope.java:356)
	at com.intellij.psi.search.GlobalSearchScope.fileScope(GlobalSearchScope.java:350)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.listResources(CloudFormationTemplateIndex.kt:101)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateKt.validateSamTemplateHasResources(CloudFormationTemplate.kt:144)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamTemplateFileUtils.validateTemplateFile(SamCommonUtils.kt:68)
	at software.aws.toolkits.jetbrains.services.lambda.actions.SyncServerlessAppAction$actionPerformed$1.invoke(SyncServerlessAppAction.kt:117)
	at software.aws.toolkits.jetbrains.services.lambda.actions.SyncServerlessAppAction$actionPerformed$1.invoke(SyncServerlessAppAction.kt:73)
	at software.aws.toolkits.jetbrains.services.lambda.actions.SyncServerlessAppAction.actionPerformed$lambda$0(SyncServerlessAppAction.kt:73)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.aws.toolkits.jetbrains.core.executables.DefaultExecutableManager.getExecutable$lambda$7(ExecutableManager.kt:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Your Environment**
- OS: Windows 11
- JetBrains product: PyCharm
- JetBrains product version: 2023.1
- AWS Toolkit version: 1.66.231
- SAM CLI version: 1.78.0
- JVM/Python version: 3.9

**Additional context**

**Comment by rli** [comment]
Fixed in 1.67
