### ISSUE TITLE
InvalidGrantException

### ISSUE THREAD

**Issue by fernando2amigos** [aws/aws-toolkit-jetbrains#3638]
Just logged in from PHPStorm after upgrading AWSToolkit to 1.67-231

**To reproduce**
In PHPStorm, upgrade AWSToolkit to its latest version (1.67-231)
Log in using AWS Builder ID
Do normal process and see access granted and IDE working
After a few seconds receive Service returned error code InvalidGrantException

software.amazon.awssdk.services.ssooidc.model.InvalidGrantException: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400 ...

**Your Environment**
- OS: Windows  11 + WSL2
- JetBrains product: PhpStorm 2023.1 Build #PS-231.8109.199, built on March 29, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- AWS Toolkit version: 1.67-231

**Comment by rli** [comment]
Could you share your IDE logs with us? `Help -> Show Log in Explorer`
At the very least we need the context surrounding the exception, including the stacktrace

**Comment by fernando2amigos** [comment]
Oh, sure.
FYI, after re-connecting it worked fine, and it's still as of now. 

Sorry, I thought it wouldn't makes sense the stack trace in this context, but here I go (just obfuscated the Request ID)

```
2023-04-28 11:59:58,213 [5793009] SEVERE - #c.i.o.a.i.ApplicationImpl - Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: 7166a489-b631-4063-bf6c-XXXXXXXXXXXX)
software.amazon.awssdk.services.ssooidc.model.InvalidGrantException: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: 7166a489-b631-4063-bf6c-XXXXXXXXXXXX)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.ssooidc.DefaultSsoOidcClient.createToken(DefaultSsoOidcClient.java:156)
	at software.amazon.awssdk.services.ssooidc.SsoOidcClient.createToken(SsoOidcClient.java:224)
	at software.aws.toolkits.jetbrains.core.credentials.sso.SsoAccessTokenProvider.pollForToken(SsoAccessTokenProvider.kt:133)
	at software.aws.toolkits.jetbrains.core.credentials.sso.SsoAccessTokenProvider.accessToken(SsoAccessTokenProvider.kt:63)
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.reauthenticate(BearerTokenProvider.kt:151)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1$1.invoke(ToolkitAuthManager.kt:226)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1$1.invoke(ToolkitAuthManager.kt:225)
	at software.aws.toolkits.jetbrains.utils.ThreadingUtilsKt.runUnderProgressIfNeeded(ThreadingUtils.kt:30)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1.invoke(ToolkitAuthManager.kt:225)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1.invoke(ToolkitAuthManager.kt:224)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.maybeReauthProviderIfNeeded(ToolkitAuthManager.kt:239)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.reauthProviderIfNeeded(ToolkitAuthManager.kt:224)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.reauthProviderIfNeeded(ToolkitAuthManager.kt:220)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.reauthConnection(ToolkitAuthManager.kt:178)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.loginSso(ToolkitAuthManager.kt:169)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.loginSso$default(ToolkitAuthManager.kt:107)
	at software.aws.toolkits.jetbrains.services.codewhisperer.util.CodeWhispererUtil.reconnectCodeWhisperer$lambda$4(CodeWhispererUtil.kt:167)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by WhiteRaven777** [comment]
This exception occurred in my environment.
Some time after authentication, this exception occurs and I am forced to reconnect.

I hope that the information here will be of some help.

---

**Your Environment**
- OS: Kubuntu 22.04 LTS (Linux 5.15.0-71-generic)
- JetBrains product: GoLand 2023.1.1
- JetBrains product version: Build #GO-231.8770.71, built on May 3, 2023
- AWS Toolkit version: AWS Toolkit For JetBrains 1.67-231
- SAM CLI version: SAM CLI, version 1.81.0
- JVM/Python version: JRE 17.0.6+10-b829.9 amd64

**Internal error in the IDE**
```
software.amazon.awssdk.services.ssooidc.model.InvalidGrantException: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: ********-****-****-****-************)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.ssooidc.DefaultSsoOidcClient.createToken(DefaultSsoOidcClient.java:156)
	at software.amazon.awssdk.services.ssooidc.SsoOidcClient.createToken(SsoOidcClient.java:224)
	at software.aws.toolkits.jetbrains.core.credentials.sso.SsoAccessTokenProvider.pollForToken(SsoAccessTokenProvider.kt:133)
	at software.aws.toolkits.jetbrains.core.credentials.sso.SsoAccessTokenProvider.accessToken(SsoAccessTokenProvider.kt:63)
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.reauthenticate(BearerTokenProvider.kt:151)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1$1.invoke(ToolkitAuthManager.kt:226)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1$1.invoke(ToolkitAuthManager.kt:225)
	at software.aws.toolkits.jetbrains.utils.ThreadingUtilsKt.runUnderProgressIfNeeded(ThreadingUtils.kt:30)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1.invoke(ToolkitAuthManager.kt:225)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt$reauthProviderIfNeeded$1.invoke(ToolkitAuthManager.kt:224)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.maybeReauthProviderIfNeeded(ToolkitAuthManager.kt:239)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.reauthProviderIfNeeded(ToolkitAuthManager.kt:224)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.reauthProviderIfNeeded(ToolkitAuthManager.kt:220)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.reauthConnection(ToolkitAuthManager.kt:178)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.loginSso(ToolkitAuthManager.kt:169)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.loginSso$default(ToolkitAuthManager.kt:107)
	at software.aws.toolkits.jetbrains.services.codewhisperer.util.CodeWhispererUtil.reconnectCodeWhisperer$lambda$4(CodeWhispererUtil.kt:167)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by madeupname** [comment]
My situation is very similar, but worse. I can't even get the initial login to work. I'm using IntelliJ IDEA Ultimate and it requests access, and then grants it in the website:

> AWS Toolkit for JetBrains can now access your data.
> 
> You can close this window and start using AWS Toolkit for JetBrains.

but then I immediately get an error message like the above in the IDE:

Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400,
```

	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 1 failure: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: eb7e34e2-ebb5-4e2c-8d0f-98929f5940ee)
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 2 failure: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: 253ca32d-0f6b-4248-8e78-25ad016a591d)
2023-06-29 22:09:07,438 [ 371949]   WARN - software.aws.toolkits.jetbrains.core.credentials.ToolkitAddConnectionDialog - Failed to fetch credential with: Modal(loginType=SSO, startUrl=https://SECRET.awsapps.com/start, region=us-west-2); reason: Access denied
software.amazon.awssdk.services.ssooidc.model.InvalidGrantException: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: e26e2eab-5cb6-4aea-97d2-e6bbf8eee20f)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
...
```
Do I have to do something special in IAM Identity Center beyond creating the user? Special permissions? User is verified.

I'm using Windows and I've tried with both Firefox and Chrome.

**Comment by fernando2amigos** [comment]
JFYI, this didn't happen anymore on my side.

**Comment by at0dd** [comment]
I just started receiving the same error today. I updated AWS Toolkit to 1.87-232 in PyCharm 2023.2.4 Community Edition and Rider 2023.2.3. No other changes or issues before today. Running macOS 14.1.

```
Exception occurred attempting to inject region/credentials
  
  software.amazon.awssdk.services.ssooidc.model.InvalidGrantException: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:196)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
at software.amazon.awssdk.services.ssooidc.DefaultSsoOidcClient.createToken(DefaultSsoOidcClient.java:156)
at software.amazon.awssdk.services.ssooidc.SsoOidcClient.createToken(SsoOidcClient.java:224)
at software.aws.toolkits.jetbrains.core.credentials.sso.SsoAccessTokenProvider.refreshToken(SsoAccessTokenProvider.kt:180)
at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.refreshToken(BearerTokenProvider.kt:123)
at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.supplier$lambda$0(BearerTokenProvider.kt:101)
at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$8(CachedSupplier.java:300)
at software.amazon.awssdk.utils.cache.NonBlocking.fetch(NonBlocking.java:141)
at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:208)
at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.resolveToken(BearerTokenProvider.kt:134)
at software.aws.toolkits.core.credentials.ToolkitBearerTokenProvider.resolveToken(ToolkitCredentialsProvider.kt)
at software.aws.toolkits.jetbrains.core.credentials.sso.SsoCredentialProvider.refreshCredentials(SsoCredentialProvider.kt:40)
at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$8(CachedSupplier.java:300)
at software.amazon.awssdk.utils.cache.CachedSupplier$PrefetchStrategy.fetch(CachedSupplier.java:448)
at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:208)
at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
at software.aws.toolkits.jetbrains.core.credentials.sso.SsoCredentialProvider.resolveCredentials(SsoCredentialProvider.kt:34)
at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileSsoSessionProvider.resolveCredentials(ProfileSsoSessionProvider.kt:54)
at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$AwsCredentialProviderProxy$resolveCredentials$1.invoke(CredentialManager.kt:111)
at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$AwsCredentialProviderProxy$resolveCredentials$1.invoke(CredentialManager.kt:110)
at software.aws.toolkits.jetbrains.utils.ThreadingUtilsKt.runUnderProgressIfNeeded(ThreadingUtils.kt:30)
at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$AwsCredentialProviderProxy.resolveCredentials(CredentialManager.kt:110)
at software.aws.toolkits.core.credentials.ToolkitCredentialsProvider.resolveCredentials(ToolkitCredentialsProvider.kt)
at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension$addToTargetEnvironment$2.invoke(AwsConnectionExtension.kt:38)
at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension$addToTargetEnvironment$2.invoke(AwsConnectionExtension.kt:32)
at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension.injectCredentials(AwsConnectionExtension.kt:62)
at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension.addToTargetEnvironment(AwsConnectionExtension.kt:32)
at software.aws.toolkits.jetbrains.core.execution.PythonAwsConnectionCommandLineTargetEnvironmentProvider.extendTargetEnvironment(PythonAwsConnectionCommandLineTargetEnvironmentProvider.kt:31)
at com.jetbrains.python.run.PythonCommandLineState.initEnvironment(PythonCommandLineState.java:691)
at com.jetbrains.python.run.PythonCommandLineState.buildPythonExecutionFinal(PythonCommandLineState.java:363)
at com.jetbrains.python.run.PythonCommandLineState.startProcess(PythonCommandLineState.java:327)
at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:234)
at com.jetbrains.python.run.PythonScriptCommandLineState.execute(PythonScriptCommandLineState.java:147)
at com.jetbrains.python.debugger.PyDebugRunner.lambda$createSessionUsingTargetsApi$2(PyDebugRunner.java:170)
at org.jetbrains.concurrency.Promises__PromiseKt$runAsync$1.run(promise.kt:213)
at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)
Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 1 failure: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 2 failure: Service returned error code InvalidGrantException (Service: SsoOidc, Status Code: 400, Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
```
