### ISSUE TITLE
 codewhisperer stopped:  Inlay operations are not supported for injected editors

### ISSUE THREAD

**Issue by zengLH1981** [aws/aws-toolkit-jetbrains#3665]
**Describe the bug**
I user codewhisperer  in idea-U 2023.1.
after some hours, the codewhisperer will stop, and it status like this
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/16136238/9d930343-c1a4-4efe-9995-9b11ba975de0)

and the IDE internal Errors show Exceptions
```
java.lang.Throwable: Inlay operations are not supported for injected editors
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.impl.source.tree.injected.InlayModelWindow.logUnsupported(InlayModelWindow.java:157)
	at com.intellij.psi.impl.source.tree.injected.InlayModelWindow.getInlineElementsInRange(InlayModelWindow.java:82)
	at com.intellij.openapi.editor.InlayModel.getInlineElementsInRange(InlayModel.java:139)
	at software.aws.toolkits.jetbrains.services.codewhisperer.inlay.CodeWhispererInlayManager.clearInlays(CodeWhispererInlayManager.kt:51)
	at software.aws.toolkits.jetbrains.services.codewhisperer.inlay.CodeWhispererInlayManager.updateInlays(CodeWhispererInlayManager.kt:16)
	at software.aws.toolkits.jetbrains.services.codewhisperer.popup.CodeWhispererUIChangeListener.stateChanged(CodeWhispererUIChangeListener.kt:86)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:680)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:640)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:415)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:394)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:454)
	at jdk.proxy7/jdk.proxy7.$Proxy263.stateChanged(Unknown Source)
	at software.aws.toolkits.jetbrains.services.codewhisperer.popup.CodeWhispererPopupManager.changeStates(CodeWhispererPopupManager.kt:173)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.updateCodeWhisperer(CodeWhispererService.kt:464)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.processCodeWhispererUI(CodeWhispererService.kt:377)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.access$processCodeWhispererUI(CodeWhispererService.kt:73)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService$invokeCodeWhispererInBackground$2$1.invoke(CodeWhispererService.kt:224)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService$invokeCodeWhispererInBackground$2$1.invoke(CodeWhispererService.kt:192)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:58)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

I need restart idea, and codewhisperer will reconnect.

**To reproduce**
I don't what operation make it

**Expected behavior**
 a

**Screenshots**
 a

**Your Environment**
- OS: Windows 10
- JetBrains product: idea-U 
- JetBrains product version: 2023.1
- AWS Toolkit version: 1.67-231
- SAM CLI version: i don't know
- JVM/Python version: maybe java-11

**Additional context**
a

**Comment by rli** [comment]
related: #3601

**Comment by andrewyuq** [comment]
Hi @zengLH1981 the fix for this is release in the latest version 1.69, please upgrade and try again. Thanks.
