### ISSUE TITLE
Cannot sync serverless app

### ISSUE THREAD

**Issue by magauthier-36pix** [aws/aws-toolkit-jetbrains#3709]
Having latest ide version (2023.1.2 (Community Edition))
Having latest toolkit version (1.68.231)
Having lates SAMCLI version (1.86.1)

Getting error when doing "Sync serverless application"

Error: Invalid sam executable: Traceback (most recent call last): File "runpy.py", line 194, in _run_module_as_main File "runpy.py", line 87, in _run_code File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in   cli(prog_name="sam") File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1054, in main with self.make_context(prog_name, args, **extra) as ctx: File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 920, in make_context self.parse_args(ctx, args) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1613, in parse_args rest = super().parse_args(ctx, args) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1378, in parse_args value, args = param.handle_parse_result(ctx, opts, args) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2360, in handle_parse_result value = self.process_value(ctx, value) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2322, in process_value value = self.callback(ctx, self, value) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 58, in print_info "additional_dependencies": gather_additional_dependencies_info(), File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 37, in gather_additional_dependencies_info "docker_engine": _gather_docker_info(), File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 60, in _gather_docker_info if is_docker_reachable(client): File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\utils.py", line 90, in is_docker_reachable docker_client.ping() File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 187, in ping return self.api.ping(*args, **kwargs) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\daemon.py", line 166, in ping return self._result(self._get(self._url('/_ping'))) == 'OK' File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\utils\decorators.py", line 46, in inner return f(self, *args, **kwargs) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 230, in _get return self.get(url, **self._set_request_timeout(kwargs)) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 602, in get return self.request("GET", url, **kwargs) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\adapters.py", line 486, in send resp = conn.urlopen( File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen response = self._make_request( File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request conn.request( TypeError: request() got an unexpected keyword argument 'chunked'. Click here to reconfigure AWS SAM.

**Comment by magauthier-36pix** [comment]
Every time there is a IDE update, a toolkit update or a SAMCLI update, we always have to cross our fingers hoping nothing breaks. This is very annoying.

**Comment by manodnyab** [comment]
Hi, based on the logs you have provided, this seems like a related issue: https://github.com/aws/aws-sam-cli/issues/5243. Following the comments there, looks like this bug is being fixed. Meanwhile, based off this: https://github.com/aws/aws-sam-cli/issues/5243#issuecomment-1581286826, can you please try downgrading the SAM CLI version to 1.84.0 and see if the issue persists?

**Comment by manodnyab** [comment]
Since v1.64, The toolkits provides the functionality to sync serverless applications(instead of deploy): https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/sam-sync.html. It runs the sync command for you once you've confirmed that you're using a development stack and selected the required parameters(stack, s3 bucket) for sync. Are you looking to execute the [sam deploy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html) command specifically?
