### ISSUE TITLE
CodeWhisperer does not work in `JetBrains Client` (Remote Development thin client)

### ISSUE THREAD

**Issue by rapphil** [aws/aws-toolkit-jetbrains#3775]
**Describe the bug**
When I try to use the AWS Toolkit with the Jetbrains Client and IntelliJ IDEA as remote backend, I'm getting the following error in the background when CodeWhisperer is activated:
```
ava.lang.NoClassDefFoundError: info/debatty/java/stringsimilarity/Levenshtein
	at software.aws.toolkits.jetbrains.services.codewhisperer.telemetry.CodeWhispererCodeCoverageTracker.<clinit>(CodeWhispererCodeCoverageTracker.kt:230)
	at software.aws.toolkits.jetbrains.services.codewhisperer.editor.CodeWhispererEditorListener$editorCreated$1$1$1.documentChanged(CodeWhispererEditorListener.kt:30)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$changedUpdate$2(DocumentImpl.java:922)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:919)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:823)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:664)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$setText$4(DocumentImpl.java:1091)
	at com.intellij.openapi.editor.impl.DocumentImpl.setText(DocumentImpl.java:1093)
	at com.jetbrains.rd.ide.document.PatchEngineDocumentSynchronizer.applyResetDocumentChange(PatchEngineDocumentSynchronizer.kt:173)
	at com.jetbrains.rd.ide.document.PatchEngineDocumentSynchronizer.applyChange(PatchEngineDocumentSynchronizer.kt:163)
	at com.jetbrains.rd.ide.document.PatchEngineDocumentSynchronizer.applyChangeCheckForce(PatchEngineDocumentSynchronizer.kt:153)
	at com.jetbrains.rd.ide.document.PatchEngineDocumentSynchronizer.receiveDocumentChange$lambda$5$lambda$4(PatchEngineDocumentSynchronizer.kt:128)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:368)
	at com.jetbrains.rd.ide.document.PatchEngineDocumentSynchronizer.receiveDocumentChange$lambda$5(PatchEngineDocumentSynchronizer.kt:127)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:956)
	at com.jetbrains.rd.ide.document.PatchEngineDocumentSynchronizer.receiveDocumentChange(PatchEngineDocumentSynchronizer.kt:121)
	at com.jetbrains.rdclient.requests.cwm.RdPatchUtilsKt.applyTo(RdPatchUtils.kt:41)
	at com.jetbrains.rdclient.requests.cwm.FrontendAsyncRequestExecutor.applyBackendPatch(FrontendAsyncRequestExecutor.kt:454)
	at com.jetbrains.rdclient.requests.cwm.FrontendAsyncRequestExecutor.applyBackendPatch$default(FrontendAsyncRequestExecutor.kt:440)
	at com.jetbrains.rdclient.requests.cwm.FrontendAsyncRequestExecutor.doBackendChanged(FrontendAsyncRequestExecutor.kt:378)
	at com.jetbrains.rdclient.requests.cwm.FrontendAsyncRequestExecutor.backendChanged(FrontendAsyncRequestExecutor.kt:358)
	at com.jetbrains.rdclient.requests.cwm.FrontendAsyncRequestExecutor.access$backendChanged(FrontendAsyncRequestExecutor.kt:63)
	at com.jetbrains.rdclient.requests.cwm.FrontendAsyncRequestExecutor$bindWithModel$2.invoke(FrontendAsyncRequestExecutor.kt:89)
	at com.jetbrains.rdclient.requests.cwm.FrontendAsyncRequestExecutor$bindWithModel$2.invoke(FrontendAsyncRequestExecutor.kt:89)
	at com.jetbrains.rd.framework.util.ISourceCoroutineUtilKt$adviseSuspend$1$1.invokeSuspend(ISourceCoroutineUtil.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.jetbrains.rd.framework.util.RdCoroutineScope.launch(RdCoroutineScope.kt:81)
	at com.jetbrains.rd.framework.util.LifetimeCoroutineUtilKt.launch(LifetimeCoroutineUtil.kt:42)
	at com.jetbrains.rd.framework.util.LifetimeCoroutineUtilKt.launch$default(LifetimeCoroutineUtil.kt:38)
	at com.jetbrains.rd.framework.util.ISourceCoroutineUtilKt$adviseSuspend$1.invoke(ISourceCoroutineUtil.kt:62)
	at com.jetbrains.rd.framework.util.ISourceCoroutineUtilKt$adviseSuspend$1.invoke(ISourceCoroutineUtil.kt:61)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.platform.codeWithMe.protocol.SecureWireOverStreamTransport$advise$wrapper$1.onWireReceived(SecureWireOverStreamTransport.kt:137)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:148)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:54)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:101)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAllRunnable$lambda$0(RdDispatcher.kt:25)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1444)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: info.debatty.java.stringsimilarity.Levenshtein PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit, id=aws.toolkit, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/JetBrainsClient231.9392.1/plugins/aws-toolkit-jetbrains, version=1.74-231, package=null, isBundled=false), packagePrefix=null, instanceId=13, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 92 more

```

What I did to circunvent the error and validate my hypothesis that some dependencies were missing in the classpath of the plugin was:
1. Download the plugin from https://plugins.jetbrains.com/plugin/11349-aws-toolkit/versions/stable/367952
2. Unzip it locally
3. Put the dependency https://github.com/tdebatty/java-string-similarity/releases/download/v2.0.0/java-string-similarity-2.0.0.jar in the `libs` directory. 
4. zip it again
5. Install plugin from disk using the zip from the previous step.

**To reproduce**
1. Open Project in IntellijClient with remote backend IntellijIDEA 2023.1.5
2. Try to trigger CodeWhisperer.

**Expected behavior**

No error in the background.

**Screenshots**

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/5030304/b75c59ae-bd75-4e58-98d8-fa9461fbcf3a)

**Your Environment**
- OS: MacOS X and Amazon Linux 2
- JetBrains product: IntelliJ Client and Remote IDE Intellij IDE 
- JetBrains product version: 2023.1.5
- AWS Toolkit version: 1.74-231
- SAM CLI version:
- JVM/Python version: JDK17

**Additional context**

**Comment by rli** [comment]
`Remote Development` is not a supported target for CodeWhisperer at the moment

**Comment by rapphil** [comment]
@rli this still does not change the fact that the CodeWhisperer plugin have dependency on java-string-similarity and it is not being included in the package. You are relying on a transitive dependency of the Intellij plugin system no?
