### ISSUE TITLE
Exception in plugin AWS Toolkit (1.75-231)

### ISSUE THREAD

**Issue by Ahmad-Sinch** [aws/aws-toolkit-jetbrains#3812]
**Describe the bug**
This plugin is not a production of JetBrains. Please report the problem to AWS.
Failed to set up software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory@7426ac2d

```
java.lang.IllegalArgumentException: profile 'staging' missing either property 'source_profile' or 'credential_source'
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileUtilsKt$traverseCredentialChain$1.invokeSuspend(ProfileUtils.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.requiresMfa(ProfileCredentialProviderFactory.kt:361)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.asId(ProfileCredentialProviderFactory.kt:295)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.loadProfiles(ProfileCredentialProviderFactory.kt:112)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileCredentialProviderFactory.setUp(ProfileCredentialProviderFactory.kt:86)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager$1$1.invoke(CredentialManager.kt:122)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager$1$1.invoke(CredentialManager.kt:121)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull(LogUtils.kt:21)
	at software.aws.toolkits.core.utils.LogUtilsKt.tryOrNull$default(LogUtils.kt:20)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultCredentialManager.<init>(CredentialManager.kt:121)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:54)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:714)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$Companion.getInstance(CredentialManager.kt:154)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultAwsConnectionManager$loadState$3$credentials$1.invoke(DefaultAwsConnectionManager.kt:55)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultAwsConnectionManager$loadState$3$credentials$1.invoke(DefaultAwsConnectionManager.kt:54)
	at software.aws.toolkits.core.utils.ExceptionUtils.tryOrNull(ExceptionUtils.kt:11)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultAwsConnectionManager$loadState$3.invokeSuspend(DefaultAwsConnectionManager.kt:54)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833) 
```

**To reproduce**
- Steps to reproduce the behavior: 
- 1. Go to 'IntelliJ IDEA CE' 
- 2. Add the AWS Toolkit plugin 
- 3. start using the app normally or just restart the app
- 4. See error

**Expected behavior**
The plugin should be trusted I think

**Screenshots**

**Your Environment**
- OS: MacOS 13.5 
- JetBrains product: IntelliJ IDEA CE
- JetBrains product version: IntelliJ IDEA 2023.1.5 (Community Edition)
- AWS Toolkit version: 1.75-231
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by justinmk3** [comment]
> java.lang.IllegalArgumentException: profile 'staging' missing either property 'source_profile' or 'credential_source'

What does your "staging" profile look like (after removing any secret info)?

**Comment by justinmk3** [comment]
Is that profile being referenced by another profile (e.g. an MFA profile)? If you remove or comment out (`# ...`) that profile, does the problem go away?
