### ISSUE TITLE
AWS Toolkit & IntelliJ Error

### ISSUE THREAD

**Issue by Ajris** [aws/aws-toolkit-jetbrains#3818]
**Describe the bug**

Error while running configuration with sso profile in intellij. 
Application works (I have connection to AWS, yet the error is being shown).

Stacktrace:
`java.lang.Throwable: Assertion failed: Network calls can't be made inside read/write action
	at software.aws.toolkits.core.utils.LogUtilsKt.assertTrue(LogUtils.kt:105)
	at software.aws.toolkits.jetbrains.core.AwsSdkClient$ValidateCorrectThreadClient.prepareRequest(AwsSdkClient.kt:46)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder$NonManagedSdkHttpClient.prepareRequest(SdkDefaultClientBuilder.java:538)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:68)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:196)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.sso.DefaultSsoClient.getRoleCredentials(DefaultSsoClient.java:132)
	at software.amazon.awssdk.services.sso.SsoClient.getRoleCredentials(SsoClient.java:152)
	at software.aws.toolkits.jetbrains.core.credentials.sso.SsoCredentialProvider.refreshCredentials(SsoCredentialProvider.kt:41)
	at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$8(CachedSupplier.java:300)
	at software.amazon.awssdk.utils.cache.CachedSupplier$PrefetchStrategy.fetch(CachedSupplier.java:448)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:208)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
	at software.aws.toolkits.jetbrains.core.credentials.sso.SsoCredentialProvider.resolveCredentials(SsoCredentialProvider.kt:33)
	at software.aws.toolkits.jetbrains.core.credentials.profiles.ProfileSsoProvider.resolveCredentials(ProfileSsoProvider.kt:47)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$AwsCredentialProviderProxy$resolveCredentials$1.invoke(CredentialManager.kt:74)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$AwsCredentialProviderProxy$resolveCredentials$1.invoke(CredentialManager.kt:73)
	at software.aws.toolkits.jetbrains.utils.ThreadingUtilsKt.runUnderProgressIfNeeded(ThreadingUtils.kt:30)
	at software.aws.toolkits.jetbrains.core.credentials.CredentialManager$AwsCredentialProviderProxy.resolveCredentials(CredentialManager.kt:73)
	at software.aws.toolkits.core.credentials.ToolkitCredentialsProvider.resolveCredentials(ToolkitCredentialsProvider.kt)
	at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension$addEnvironmentVariables$2.invoke(AwsConnectionExtension.kt:45)
	at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension$addEnvironmentVariables$2.invoke(AwsConnectionExtension.kt:43)
	at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension.injectCredentials(AwsConnectionExtension.kt:62)
	at software.aws.toolkits.jetbrains.core.execution.AwsConnectionRunConfigurationExtension.addEnvironmentVariables(AwsConnectionExtension.kt:43)
	at software.aws.toolkits.jetbrains.core.execution.JavaAwsConnectionExtension.updateJavaParameters(JavaAwsConnectionExtension.kt:36)
	at com.intellij.execution.RunConfigurationExtension.updateJavaParameters(RunConfigurationExtension.java:27)
	at com.intellij.execution.JavaRunConfigurationExtensionManager.updateJavaParameters(JavaRunConfigurationExtensionManager.kt:42)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.lambda$setupJavaParameters$0(BaseJavaApplicationCommandLineState.java:37)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:63)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.setupJavaParameters(BaseJavaApplicationCommandLineState.java:36)
	at com.intellij.execution.application.ApplicationCommandLineState.createJavaParameters(ApplicationCommandLineState.java:62)
	at com.intellij.spring.boot.run.SpringBootCommandLineState.createJavaParameters(SpringBootCommandLineState.java:46)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:41)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.patchJavaCommandLineParams(DefaultJavaProgramRunner.java:132)
	at com.intellij.execution.impl.DefaultJavaProgramRunner.lambda$doExecuteAsync$4(DefaultJavaProgramRunner.java:158)
	at com.intellij.execution.runners.ExecutionUtil.computeWithDataContext(ExecutionUtil.java:326)
	at com.intellij.execution.target.TargetEnvironmentAwareRunProfileState$1.run(TargetEnvironmentAwareRunProfileState.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**To reproduce**

Run any configuration in Intellij with AWS Toolkit with AWS Profile (SSO config).
Run it and see error.

**Expected behavior**
No errors.

**Screenshots**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/10548910/a0150455-a9e7-46a6-bc18-16c961a39de2)

**Your Environment**
- OS: Ubuntu 22.04
- JetBrains product: Intellij Ultimate
- JetBrains product version: 2023.02
- AWS Toolkit version: 1.75-232
- SAM CLI version: 1.94
- AWS CLI version: 2.9.10
- JVM version: 17.0.8
- Python version: 3.9.11

**Additional context**

**Comment by asaarela** [comment]
Same issue on OSX:

OS: Mac OS Monterey 12.6.8
Jetbrains product: IntelliJ Ultimate
Jetbrains product version: 2023.2.1
AWS Toolkit version: 1.77-232
JVM version: 17.0.8

**Comment by dwaynewilliams** [comment]
Same issue here:

IntelliJ IDEA 2022.3.3 (Community Edition)
Build #IC-223.8836.41, built on March 9, 2023
Runtime version: 17.0.6+1-b653.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
    net.seesharpsoft.intellij.plugins.csv (3.2.1-223)
    PythonCore (223.8836.26)
    aws.toolkit (1.78-223)

Kotlin: 223-1.8.0-release-345-IJ8836.41

**Comment by contentfree** [comment]
Well more than a year has gone by and still getting this issue. 

IntelliJ IDEA 2024.2.5 (Ultimate Edition)
Build #IU-242.24807.4, built on November 25, 2024
Runtime version: 21.0.5+13-b509.30 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.7.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
  org.jetbrains.plugins.haml (242.20224.175)
  net.coderazzi.aws_codeartifact_maven (4.0.2)
  aws.toolkit.core (3.49-242)
  com.nasller.CodeGlancePro (1.9.3)
  com.haulmont.jpab (242.22855.36)
  org.jetbrains.plugins.ruby (242.24807.4)
  net.seesharpsoft.intellij.plugins.csv (4.0.2)
  com.github.copilot (1.5.30-242)
  aws.toolkit (3.49-242)
Kotlin: 242.24807.4-IJ
