### ISSUE TITLE
NumberFormatException thrown when trying to use AWS functionality

### ISSUE THREAD

**Issue by noodanee** [aws/aws-toolkit-jetbrains#3845]
**Describe the bug**

Open the CodeWisperer: Add Connection to AWS modal, click 'Connect' button
Show error: Ran into unknown error: java.lang.NumberFormatException: For input string: ""

Trace: 
```
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:678)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at java.base/java.util.Optional.map(Optional.java:260)
	at software.amazon.awssdk.http.apache.ProxyConfiguration.resolvePort(ProxyConfiguration.java:216)
	at software.amazon.awssdk.http.apache.ProxyConfiguration.<init>(ProxyConfiguration.java:67)
	at software.amazon.awssdk.http.apache.ProxyConfiguration.<init>(ProxyConfiguration.java:37)
	at software.amazon.awssdk.http.apache.ProxyConfiguration$DefaultClientProxyConfigurationBuilder.build(ProxyConfiguration.java:409)
	at software.amazon.awssdk.http.apache.ProxyConfiguration$DefaultClientProxyConfigurationBuilder.build(ProxyConfiguration.java:300)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.<init>(ApacheHttpClient.java:458)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$DefaultBuilder.<init>(ApacheHttpClient.java:456)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.builder(ApacheHttpClient.java:131)
	at software.aws.toolkits.jetbrains.core.AwsSdkClient$sdkHttpClient$2.invoke(AwsSdkClient.kt:26)
	at software.aws.toolkits.jetbrains.core.AwsSdkClient$sdkHttpClient$2.invoke(AwsSdkClient.kt:24)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at software.aws.toolkits.jetbrains.core.AwsSdkClient.getSdkHttpClient(AwsSdkClient.kt:24)
	at software.aws.toolkits.jetbrains.core.AwsSdkClient.sharedSdkClient(AwsSdkClient.kt:35)
	at software.aws.toolkits.jetbrains.core.AwsClientManager.sdkHttpClient(AwsClientManager.kt:57)
	at software.aws.toolkits.core.ToolkitClientManager.constructAwsClient(ToolkitClientManager.kt:151)
	at software.aws.toolkits.core.ToolkitClientManager.constructAwsClient$default(ToolkitClientManager.kt:133)
	at software.aws.toolkits.core.ToolkitClientManager.createUnmanagedClient(ToolkitClientManager.kt:104)
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.BearerTokenProviderKt.buildUnmanagedSsoOidcClient(BearerTokenProvider.kt:247)
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.<init>(BearerTokenProvider.kt:90)
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.<init>(BearerTokenProvider.kt:81)
	at software.aws.toolkits.jetbrains.core.credentials.ManagedBearerSsoConnection.<init>(ToolkitConnectionImpls.kt:25)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultToolkitAuthManager.connectionFromProfile(DefaultToolkitAuthManager.kt:122)
	at software.aws.toolkits.jetbrains.core.credentials.DefaultToolkitAuthManager.createConnection(DefaultToolkitAuthManager.kt:39)
	at software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManagerKt.loginSso(ToolkitAuthManager.kt:159)
	at software.aws.toolkits.jetbrains.core.credentials.sono.SonoCredentialManager$getProviderAndPromptAuth$1.invoke(SonoCredentialManager.kt:72)
	at software.aws.toolkits.jetbrains.core.credentials.sono.SonoCredentialManager$getProviderAndPromptAuth$1.invoke(SonoCredentialManager.kt:71)
	at software.aws.toolkits.jetbrains.utils.ThreadingUtilsKt.runUnderProgressIfNeeded(ThreadingUtils.kt:30)
	at software.aws.toolkits.jetbrains.core.credentials.sono.SonoCredentialManager.getProviderAndPromptAuth(SonoCredentialManager.kt:71)
	at software.aws.toolkits.jetbrains.core.credentials.sono.SonoCredentialManager$Companion.loginSono(SonoCredentialManager.kt:87)
	at software.aws.toolkits.jetbrains.core.explorer.devToolsTab.nodes.actions.SonoLogin.actionPerformed$lambda$0(SonoLogin.kt:16)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
**Screenshots**

![Export-1693534430046](https://github.com/aws/aws-toolkit-jetbrains/assets/16449385/c75a1e12-1745-4031-ab94-123afd29dd23)

**Your Environment**
- JetBrains product version:
Intellij IDEA 2023.2.1
Runtime version: 17.0.8+7-b1000.8 aarch64
- AWS Toolkit version: 1.77-232

**Comment by rli** [comment]
I don't know how this would happen, but your IDE system properties has `http.proxyPort` set to empty string.
