### ISSUE TITLE
Plugin crashes on IntelliJ startup. Attaching the stacktrace

### ISSUE THREAD

**Issue by mh-agi** [aws/aws-toolkit-jetbrains#3946]
com.intellij.diagnostic.PluginException: Cannot init component state (componentName=codewhispererStates, componentClass=CodeWhispererExplorerActionManager) [Plugin: aws.toolkit]
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:148)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:46)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:622)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:154)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance$lambda$1(BaseComponentAdapter.kt:133)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:132)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:714)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at software.aws.toolkits.jetbrains.services.codewhisperer.explorer.CodeWhispererExplorerActionManager$Companion.getInstance(CodeWhispererExplorerActionManager.kt:207)
	at software.aws.toolkits.jetbrains.services.codewhisperer.explorer.CodeWhispererExplorerActionManagerKt.isCodeWhispererEnabled(CodeWhispererExplorerActionManager.kt:198)
	at software.aws.toolkits.jetbrains.services.codewhisperer.toolwindow.CodeWhispererCodeReferenceToolWindowFactory.shouldBeAvailable(CodeWhispererCodeReferenceToolWindowFactory.kt:25)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:264)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:250)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.invoke(ToolWindowSetInitializer.kt:279)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.invoke(ToolWindowSetInitializer.kt:275)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans$lambda$0(ToolWindowSetInitializer.kt:275)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:299)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:275)
	at com.intellij.openapi.project.impl.ProjectFrameAllocatorKt$initFrame$1$taskListDeferred$1.invokeSuspend(ProjectFrameAllocator.kt:365)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.util.xmlb.XmlSerializationException: Cannot deserialize class software.aws.toolkits.jetbrains.services.codewhisperer.explorer.CodeWhispererExploreActionState
	at com.intellij.configurationStore.JdomSerializerImpl.deserialize(xmlSerializer.kt:99)
	at com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:29)
	at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:34)
	at com.intellij.configurationStore.StateGetterImpl.getState(StorageBaseEx.kt:56)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:417)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:368)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:119)
	... 29 more
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.serialization.stateProperties.MyMap.put, parameter key
	at com.intellij.serialization.stateProperties.MyMap.put(MapStoredProperty.kt)
	at com.intellij.util.xmlb.MapBinding.deserialize(MapBinding.java:241)
	at com.intellij.util.xmlb.MapBinding.deserializeList(MapBinding.java:168)
	at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:25)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:108)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:54)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:241)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:199)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:142)
	at com.intellij.configurationStore.JdomSerializerImpl.deserialize(xmlSerializer.kt:93)
	... 35 more

**Comment by andrewyuq** [comment]
When you say "crash" do you mean the IDE is not launching?

**Comment by leigaol** [comment]
Could you try install the latest plugin? This issue should have been fixed in the latest release.
