### ISSUE TITLE
Exception in aws toolkit(1.86-EAP.2023.11.03-232).

### ISSUE THREAD

**Issue by NehaAnthony** [aws/aws-toolkit-jetbrains#3970]
Exception is occuring  while running a code- Exception in thread "main" java.lang.IllegalArgumentException: Invalid option: software.amazon.awssdk.awscore.client.config.AwsClientOption@44e81672. Required value of type interface software.amazon.awssdk.identity.spi.IdentityProvider, but was class software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider.

at software.amazon.awssdk.utils.Validate.isAssignableFrom(Validate.java:609)

at software.amazon.awssdk.utils.AttributeMap$Key.validateValue(AttributeMap.java:130)

at software.amazon.awssdk.utils.AttributeMap$Key.convertValue(AttributeMap.java:140)

at software.amazon.awssdk.utils.AttributeMap.get(AttributeMap.java:61)

at software.amazon.awssdk.core.client.config.SdkClientConfiguration.option(SdkClientConfiguration.java:55)

at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveCredentialsIdentityProvider(AwsDefaultClientBuilder.java:374)

at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:196)

at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:185)

at software.amazon.awssdk.services.textract.DefaultTextractClientBuilder.buildClient(DefaultTextractClientBuilder.java:39)

at software.amazon.awssdk.services.textract.DefaultTextractClientBuilder.buildClient(DefaultTextractClientBuilder.java:27)

at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:152)

at cell.main(cell.java:47)

Process finished with exit code 1

aws configure on terminal  showing error-unable to parse config file.

**Comment by rli** [comment]
This does not appear to be coming from the toolkit.
Can you confirm that all your project dependencies have the same AWS SDK version?

https://github.com/aws/aws-sdk-java-v2/discussions/4609

**Comment by NehaAnthony** [comment]
hello,
            yes all projects dependencies have same version. I am unable to
run my code previously everything was fine.
Please help to resolve this issue soon.

    Yours sincerely
Neha Anthony
