### ISSUE TITLE
Unable to download Amazon Q Transform diff

### ISSUE THREAD

**Issue by thisisrobkerry** [aws/aws-toolkit-jetbrains#4075]
After running an Amazon Q trasform from Java 11 to 17 on a project, I am unable to download and view the diff of the changes made. 

I get the below stacktrace:
```
Unhandled exception in [CoroutineName(software.aws.toolkits.jetbrains.services.codemodernizer.ArtifactHandler), StandaloneCoroutine{Cancelling}@46f0e330, com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor@56bb303[Running, pool size = 9, active threads = 2, queued tasks = 0, completed tasks = 53854371]]

software.amazon.awssdk.services.codewhispererstreaming.model.InternalServerException: Encountered an unexpected error when processing the request, please try again. (Service: CodeWhispererStreaming, Status Code: 500, Request ID: 512a98e0-6806-4640-8df5-d254187cab39)
	at software.amazon.awssdk.services.codewhispererstreaming.model.InternalServerException$BuilderImpl.build(InternalServerException.java:124)
	at software.amazon.awssdk.services.codewhispererstreaming.model.InternalServerException$BuilderImpl.build(InternalServerException.java:78)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:92)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:66)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:41)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:63)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:89)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:132)
	at software.amazon.awssdk.utils.async.SimplePublisher.doProcessQueue(SimplePublisher.java:275)
	at software.amazon.awssdk.utils.async.SimplePublisher.processEventQueue(SimplePublisher.java:224)
	at software.amazon.awssdk.utils.async.SimplePublisher.complete(SimplePublisher.java:157)
	at software.amazon.awssdk.http.crt.internal.response.CrtResponseAdapter.onSuccessfulResponseComplete(CrtResponseAdapter.java:113)
	at software.amazon.awssdk.http.crt.internal.response.CrtResponseAdapter.onResponseComplete(CrtResponseAdapter.java:106)
	at software.amazon.awssdk.crt.http.HttpStreamResponseHandlerNativeAdapter.onResponseComplete(HttpStreamResponseHandlerNativeAdapter.java:58)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(software.aws.toolkits.jetbrains.services.codemodernizer.ArtifactHandler), StandaloneCoroutine{Cancelled}@46f0e330, com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor@56bb303[Running, pool size = 7, active threads = 1, queued tasks = 0, completed tasks = 53900219]]
```
---
Toolkit: AWS Toolkit For JetBrains 2.2-233
OS: Mac OS X 14.2
IDE: IntelliJ IDEA Ultimate Edition 233

**Comment by robkerrybjss** [comment]
I raised this as a support case through the AWS console also and was told that there's currently a 100MB limit on diffs to be downloaded. This is being increased soon.
