### ISSUE TITLE
Amazon Q chat raise an issue when asking anything (Improperly formed request)

### ISSUE THREAD

**Issue by mbarbin-groupeseb** [aws/aws-toolkit-jetbrains#4114]
**Describe the bug**
After logging with my AWS credentials I can't use Amazon Q chat.
The chat open correctly and I can use actions like "right click > send to Amazon Q > explain code" but it keeps telling me that an error Occured.

The chat seems to trigger a request failing with a 400 http status code :

```
An error occurred while processing your request. This error is reported to the team automatically. We will attempt to fix it as soon as possible.

Details: Improperly formed request. (Service: CodeWhispererRuntime, Status Code: 400, Request ID: 7f44ec3a-f042-44ee-9f04-6a440737424b)

Session ID: null
```

**To reproduce**
1. Open Amazon Q chat
2. Say hello or ask a question
3. Amazon Q chat display an issue

**Expected behavior**
Amazon Q chat respond correctly without raising an issue.

**Screenshots**

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/83591418/f28b2cc1-59b7-4ac6-a538-257822028849)

**Your Environment**
- OS: Windows
- JetBrains product: IntelliJ IDEA 2023.3.2 (Ultimate Edition)
- JetBrains product version: Build #IU-233.13135.103, built on December 20, 2023
- AWS Toolkit version: 2.4-233

**Additional context**
I had the same issue on previous versions of IntelliJ, thinking it was due to my older version I upgraded until I was up-to-date

**Comment by ashleydaley** [comment]
I am getting this same issue, latest version of toolkit, rendering it completely useless right now for me

**Comment by mbarbin-groupeseb** [comment]
I upgraded to latest version of Intellij / toolkit plugin and as you say, still useless :(
Latest environment test : 

- OS: Windows
- JetBrain product: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
- JetBrains product version: Build #IU-233.14015.106
- AWS Toolkit version: 2.5-233

**Comment by achdmbp** [comment]
this happened to me as using `AWS Toolkit ` v2.11.0 on VS Code. I was able to resolve it by `Sign out` from 3 dots on top right of Amazon Q chat, then re-login again.

**Comment by chenxuanzzy** [comment]
I also have the same issue.
OS: Darwin arm64 22.6.0
Visual Studio Code extension host:  1.87.0
AWS Toolkit:  2.12.0
node: 18.17.1
electron: 27.3.2

I use the IAM Identity account still have same problem

**Comment by rustermi** [comment]
Same:
* OS: macOS Sequoia 15.2
* JetBrains product: IntelliJ IDEA 2024.3.1.1 (Ultimate Edition)
* JetBrains product version: Build #IU-243.22562.218, built on December 18, 2024

Signing out and back in didn't work. Yesterday it was working.

**Comment by deki** [comment]
Same issue here with latest versions
```

2025-05-09 21:26:18,593 [24929391]   INFO - software.aws.toolkits.jetbrains.services.cwc.clients.chat.v1.ChatSessionV1 - Request from tab: c44fcf5e-4520-4975-a92e-0e864feeb5c5, conversationId: null, request: GenerateAssistantResponseRequest(ConversationState=ConversationState(CurrentMessage=ChatMessage(UserInputMessage=UserInputMessage(Content=*** Sensitive Data Redacted ***, UserInputMessageContext=UserInputMessageContext(EditorState=EditorState(Document=TextDocument(RelativeFilePath=*** Sensitive Data Redacted ***, Text=*** Sensitive Data Redacted ***, DocumentSymbols=[]), CursorState=CursorState(Range=Range(Start=Position(Line=27, Character=0), End=Position(Line=46, Character=53))), RelevantDocuments=[], UseRelevantDocuments=false, WorkspaceFolders=*** Sensitive Data Redacted ***)))), ChatTriggerType=INLINE_CHAT), ProfileArn=arn:aws:codewhisperer:us-east-1:724904587780:profile/KGGD9MM7EMNX)
2025-05-09 21:26:20,618 [24931416]   INFO - software.aws.toolkits.jetbrains.services.cwc.clients.chat.v1.ChatSessionV1 - Response to tab: c44fcf5e-4520-4975-a92e-0e864feeb5c5, conversationId: 9aba08e0-34fc-4bac-88b6-312447c80844, requestId: 39bb47ad-38ea-4608-9023-b4008d6f5237, metadata: AwsResponseMetadata(metadata=[AWS_REQUEST_ID, x-amzn-RequestId, :content-type, :event-type, :message-type])
2025-05-09 21:26:37,431 [24948229] SEVERE - #c.i.o.a.i.ApplicationImpl - Improperly formed request. (Service: CodeWhispererRuntime, Status Code: 400, Request ID: 839dbbaa-c7df-41d5-a271-d2f220338515)
software.amazon.awssdk.services.codewhispererruntime.model.ValidationException: Improperly formed request. (Service: CodeWhispererRuntime, Status Code: 400, Request ID: 839dbbaa-c7df-41d5-a271-d2f220338515)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:55)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.executeRequest(RetryableStage2.java:93)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.execute(RetryableStage2.java:56)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage2.execute(RetryableStage2.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:53)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:35)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:32)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:210)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:173)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:80)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
	at software.amazon.awssdk.services.codewhispererruntime.DefaultCodeWhispererRuntimeClient.sendTelemetryEvent(DefaultCodeWhispererRuntimeClient.java:1296)
	at software.amazon.awssdk.services.codewhispererruntime.CodeWhispererRuntimeClient.sendTelemetryEvent(CodeWhispererRuntimeClient.java:2262)
	at software.aws.toolkits.jetbrains.services.codewhisperer.credentials.CodeWhispererClientAdaptorImpl.sendInlineChatTelemetry(CodeWhispererClientAdaptor.kt:799)
	at software.aws.toolkits.jetbrains.services.cwc.controller.chat.telemetry.TelemetryHelper.recordInlineChatTelemetry(TelemetryHelper.kt:166)
	at software.aws.toolkits.jetbrains.services.cwc.inline.InlineChatController.recordInlineChatTelemetry(InlineChatController.kt:157)
	at software.aws.toolkits.jetbrains.services.cwc.inline.InlineChatController.diffRejectHandler$lambda$6$lambda$5(InlineChatController.kt:200)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.lambda$call$1(ContextCallable.java:86)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:102)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:102)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:108)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:102)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-05-09 21:26:37,432 [24948230] SEVERE - #c.i.o.a.i.ApplicationImpl - IntelliJ IDEA 2025.1.1  Build #IU-251.25410.109
2025-05-09 21:26:37,432 [24948230] SEVERE - #c.i.o.a.i.ApplicationImpl - JDK: 21.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2025-05-09 21:26:37,432 [24948230] SEVERE - #c.i.o.a.i.ApplicationImpl - OS: Mac OS X
2025-05-09 21:26:37,432 [24948230] SEVERE - #c.i.o.a.i.ApplicationImpl - Plugin to blame: AWS Core version: 3.70-251
2025-05-09 21:26:37,432 [24948230] SEVERE - #c.i.o.a.i.ApplicationImpl - Last Action: EditorBackSpace
```

**Comment by aseemxs** [comment]
Please upgrade to the latest version and try again, let us know if the issue still persists.
