### ISSUE TITLE
com.intellij.diagnostic.PluginException: Created extension classloader is not equal to plugin's one.

### ISSUE THREAD

**Issue by mistu4u** [aws/aws-toolkit-jetbrains#4251]
**Describe the bug**

Everyday as soon as I open my Intellij Idea, within a few minutes, I see the bug appearing.

Pls find below the stacktrace:

```
com.intellij.diagnostic.PluginException: Created extension classloader is not equal to plugin's one.
See https://youtrack.jetbrains.com/articles/IDEA-A-65/Plugin-Model#internalignoredependencyviolation
(
  className=software.aws.toolkits.jetbrains.core.help.HelpIdTranslator,
  extensionInstanceClassloader=PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit - Amazon Q, CodeWhisperer, and more, id=aws.toolkit, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\aws-toolkit-jetbrains, version=2.17-233, package=null, isBundled=false), packagePrefix=null, state=active),
  pluginClassloader=PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit - Amazon Q, CodeWhisperer, and more, id=aws.toolkit, moduleName=aws.toolkit.core, descriptorPath=aws.toolkit.core.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\aws-toolkit-jetbrains, version=2.17-233, package=aws.toolkit.core, isBundled=false), packagePrefix=aws.toolkit.core., state=active)
)
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1465)
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:93)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:32)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:50)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:32)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:468)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:416)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:267)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.kt:41)
	at com.intellij.help.impl.HelpManagerImpl.getHelpUrl(HelpManagerImpl.java:31)
	at com.intellij.codeInsight.javadoc.AnnotationDocGenerator.generateAnnotation(AnnotationDocGenerator.java:178)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateAnnotations(JavaDocInfoGenerator.java:1381)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateVariableDefinition(JavaDocInfoGenerator.java:1403)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateMethodParameterJavaDoc(JavaDocInfoGenerator.java:1419)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfoCore(JavaDocInfoGenerator.java:551)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfo(JavaDocInfoGenerator.java:668)
	at com.intellij.lang.java.JavaDocumentationProvider.generateExternalJavadoc(JavaDocumentationProvider.java:893)
	at com.intellij.lang.java.JavaDocumentationProvider.generateExternalJavadoc(JavaDocumentationProvider.java:882)
	at com.intellij.lang.java.JavaDocumentationProvider.generateExternalJavadoc(JavaDocumentationProvider.java:876)
	at com.intellij.lang.java.JavaDocumentationProvider.generateDoc(JavaDocumentationProvider.java:801)
	at com.intellij.codeInsight.documentation.QuickDocUtil.inferLinkFromFullDocumentation(QuickDocUtil.java:92)
	at com.intellij.lang.java.JavaDocumentationProvider.getQuickNavigateInfo(JavaDocumentationProvider.java:113)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.getQuickNavigateInfo(CompositeDocumentationProvider.java:111)
	at com.intellij.codeInsight.navigation.SingleTargetElementInfo.generateInfo(SingleTargetElementInfo.java:28)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentationHint(PsiElementDocumentationTarget.kt:73)
	at com.intellij.codeInsight.navigation.CtrlMouseDataKt.targetCtrlMouseData(CtrlMouseData.kt:101)
	at com.intellij.codeInsight.navigation.CtrlMouseDataKt.symbolCtrlMouseData(CtrlMouseData.kt:55)
	at com.intellij.codeInsight.navigation.impl.CtrlMouseKt.ctrlMouseData(ctrlMouse.kt:25)
	at com.intellij.codeInsight.navigation.impl.TargetGTDActionData.ctrlMouseData(gtd.kt:55)
	at com.intellij.codeInsight.navigation.impl.GtduKt$toGTDUActionData$1.ctrlMouseData(gtdu.kt:67)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationOrUsageHandler2.getCtrlMouseData(GotoDeclarationOrUsageHandler2.kt:39)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.getCtrlMouseData(GotoDeclarationAction.java:84)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$computeInReadAction$1.invoke(CtrlMouseHandler.kt:235)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$computeInReadAction$1.invoke(CtrlMouseHandler.kt:234)
	at com.intellij.lang.documentation.ide.impl.DocumentationTargetHoverInfoKt.injectedThenHost(DocumentationTargetHoverInfo.kt:76)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2.computeInReadAction(CtrlMouseHandler.kt:234)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2.access$computeInReadAction(CtrlMouseHandler.kt:74)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2$1.invoke(CtrlMouseHandler.kt:220)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2$1.invoke(CtrlMouseHandler.kt:219)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:310)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:40)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler2$compute$2.invokeSuspend(CtrlMouseHandler.kt:219)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)


```
**To reproduce**
As soon as I open the Intellij Idea editor, I see the error message.

**Expected behavior**
No error should come up.

**Screenshots**
<img width="614" alt="image" src="https://github.com/aws/aws-toolkit-jetbrains/assets/41926114/7dff16d4-ad9c-400f-9ddf-6ef80422b685">

**Your Environment**
- OS: Windows 11 Pro 64 bit (10.0 Build 22000)
- JetBrains product: Intellij Idea
- JetBrains product version: 2023.3.6 (Ultimate Edition)
- AWS Toolkit version: 2.17-233
- JVM/Python version: openjdk 11.0.21 2023-10-17

**Comment by Daniels1610** [comment]
Hello @mistu4u , I have the same problem, have you figured out something?
