### ISSUE TITLE
WARN - software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager - Failed to switch to profile 'Profile:gm-sandbox'

### ISSUE THREAD

**Issue by jkhalaf-gr** [aws/aws-toolkit-jetbrains#4498]
**Describe the bug**

My `~/.aws/config` looks like this:

```
[profile default]
region = eu-west-2
output = json
sso_start_url = https://<some-name>.awsapps.com/start#/
sso_region = eu-west-1
sso_account_id = <some-number>
sso_role_name = ABSandboxAccess

[profile ab-dev]
region = eu-west-2
output = json
sso_start_url = https://<some-name>.awsapps.com/start#/
sso_region = eu-west-1
sso_account_id = <some-number>
sso_role_name = ABCoreServicesDevAccess

[profile ab-test]
region = eu-west-2
output = json
sso_start_url = https://<some-name>.awsapps.com/start#/
sso_region = eu-west-1
sso_account_id = <some-number>
sso_role_name = ABCoreServicesTestAccess

[profile ab-prod]
region = eu-west-2
output = json
sso_start_url = https://<some-name>.awsapps.com/start#/
sso_region = eu-west-1
sso_account_id = <some-number>
sso_role_name = ABBankingSupportAccess

[profile dc-dev]
sso_start_url = https://<some-name>.awsapps.com/start/
sso_region = us-east-1
sso_account_id = <some-number>
sso_role_name = AdministratorAccess
region = eu-west-2
output = json
cli_pager =

[profile dc-test]
sso_start_url = https://<some-name>.awsapps.com/start/
sso_region = us-east-1
sso_account_id = <some-number>
sso_role_name = AdministratorAccess
region = eu-west-2
output = json
cli_pager =

[profile dc-qa]
sso_start_url = https://<some-name>.awsapps.com/start/
sso_region = us-east-1
sso_account_id = <some-number>
sso_role_name = AdministratorAccess
region = eu-west-2
output = json
cli_pager =

[profile dc-prod]
sso_start_url = https://<some-name>.awsapps.com/start/
sso_region = us-east-1
sso_account_id = <some-number>
sso_role_name = AdministratorAccess
region = eu-west-2
output = json
cli_pager =

[profile gm-sandbox]
sso_session = gm-sso
sso_account_id = <some-number>
sso_role_name = administrator_access
region = eu-west-2
output = json

[sso-session gm-sso]
sso_start_url = https://<some-name>.awsapps.com/start
sso_region = eu-west-2
sso_registration_scopes = sso:account:access
```

**To reproduce**

I open JetBrains Rider, and authenticate here:

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/168232979/7a244db2-7515-486e-ab49-94926ec0ddeb)

A browser opens, I authenticate, then it tells me to close the browser.

When I debug my solution, I get the following error:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'Options property cannot be empty: ClientName')
   at Amazon.Runtime.Credentials.Internal.SSOTokenManager.GenerateNewTokenAsync(SSOTokenManagerGetTokenOptions options, CancellationToken cancellationToken)
   at Amazon.Runtime.Credentials.Internal.SSOTokenManager.GetTokenAsync(SSOTokenManagerGetTokenOptions options, CancellationToken cancellationToken)
   at Amazon.Runtime.SSOAWSCredentials.GetSsoCredentialsAsync(ICoreAmazonSSO sso)
   at Amazon.Runtime.SSOAWSCredentials.GenerateNewCredentialsAsync()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Core.Features.Login.LoginHandler.Handle(LoginCommand request, CancellationToken cancellationToken) in /home/j/code/gm/app/Core/Features/Login/LoginController.cs:line 111
```

Google tells me that error is due to AWS Config not loading.

When I view the logs for Rider, I see:

```
56773-2024-05-21 21:04:31,013 [  17046]   INFO - migration.software.aws.toolkits.jetbrains.core.credentials.ToolkitAuthManager - Token provider NOT_AUTHENTICATED, requesting login
56774-2024-05-21 21:04:31,017 [  17050]   WARN - software.aws.toolkits.jetbrains.core.credentials.pinning.CodeCatalystConnection - Rejecting sso-session:gm-sso since it's missing a required scope
56775-2024-05-21 21:04:31,017 [  17050]   WARN - software.aws.toolkits.jetbrains.core.credentials.pinning.CodeCatalystConnection - Rejecting AwsConnectionManagerConnection since it's not a bearer connection
56776:2024-05-21 21:04:31,021 [  17054]   WARN - software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager - Failed to switch to profile 'Profile:gm-sandbox'
56777-java.util.concurrent.ExecutionException: software.aws.toolkits.jetbrains.core.credentials.sso.bearer.NoTokenInitializedException: Token refresh started before session initialized
```

**Expected behavior**

I expect the AWS config to load and things to work.

**Your Environment**
- OS: Arch Linux
- JetBrains product: Rider
- JetBrains product version: JetBrains Rider 2024.1.2 Build #RD-241.15989.179, built on May 6, 2024
- AWS Toolkit version: aws-cli/2.15.55 Python/3.11.8 Linux/6.9.1-arch1-1 exe/x86_64.arch

**Additional context**

When I run my solution in the terminal, things work fine:

```
export AWS_PROFILE="gm-sandbox";
```
```
aws sso login --profile gm-sandbox
```
```
dotnet run -lp https --project Core
```

**Comment by chriseqipe** [comment]
I'v seen exactly the same.

**Comment by kriehzoo** [comment]
similar issue here:

2024-07-03 16:53:46,889 [ 121297]   WARN - software.aws.toolkits.jetbrains.core.credentials.AwsConnectionManager - Failed to switch to profile 'Profile:PowerUserAccess-8xxxxxxxxxxxx'
java.util.concurrent.ExecutionException: software.aws.toolkits.jetbrains.core.credentials.sso.bearer.NoTokenInitializedException: Token refresh started before session initialized


Caused by: software.aws.toolkits.jetbrains.core.credentials.sso.bearer.NoTokenInitializedException: Token refresh started before session initialized
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.refreshToken(BearerTokenProvider.kt:140)
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.supplier$lambda$0(BearerTokenProvider.kt:111)
	at software.amazon.awssdk.utils.cache.CachedSupplier.lambda$jitteredPrefetchValueSupplier$8(CachedSupplier.java:300)
	at software.amazon.awssdk.utils.cache.NonBlocking.fetch(NonBlocking.java:151)
	at software.amazon.awssdk.utils.cache.CachedSupplier.refreshCache(CachedSupplier.java:208)
	at software.amazon.awssdk.utils.cache.CachedSupplier.get(CachedSupplier.java:135)
	at software.aws.toolkits.jetbrains.core.credentials.sso.bearer.InteractiveBearerTokenProvider.resolveToken(BearerTokenProvider.kt:153)

**Comment by kriehzoo** [comment]
but for me in the browser I see one of the following:

- request denied
- 404
