### ISSUE TITLE
IDE stuck on infinite restart loop due to PluginVersionChecker

### ISSUE THREAD

**Issue by lj-replicate** [aws/aws-toolkit-jetbrains#4519]
**Describe the bug**
We have seen some users reported that their IDEs  stuck on infinite restart loop.
See full list here:
https://youtrack.jetbrains.com/issues?q=%22software.aws.toolkits.jetbrains.PluginVersionChecker.execute%22

**To reproduce**
1. Have AWS Toolkit and AWS Core plugin installed with different versions.
2. Start the IDE.

**Expected behavior**
IDE starts fine.

**Actual behavior**
IDE stuck on infinite restart loop.
From the log (attched below), I saw some problems:
1. It seems the `AWS Toolkit` is already disabled but the IDE still tried to disable it and restart the IDE.
2. "Do not call invokeLater when app is not yet fully initialized" exception from PluginVersionChecker.execute. The `PluginVersionChecker` uses `ApplicationInitializedListener` and the later one is an internal API. Switching to `ProjectActivity` or `AppLifecycleListener` might be better.

**Your Environment**
- OS: Windows
- JetBrains product: IntelliJ IDEA Community 2024.1
- JetBrains product version: IU-241.17011.79
- AWS Toolkit version: 2.17-241
- SAM CLI version: -
- JVM/Python version: -

**Additional context**
Logs:
```
2024-05-26 12:00:57,863 [      4]   INFO - #c.i.p.i.b.AppStarter - ------------------------------------------------------ IDE STARTED ------------------------------------------------------
....
2024-05-26 12:00:57,964 [    105]   INFO - #c.i.p.i.b.AppStarter - JNA library (64-bit) loaded in 38 ms
2024-05-26 12:00:57,965 [    106]   INFO - #c.i.u.i.PageCacheUtils - File page caching params:
2024-05-26 12:00:57,966 [    107]   INFO - #c.i.p.i.b.AppStarter - IDE: IntelliJ IDEA (build #IU-241.17011.79, Wed, 22 May 2024 05:24:00 GMT)
...
2024-05-26 12:00:58,024 [    165]   INFO - #c.i.i.p.PluginManager - Loaded custom plugins: .... AWS Core (3.5-241)
2024-05-26 12:00:58,025 [    166]   INFO - #c.i.i.p.PluginManager - Disabled plugins: .... AWS Toolkit - Amazon Q, CodeWhisperer, and more (2.17-241)
...
2024-05-26 12:00:58,139 [    280]   INFO - software.aws.toolkits.jetbrains.PluginVersionChecker - Mismatch between core version: 3.5-241 and plugins: [PluginInfo(id=aws.toolkit, name=AWS Toolkit)]
2024-05-26 12:00:58,166 [    307]   INFO - software.aws.toolkits.jetbrains.core.plugin.PluginUpdateManager - AWS Toolkit - Amazon Q, CodeWhisperer, and more is disabled, not performing auto-update
2024-05-26 12:00:58,166 [    307]   INFO - software.aws.toolkits.jetbrains.PluginVersionChecker - Attempting to disable aws.toolkit due to known incompatibility
2024-05-26 12:00:58,166 [    307]   INFO - #c.i.i.p.DisabledPluginsState - Plugins to disable: [aws.toolkit]
2024-05-26 12:00:58,167 [    308]   INFO - software.aws.toolkits.jetbrains.PluginVersionChecker - Restarting due to forced update of plugins
2024-05-26 12:00:58,168 [    309] SEVERE - #c.i.o.a.i.ApplicationImpl - Do not call invokeLater when app is not yet fully initialized
java.lang.Throwable: Do not call invokeLater when app is not yet fully initialized
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:274)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:539)
	at com.intellij.openapi.application.impl.ApplicationImpl.restart(ApplicationImpl.java:515)
	at com.intellij.openapi.application.impl.ApplicationImpl.restart(ApplicationImpl.java:485)
	at com.intellij.openapi.application.impl.ApplicationImpl.restart(ApplicationImpl.java:473)
	at software.aws.toolkits.jetbrains.PluginVersionChecker.execute(PluginVersionChecker.kt:66)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$callAppInitialized$1.invokeSuspend(ApplicationLoader.kt:570)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by lj-replicate** [comment]
There are 5 users reporting this issue in Intellij issue tracker so this issues seems a critical one.
