### ISSUE TITLE
Cannot open files from S3 Explorer by double clicking and no right-click context menu

### ISSUE THREAD

**Issue by tsposato** [aws/aws-toolkit-jetbrains#4705]
**Describe the bug**
Open the AWS Toolkit Explorer, Go to any S3 bucket and try and open a file by double clicking, or right-click any file.

**To reproduce**
As above
I can't right-click context menu any file, but I can download and select/delete them.

**Expected behavior**
The file will open in the IDE

**Screenshots**

**Your Environment**
**- OS:** Microsoft Windows 11 Pro
**- JetBrains product:** IntelliJ IDEA 2024.1.4 (Ultimate Edition)
**- JetBrains product version:** Build #IU-241.18034.62, built on June 21, 2024
**- AWS Toolkit version:** 3.18-241
**- SAM CLI version:** N/A
**- JVM/Python version:** OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)

**Additional context**
I've tried restarting the application, and re-installing the AWS Toolket plugin and resetting any settings.
Relevant logs from idea.log:
2024-07-22 08:54:46,943 [    520] SEVERE - #c.i.o.a.i.ActionManagerImpl - Cannot resolve resource bundle software.aws.toolkits.resources.MessagesBundle for action XmlElement(name=action, attributes={class=software.aws.toolkits.jetbrains.ui.feedback.ShowFeedbackDialogAction, id=aws.toolkit.showFeedback}, children=[], content=null) [Plugin: aws.toolkit]
com.intellij.diagnostic.PluginException: Cannot resolve resource bundle software.aws.toolkits.resources.MessagesBundle for action XmlElement(name=action, attributes={class=software.aws.toolkits.jetbrains.ui.feedback.ShowFeedbackDialogAction, id=aws.toolkit.showFeedback}, children=[], content=null) [Plugin: aws.toolkit]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.kt:371)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doRegisterActions(ActionManagerImpl.kt:243)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.kt:130)
	at com.jetbrains.rdserver.ui.actionPopupMenu.BackendActionManager.<init>(BackendActionManager.kt:17)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:49)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:42)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:308)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:42)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:31)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:83)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:68)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:702)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$preloadNonHeadlessServices$2$5.invokeSuspend(ApplicationLoader.kt:586)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.util.MissingResourceException: Can't find bundle for base name software.aws.toolkits.resources.MessagesBundle, locale en_AU
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:1280)
	at com.intellij.AbstractBundle.resolveResourceBundleWithFallback(AbstractBundle.java:162)
	at com.intellij.DynamicBundle.resolveResourceBundle(DynamicBundle.java:291)
	at com.intellij.DynamicBundle.lambda$getResourceBundle$2(DynamicBundle.java:275)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at com.intellij.DynamicBundle.getResourceBundle(DynamicBundle.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.kt:366)
	... 39 more

**Comment by bpepmiller** [comment]
Thank you for adding this bug!

I am experience the same with the following Pycharm version: Build #PY-241.18034.82, built on June 24, 2024

All right-click menus when browsing S3 using the AWS Toolkit Explorer are gone, and I can no longer double-click and open S3 files from the AWS Toolkit Explorer.

AWS Toolkit and Core versions: 3.18-241

**Comment by kumakuma34** [comment]
I'm troubling with exactly same issue 
- JetBrains product: IntelliJ IDEA 2024.1.4 (Ultimate Edition)
using this version 

double-click and open s3 files from AWS Tooklit Exploer is not working

**Comment by nickorka** [comment]
Same issues with S3 in IntelliJ IDEA 2024.1.4 (Ultimate Edition) with AWS Toolkit 3.20-241:

- no context menu
- does not open files by double click
- no upload/download by drug and drop

**Comment by JonJakova** [comment]
Same issue with S3 in `IntelliJ IDEA 2024.1.4 (Ultimate Edition)`.
 
- No right click
- No double click
- No drag/drop

**Comment by tsposato** [comment]
Thanks!
