### ISSUE TITLE
Wrong error shown when language is not supported

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#4929]
```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:77)
	at com.intellij.codeInsight.hint.LocalHintManager.getHintPosition(LocalHintManager.java:347)
	at com.intellij.codeInsight.hint.HintManagerImpl.showInformationHint(HintManagerImpl.java:570)
	at com.intellij.codeInsight.hint.HintManagerImpl.showInformationHint(HintManagerImpl.java:544)
	at com.intellij.codeInsight.hint.HintManagerImpl.showInformationHint(HintManagerImpl.java:531)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.showCodeWhispererInfoHint(CodeWhispererService.kt:758)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.doShowRecommendationsInPopup(CodeWhispererService.kt:177)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService.access$doShowRecommendationsInPopup(CodeWhispererService.kt:93)
	at software.aws.toolkits.jetbrains.services.codewhisperer.service.CodeWhispererService$showRecommendationsInPopup$1.invokeSuspend(CodeWhispererService.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

  amazon.q (3.30-242)
  aws.toolkit (3.30-242)

**Comment by bryceitoc9** [comment]
Appears fixed by https://github.com/aws/aws-toolkit-jetbrains/pull/4946 . Closing.
