### ISSUE TITLE
IllegalStateException: clz.containingFile.virtualFile must not be null

### ISSUE THREAD

**Issue by jarst** [aws/aws-toolkit-jetbrains#494]
I've noticed following stack trace in event log.
Plugin built from commit **e66f0eae6328**

I didn't do anything AWS related, but the AWS credentials were not valid.

```
java.lang.IllegalStateException: clz.containingFile.virtualFile must not be null
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.findByClass(JavaLambdaHandlerResolver.kt:131)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.access$findByClass(JavaLambdaHandlerResolver.kt:25)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:58)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:25)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:291)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.determineHandler(JavaLambdaHandlerResolver.kt:56)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:60)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver$determineHandler$1.compute(JavaLambdaHandlerResolver.kt:25)
	at com.intellij.openapi.project.DumbService.computeWithAlternativeResolveEnabled(DumbService.java:291)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaHandlerResolver.determineHandler(JavaLambdaHandlerResolver.kt:56)
	at software.aws.toolkits.jetbrains.services.lambda.upload.LambdaLineMarker.getLineMarkerInfo(LambdaLineMarker.kt:45)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:174)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by awschristou** [comment]
Hi @jarst thank you for providing the stack trace.

Do you happen to know which file was open when the error occurred, and if there was anything interesting about the code contained within? (for example, a nested class or something)

**Comment by abrooksv** [comment]
Should be fixed in tip of master
