### ISSUE TITLE
Intellij - Amazon Q plugin stopped working 

### ISSUE THREAD

**Issue by KameshAnandan** [aws/aws-toolkit-jetbrains#5005]
**Describe the bug**
Amazon Q stopped working, its not responding and I see the below in stacktrace.

**To reproduce**

Just Launch the Amazon Q, after successful sign in.

**Expected behavior**

![image](https://github.com/user-attachments/assets/5bf07ad8-6a3d-4de6-8635-6ae9d15aba86)

Hi, when I launch Amazon Q from my intellij , Its is not responding to any of my queries.

Unhandled exception in [ComponentManager(ProjectImpl@282035062), CoroutineName(software.aws.toolkits.jetbrains.services.amazonq.toolwindow.AmazonQToolWindow), Dispatchers.Default]

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `software.aws.toolkits.jetbrains.services.cwc.messages.IncomingCwcMessage$ChatPrompt`: Argument #0 of constructor [constructor for `software.aws.toolkits.jetbrains.services.cwc.messages.IncomingCwcMessage$ChatPrompt` (4 args), annotations: [null] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadTypeDefinition(DeserializationContext.java:1865)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addImplicitConstructorCreators(BasicDeserializerFactory.java:605)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:301)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:222)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:450)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:394)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:295)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:273)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:173)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:5036)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4881)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3035)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3499)
	at software.aws.toolkits.jetbrains.services.amazonq.commands.MessageSerializer.deserialize(MessageSerializer.kt:34)
	at software.aws.toolkits.jetbrains.services.amazonq.webview.BrowserConnector$connect$2$1$2$1.invokeSuspend(BrowserConnector.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@282035062), CoroutineName(software.aws.toolkits.jetbrains.services.amazonq.toolwindow.AmazonQToolWindow), StandaloneCoroutine{Cancelled}@41deb02b, Dispatchers.Default]

**Your Environment**
- OS: Windows 
- JetBrains product: Intellij
- JetBrains product version: IntelliJ IDEA 2024.2.4 (Ultimate Edition)
- AWS Toolkit version: 3.34-242
- SAM CLI version: SAM CLI, version 1.116.0
- JVM/Python version: Java 21
- Amazon Q version - 3.34-242

**Additional context**

**Comment by lwoggardner** [comment]
I'm getting this same issue in RubyMine.

Toolkit: Amazon Q For JetBrains 3.37-242
OS: Linux 6.8.0-47-generic
IDE: RubyMine 242

**Comment by lwoggardner** [comment]
Workaround got it back for me. Disable all the AWS plugins and shutdown Intellij.   
In the Intellij install directory (.local/share/JetBrains/RubyMine2024.2 for me)  force remove the following directories

- plugin-amazonq
- plugin-core
- aws-toolkit-jetbrains-standalone

Then restart and reinstall the plugins.

Possibly only a subset of those need reinstalling.

**Comment by aseemxs** [comment]
Please try the latest update, let us know if this is still an issue.
