### ISSUE TITLE
Toolkit: ActionGroup should be registered using <group> tag

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#5012]
v3.34

```
com.intellij.diagnostic.PluginException: ActionGroup should be registered using <group> tag: id="aws.toolkit.dynamoViewer.changeMaxResults" class="software.aws.toolkits.jetbrains.services.dynamodb.editor.actions.ConfigureMaxResultsAction" [Plugin: aws.toolkit]
	at com.intellij.openapi.actionSystem.ActionStub.initAction(ActionStub.java:108)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1696)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.getAction(ActionManagerImpl.kt:2173)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$getAction(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:411)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2.invokeSuspend(ActionAsyncProvider.kt:378)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2.invoke(ActionAsyncProvider.kt)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2.invoke(ActionAsyncProvider.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider.loadAction(ActionAsyncProvider.kt:377)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider.access$loadAction(ActionAsyncProvider.kt:35)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1$1.emit(Emitters.kt:220)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$filter$1$2.emit(Emitters.kt:219)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$mapNotNull$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:114)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$mapNotNull$1.collect(SafeCollector.common.kt:112)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$filter$1.collect(SafeCollector.common.kt:112)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1.invokeSuspend(Emitters.kt:36)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1.invoke(Emitters.kt)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1.invoke(Emitters.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:191)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:153)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

```

**Comment by rainer-wei** [comment]
Also happening in version `3.42-243`

**Comment by sam5827** [comment]
I keep having this issue every time I open the IDE for the first time as well.

<details>
<summary>Version details</summary>
<pre>
IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 5.4.0-200-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 1338M
Cores: 3
Registry:
	ide.experimental.ui=true
	i18n.locale=
Non-Bundled Plugins:
	...
	aws.toolkit.core (3.42-243)
	AWSCloudFormation (243.21565.122)
	...
	com.jetbrains.jax.ws (243.21565.129)
	com.intellij.spring.shell (243.21565.129)
	org.jetbrains.plugins.gitlab (243.21565.204)
	org.jetbrains.plugins.github (243.21565.204-ultimate)
	...
	aws.toolkit (3.42-243)
Kotlin: 243.21565.193-IJ
Current Desktop: ubuntu:GNOME
</pre>
OS: Ubuntu 20.04.6 LTS
</details>
