### ISSUE TITLE
Closing project throws exception from Q EncoderServer

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#5014]
v.3.34

```
Project Project(name=aws-toolkit-common, containerState=COMPONENT_CREATED, componentStore=/Users/richali/idetools/aws-toolkit-common): scope was not completed in 10s

java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:130)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:388)
	at com.intellij.ide.ShutdownKt$cancelAndTryJoin$5$dumpJob$1.invokeSuspend(shutdown.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

```

```
- "ProjectImpl@1159132909 container":supervisor:ChildScope{Cancelling} [ComponentManager(ProjectImpl@1159132909), com.intellij.codeWithMe.ClientIdContextElementPrecursor@2546b07c]
	- "(ProjectImpl@1159132909 x amazon.q)":supervisor:ChildScope{Cancelling} [ComponentManager(ProjectImpl@1159132909), com.intellij.codeWithMe.ClientIdContextElementPrecursor@2546b07c]
		- "software.aws.toolkits.jetbrains.services.amazonq.project.ProjectContextController":supervisor:ChildScope{Cancelling} [ComponentManager(ProjectImpl@1159132909), com.intellij.codeWithMe.ClientIdContextElementPrecursor@2546b07c]
			- "software.aws.toolkits.jetbrains.services.amazonq.project.ProjectContextController":StandaloneCoroutine{Cancelling}, state: RUNNING [ComponentManager(ProjectImpl@1159132909), com.intellij.codeWithMe.ClientIdContextElementPrecursor@2546b07c, Dispatchers.Default]
				at java.base/jdk.internal.misc.Unsafe.park(Native Method)
				at java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
				at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
				at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1099)
				at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:87)
				at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:79)
				at com.intellij.execution.process.ProcessHandler.waitFor(ProcessHandler.java:96)
				at com.intellij.execution.process.BaseOSProcessHandler.waitFor(BaseOSProcessHandler.java:163)
				at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:96)
				at software.aws.toolkits.jetbrains.services.amazonq.project.EncoderServer.runCommand(EncoderServer.kt:105)
				at software.aws.toolkits.jetbrains.services.amazonq.project.EncoderServer.start(EncoderServer.kt:144)
				at software.aws.toolkits.jetbrains.services.amazonq.project.EncoderServer.downloadArtifactsAndStartServer(EncoderServer.kt:64)
				at software.aws.toolkits.jetbrains.services.amazonq.project.ProjectContextController$initJob$1.invokeSuspend(ProjectContextController.kt:30)

```

**Comment by ecerzel** [comment]
I'm experiencing the same issue - as IntelliJ IDEA hang on every 'Project Close':
(IntelliJ IDEA version is 2023.3.4 Ultimate and Amazon Q Plugin 3.35-233 AWS)

- "ProjectImpl@362326873 container":supervisor:ChildScope{Cancelling}
        - "(ProjectImpl@362326873 x amazon.q)":supervisor:ChildScope{Cancelling}
                - "software.aws.toolkits.jetbrains.services.amazonq.project.ProjectContextController":supervisor:ChildScope{Cancelling}
                        - "software.aws.toolkits.jetbrains.services.amazonq.project.ProjectContextController":StandaloneCoroutine{Cancelling}, state: RUNNING [Dispatchers.Default]
                                at java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
                                at java.base@17.0.10/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
                                at java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
                                at java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
                                at com.intellij.util.concurrency.Semaphore.waitForUnsafe(Semaphore.java:87)
                                at com.intellij.util.concurrency.Semaphore.waitFor(Semaphore.java:79)
                                at com.intellij.execution.process.ProcessHandler.waitFor(ProcessHandler.java:96)
                                at com.intellij.execution.process.BaseOSProcessHandler.waitFor(BaseOSProcessHandler.java:163)
                                at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:95)
                                at software.aws.toolkits.jetbrains.services.amazonq.project.EncoderServer.runCommand(EncoderServer.kt:101)
                                at software.aws.toolkits.jetbrains.services.amazonq.project.EncoderServer.start(EncoderServer.kt:140)
                                at software.aws.toolkits.jetbrains.services.amazonq.project.EncoderServer.downloadArtifactsAndStartServer(EncoderServer.kt:60)
                                at software.aws.toolkits.jetbrains.services.amazonq.project.ProjectContextController$1.invokeSuspend(ProjectContextController.kt:24)

**Comment by rli** [comment]
This issue requires users to completely restart the IDE in instances where closing/reopening the project would resolve IDE errors. This is also likely related to another issue where the IDE hangs for a significant amount of time when the user is trying to exit their IDE.
