### ISSUE TITLE
Amazon Q chat does not work at all

### ISSUE THREAD

**Issue by CatDogFishFrog** [aws/aws-toolkit-jetbrains#5042]
**Describe the bug**
Amazon Q chat does not work at all. No matter what I write to him, he just doesn't respond, ever. Sometimes there is an error at this point, but it is very rare. At the same time, CodeWhisperer works. Only the chat doesn't work.

**To reproduce**
1. Launch the IDE and open the Amazon Q chat
2. Write something in the chat, for example, “Hello”
3. Result: Nothing happens

**Expected behavior**
Chat should give at least some kind of answer, at least say something like “I can't help you.” 

**Screenshots**
![image](https://github.com/user-attachments/assets/716f7e74-a851-4018-85fa-267ba6f69878)

**Your Environment**
- OS: Windows 10 22H2 19045.4957
- JetBrains product: PyCharm 2024.2.4
- JetBrains product version: Build #PY-242.23726.102, built on October 22, 2024
- AWS Toolkit version: 3.37-242
- SAM CLI version:
- JVM/Python version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9) / Python 3.12.3

**Additional context**
```
Unhandled exception in [ComponentManager(ProjectImpl@946777978), CoroutineName(software.aws.toolkits.jetbrains.services.amazonq.toolwindow.AmazonQToolWindow), Dispatchers.Default]

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `software.aws.toolkits.jetbrains.services.cwc.messages.IncomingCwcMessage$ChatPrompt`: Argument #0 of constructor [constructor for `software.aws.toolkits.jetbrains.services.cwc.messages.IncomingCwcMessage$ChatPrompt` (4 args), annotations: [null] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadTypeDefinition(DeserializationContext.java:1865)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addImplicitConstructorCreators(BasicDeserializerFactory.java:605)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:301)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:222)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:450)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:394)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:295)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:273)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:173)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:5036)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4881)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3035)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3499)
	at software.aws.toolkits.jetbrains.services.amazonq.commands.MessageSerializer.deserialize(MessageSerializer.kt:34)
	at software.aws.toolkits.jetbrains.services.amazonq.webview.BrowserConnector$connect$2$1$2$1.invokeSuspend(BrowserConnector.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@946777978), CoroutineName(software.aws.toolkits.jetbrains.services.amazonq.toolwindow.AmazonQToolWindow), StandaloneCoroutine{Cancelled}@233bd890, Dispatchers.Default]
```

**Comment by ffigorsonntag** [comment]
Can confirm the same issue for IntelliJ version 2024.3.1.1

`Unhandled exception in [ComponentManager(ProjectImpl@1550088374), com.intellij.codeWithMe.ClientIdContextElementPrecursor@11bb97e3, CoroutineName(software.aws.toolkits.jetbrains.services.amazonq.toolwindow.AmazonQToolWindow), Dispatchers.Default]

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `software.aws.toolkits.jetbrains.services.cwc.messages.IncomingCwcMessage$ChatPrompt`: Argument #0 of constructor [constructor for `software.aws.toolkits.jetbrains.services.cwc.messages.IncomingCwcMessage$ChatPrompt` (4 args), annotations: [null] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadTypeDefinition(DeserializationContext.java:1865)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addImplicitConstructorCreators(BasicDeserializerFactory.java:605)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:301)
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:222)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:262)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:151)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:450)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:394)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:295)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:273)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:173)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:669)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:5036)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4881)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3035)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3499)
	at software.aws.toolkits.jetbrains.services.amazonq.commands.MessageSerializer.deserialize(MessageSerializer.kt:34)
	at software.aws.toolkits.jetbrains.services.amazonq.webview.BrowserConnector$connect$2$1$5$1.invokeSuspend(BrowserConnector.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@1550088374), com.intellij.codeWithMe.ClientIdContextElementPrecursor@11bb97e3, CoroutineName(software.aws.toolkits.jetbrains.services.amazonq.toolwindow.AmazonQToolWindow), StandaloneCoroutine{Cancelled}@44ef34a2, Dispatchers.Default]
`

**Comment by jakob-keller** [comment]
We are also affected by this annoying issue:
* PyCharm 2024.3.2 (Professional Edition)
* Amazon Q plugin 3.52-243
* macOS Sequoia 15.3 (M2 Pro)

**Comment by jakob-keller** [comment]
At least for me, the root cause appeared to have been an incompatibility with the [EmmyLua plugin](https://plugins.jetbrains.com/plugin/9768-emmylua). If you are also using that, please try to disable EmmyLua, restart your IDE and report if that helps. I've also taken steps to inform the Amazon Q team through AWS Support channels. Maybe the can figure out a way to restore compatibility.

**Comment by trevorijones** [comment]
@jakob-keller Thank you. Disabling the EmmyLua plugin solved this issue for me!

**Comment by aseemxs** [comment]
Please try the latest update, let us know if this is still an issue.
