### ISSUE TITLE
Failed to run security scan and display results

### ISSUE THREAD

**Issue by TinMTC** [aws/aws-toolkit-jetbrains#5126]
Failed to run security scan and display results. Caused by: Amazon Q: The selected file exceeds the input artifact limit. Try again with a smaller file. For more information about scan limits, see the Amazon Q documentation. , status code: null, exception: CodeWhispererCodeScanException, request ID: nullJetbrains IDE: PhpStorm 2024.3, IDE version: PS-243.21565.202, 

software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanException: Amazon Q: The selected file exceeds the input artifact limit. Try again with a smaller file. For more information about scan limits, see the Amazon Q documentation. 
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanExceptionKt.cannotFindBuildArtifacts(CodeWhispererCodeScanException.kt:22)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.sessionconfig.CodeScanSessionConfig.createPayload(CodeScanSessionConfig.kt:115)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanSession$run$2.invokeSuspend(CodeWhispererCodeScanSession.kt:99)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanSession$run$2.invoke(CodeWhispererCodeScanSession.kt)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanSession$run$2.invoke(CodeWhispererCodeScanSession.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:74)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:43)
	at kotlinx.coroutines.time.TimeKt.withTimeout(Time.kt:42)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanSession.run(CodeWhispererCodeScanSession.kt:98)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanManager$launchCodeScanCoroutine$1$3.invokeSuspend(CodeWhispererCodeScanManager.kt:254)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanManager$launchCodeScanCoroutine$1$3.invoke(CodeWhispererCodeScanManager.kt)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanManager$launchCodeScanCoroutine$1$3.invoke(CodeWhispererCodeScanManager.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:74)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:43)
	at kotlinx.coroutines.time.TimeKt.withTimeout(Time.kt:42)
	at software.aws.toolkits.jetbrains.services.codewhisperer.codescan.CodeWhispererCodeScanManager$launchCodeScanCoroutine$1.invokeSuspend(CodeWhispererCodeScanManager.kt:250)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

---
Toolkit: Amazon Q For JetBrains 3.41-243
OS: Linux 6.8.0-49-generic
IDE: PhpStorm 243

**Comment by rli** [comment]
As stated by the error, your project exceeds service limits documented on https://docs.aws.amazon.com/amazonq/latest/qdeveloper-ug/security-scans.html#quotas
