### ISSUE TITLE
intelliJ Idea 2024.2.5 Plugin doesn't load

### ISSUE THREAD

**Issue by 0618** [aws/aws-toolkit-jetbrains#5139]
**Describe the bug**

From today, I started seeing the IDE error. And intelliJ also flash quit. 

**To reproduce**
No steps

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/2c5dae97-2150-41f3-b107-42f5eb0d7b30)

**Your Environment**
- OS: macOS
- JetBrains product: intelliJ Idea
- JetBrains product version: 2024.2.5
- AWS Toolkit version:
- SAM CLI version:
- JVM/Python version: 17

**Additional context**

Error detail: 
```
com.intellij.diagnostic.PluginException: Cannot create extension (class=software.aws.toolkits.jetbrains.PluginVersionChecker) [Plugin: aws.toolkit.core]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:980)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:73)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:33)
	at com.intellij.openapi.extensions.impl.ExtensionPointImplKt.getOrCreateExtensionInstance(ExtensionPointImpl.kt:1058)
	at com.intellij.openapi.extensions.impl.ExtensionPointImplKt.access$getOrCreateExtensionInstance(ExtensionPointImpl.kt:1)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$iterator$2.advanceToNextNonNull(ExtensionPointImpl.kt:291)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$iterator$2.hasNext(ExtensionPointImpl.kt:273)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:816)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader.getAppInitializedListeners(ApplicationLoader.kt:417)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$loadApp$2$appInitListeners$1.invokeSuspend(ApplicationLoader.kt:209)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class software.aws.toolkits.jetbrains.PluginVersionChecker (
  error: software/aws/toolkits/jetbrains/PluginVersionChecker has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=AWS Core, id=aws.toolkit.core, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2024.2/plugins/plugin-core, version=3.42-242, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/Applications/IntelliJ IDEA Ultimate.app/Contents/lib, version=242.24807.4, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/Applications/IntelliJ IDEA Ultimate.app/Contents/lib, version=242.24807.4, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/Applications/IntelliJ IDEA Ultimate.app/Contents/lib, version=242.24807.4, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/Applications/IntelliJ IDEA Ultimate.app/Contents/lib, version=242.24807.4, package=null, isBundled=true), )
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:335)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:179)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1464)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass$default(ComponentManagerImpl.kt:1460)
	at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:887)
	at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:21)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:51)
	... 14 more
Caused by: java.lang.UnsupportedClassVersionError: software/aws/toolkits/jetbrains/PluginVersionChecker has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1108)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:276)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:115)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:240)
	at com.intellij.util.lang.ClassPath.findClassWithoutCache(ClassPath.java:229)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:212)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:330)
	... 20 more
```

**Comment by rli** [comment]
On IDE versions 2024.2.x, we expect the IDE to be using a JRE version of 21.
Please see https://www.jetbrains.com/help/idea/switching-boot-jdk.html
