### ISSUE TITLE
ClassCastException in the plugin for swagger.yaml file

### ISSUE THREAD

**Issue by mogren** [aws/aws-toolkit-jetbrains#554]
**Describe the bug**
When restarting IntelliJ after installing the plugin for the first time, I got this exception.
```
Error while indexing /Volumes/Unix/go/src/github.com/aws/amazon-vpc-cni-k8s/vendor/github.com/docker/docker/api/swagger.yaml
To reindex this file IDEA has to be restarted

java.lang.ClassCastException: org.jetbrains.yaml.psi.impl.YAMLQuotedTextImpl cannot be cast to org.jetbrains.yaml.psi.YAMLMapping
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate$Companion.asResource(YamlCloudFormationTemplate.kt:84)
	at software.aws.toolkits.jetbrains.services.cloudformation.yaml.YamlCloudFormationTemplate$Companion.convertPsiToResource(YamlCloudFormationTemplate.kt:80)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1$1.visitElement(CloudFormationTemplateIndex.kt:64)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at org.jetbrains.yaml.psi.impl.YAMLValueImpl.accept(YAMLValueImpl.java:40)
	at org.jetbrains.yaml.psi.impl.YAMLScalarImpl.accept(YAMLScalarImpl.java:181)
	at org.jetbrains.yaml.psi.impl.YAMLQuotedTextImpl.accept(YAMLQuotedTextImpl.java:286)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:88)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.acceptNode(CloudFormationTemplateIndex.kt:91)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$Companion.access$acceptNode(CloudFormationTemplateIndex.kt:84)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:57)
	at software.aws.toolkits.jetbrains.services.cloudformation.CloudFormationTemplateIndex$getIndexer$1.map(CloudFormationTemplateIndex.kt:27)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:273)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:97)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1668)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1596)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:519)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1555)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1543)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:110)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:230)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
```

**Expected behavior**
The plugin should ignore the swagger file.

**Your Environment**
 - OS: macOS 10.12.6
 - JetBrains' Product: IntelliJ IDEA 2018.2.6 (Ultimate Edition)
 - JetBrains' Product Version: Build #IU-182.5107.16, built on November 6, 2018
 - Toolkit Version:

**Additional context**
Nice that it's written in Kotlin 🙂

**Comment by mogren** [comment]
Hmm, it looks like the[ cast check](https://github.com/aws/aws-toolkit-jetbrains/pull/552/files#diff-ba68b4d53c53cf73467ea5b5c4926bf3R108) should fix it. Is there a later build I could test with?

Thanks!
