### ISSUE TITLE
Local Lambda Invokes are missing env vars

### ISSUE THREAD

**Issue by awschristou** [aws/aws-toolkit-jetbrains#559]
**Describe the bug**

Environment variables are not passed into local Lambda invokes.

**To reproduce**
* Click function gutter icon
* Run Local...
* define MY_PARAM env var
* run
* Error:

```
'MY_PARAM': KeyError
Traceback (most recent call last):
  File "/var/task/app.py", line 14, in lambda_handler
    print ('My Param: ' + os.environ['MY_PARAM'])
  File "/var/lang/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'MY_PARAM'
```

**Expected behavior**

**Screenshots**

**Your Environment**
 - OS: 
 - JetBrains' Product:
 - JetBrains' Product Version:
 - Toolkit Version:

**Additional context**

Sample Code
```
import json
import os

import requests


def lambda_handler(event, context):
    """Sample pure Lambda function
    """

    try:
        ip = requests.get("http://checkip.amazonaws.com/")
        print ('----------------------------------------')
        print ('My Param: ' + os.environ['MY_PARAM'])
        print ('----------------------------------------')

    except requests.RequestException as e:
        # Send some context about this error to Lambda Logs
        print(e)

        raise e

    return {
        "statusCode": 200,
        "body": json.dumps(
            {"message": "hello world", "location": ip.text.replace("\n", "")}
        ),
    }

```

**Comment by abrooksv** [comment]
The "jit'ed" template for raw lambda invoke needs to include the env vars
