### ISSUE TITLE
Cannot remote invoke Lambda in IntelliJ Ultimate 

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#602]
**Describe the bug**

When I attempt to right-click a remote Lambda function - no Run Remote option is given. An error with the following stack-traces is written to the error-log:

```
update failed for AnAction(com.intellij.execution.actions.RunContextAction) with ID=RunClass

java.lang.UnsupportedOperationException
	at software.aws.toolkits.jetbrains.services.lambda.execution.remote.RemoteLambdaLocation.getAncestors(RemoteLambdaLocation.kt:32)
	at com.intellij.execution.junit.JUnitUtil.getTestClass(JUnitUtil.java:506)
	at com.intellij.plugins.jboss.arquillian.utils.ArquillianUtils.isJunitArquillianEnabled(ArquillianUtils.java:31)
	at com.intellij.plugins.jboss.arquillian.producer.ArquillianInClassConfigurationProducer.setupConfigurationFromContext(ArquillianInClassConfigurationProducer.java:28)
	at com.intellij.plugins.jboss.arquillian.producer.ArquillianInClassConfigurationProducer.setupConfigurationFromContext(ArquillianInClassConfigurationProducer.java:14)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:79)
	at com.intellij.execution.junit.JavaRunConfigurationProducerBase.createConfigurationFromContext(JavaRunConfigurationProducerBase.java:69)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:167)
	at com.intellij.execution.actions.PreferredProducerFind.doGetConfigurationsFromContext(PreferredProducerFind.java:108)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:92)
	at com.intellij.execution.actions.PreferredProducerFind.findConfigurationFromContext(PreferredProducerFind.java:133)
	at com.intellij.execution.actions.PreferredProducerFind.createConfiguration(PreferredProducerFind.java:31)
	at com.intellij.execution.actions.ConfigurationContext.createConfiguration(ConfigurationContext.java:147)
	at com.intellij.execution.actions.ConfigurationContext.getConfiguration(ConfigurationContext.java:138)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:193)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:151)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:177)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:295)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:109)
	at software.aws.toolkits.jetbrains.core.explorer.ExplorerToolWindow$createTree$2.invokePopup(ExplorerToolWindow.kt:128)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:40)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6545)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:409)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Steps to reproduce**
1) Install the "JBoss Arquillian Support" plugin
2) Restart IDE
3) Right-click function no longer shows Run Remote and stack-trace written to log

**Screenshots**

<img width="366" alt="screen shot 2018-11-25 at 6 18 30 pm" src="https://user-images.githubusercontent.com/4661536/48989325-8afc5a00-f0de-11e8-86f0-9dc85d2a01a5.png">

**Your Environment**
 - OS: Mac
 - JetBrains' Product: IntelliJ Ultimate
 - JetBrains' Product Version: 2018.3
 - Toolkit Version: 0.3

**Additional context**

**Comment by abrooksv** [comment]
It is our fake PSILocation we use to plug a non-psi element into the RunConfig system....

We could just change it to return an empty Iterator and be good.
