### ISSUE TITLE
Plugin 'aws.toolkit' failed to initialize, in IntelliJ IDEA, possible AWS-ADFS config problem/feature req?

### ISSUE THREAD

**Issue by djmrr** [aws/aws-toolkit-jetbrains#842]
Hey there!
I really dig that there is a plugin for AWS for IntelliJ IDEA in development!

I am able to launch IntelliJ IDEA, with the plugin enabled, with a config file that looks something like this (with an empty, non-existent, or populated: ~/.aws/credentials file):
```
[default]
region=us-west-2
output=json
```
But, as soon as my configuration file holds the format needed for our active directory federation system, leveraging aws-adfs ( https://github.com/venth/aws-adfs )
[I build the ~/.aws/credentials file with: aws-adfs login --profile=master --adfs-host=adfs.SITE.com --ssl-verification --session-duration 14400]
 like this
[probably the adfs_config.ssl_verification && adfs_config.role_arn ?] :
```
[default]
region=us-west-2
output=json

[profile master]
region = us-west-2
output = text
adfs_config.ssl_verification = True
adfs_config.role_arn = arn:aws:iam::XXXXXXXXXXXX:role/AD_DeveloperRole
  
[profile shared]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DeveloperRole
source_profile = master
output = text
region = us-west-2
  
[profile audit]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DeveloperRole
source_profile = master
region = us-west-2
  
[profile sbx]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DeveloperRole
source_profile = master
region = us-west-2
  
[profile development]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DeveloperRole
source_profile = master
region = us-west-2
  
[profile stage]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DeveloperRole
source_profile = master
region = us-west-2
  
[profile prod]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DeveloperRole
source_profile = master
region = us-west-2
 
[profile ops]
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DeveloperRole
source_profile = master
region = us-west-2
```
I end up seeing this spit back upon launch:
```
Plugin 'aws.toolkit' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: Could not initialize class software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.lambda$mergeChildDefaults$0(AwsDefaultClientBuilder.java:110)
    at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
    at software.amazon.awssdk.core.client.config.SdkClientConfiguration.merge(SdkClientConfiguration.java:67)
    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.mergeChildDefaults(AwsDefaultClientBuilder.java:108)
    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:142)
    at software.amazon.awssdk.services.cognitoidentity.DefaultCognitoIdentityClientBuilder.buildClient(DefaultCognitoIdentityClientBuilder.java:29)
    at software.amazon.awssdk.services.cognitoidentity.DefaultCognitoIdentityClientBuilder.buildClient(DefaultCognitoIdentityClientBuilder.java:22)
    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:118)
    at software.aws.toolkits.core.ToolkitClientManager.createNewClient(ToolkitClientManager.kt:120)
    at software.aws.toolkits.core.ToolkitClientManager$getClient$2.apply(ToolkitClientManager.kt:63)
    at software.aws.toolkits.core.ToolkitClientManager$getClient$2.apply(ToolkitClientManager.kt:28)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
    at software.aws.toolkits.core.ToolkitClientManager.getClient(ToolkitClientManager.kt:63)
    at software.aws.toolkits.jetbrains.services.telemetry.AWSCognitoCredentialsProvider.<init>(CognitoIdentityProvider.kt:98)
    at software.aws.toolkits.jetbrains.services.telemetry.AWSCognitoCredentialsProvider.<init>(CognitoIdentityProvider.kt:41)
    at software.aws.toolkits.jetbrains.services.telemetry.DefaultTelemetryService.<init>(TelemetryService.kt:77)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:210)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
    at org.picocontainer.defaults.BasicComponentParameter.resolveInstance(BasicComponentParameter.java:77)
    at org.picocontainer.defaults.ComponentParameter.resolveInstance(ComponentParameter.java:114)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getConstructorArguments(CachingConstructorInjectionComponentAdapter.java:111)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:82)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:462)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:471)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Thanks again to everyone working on this plugin, I really really really dig that there is something like this out there for IntelliJ IDEA! :) 

Any input would be awesome and I'm also super game to provide more information with whatever!

Thanks again,
-Mike

**Comment by zhangzhx** [comment]
It seems it is a duplicate issue to #836.  Please track that issue instead.

**Comment by djmrr** [comment]
@zhangzhx thanks for the response :) ! 

So I looked into #836  , #767  , and https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes

I'm wondering if then when that is implemented that the config would need to shift to:
```
[profile master]
region = us-west-2
output = text
adfs_config.ssl_verification = True
adfs_config.role_arn = arn:aws:iam::XXXXXXXXXXXX:role/AD_DeveloperRole
credential_process = /Users/my.name/Library/Python/2.7/bin//aws-adfs login --profile=master --adfs-host=adfs.SITE.com --ssl-verification --session-duration 14400
```
updating that config to add that? credential_process ? 

I know that adfs_config.ssl_verification && adfs_config.role_arn are custom configuration properties for aws-adfs, you don't think that those two custom properties would-be/are 'breaking' the functionality of the plugin?

**Comment by abrooksv** [comment]
The plugin has a hard coded list of what it wants/supports, everything else is ignored.

**Comment by djmrr** [comment]
@abrooksv - rad!  that's cool to hear! 
good to know the other stuff is just ignored :)

**Comment by abrooksv** [comment]
Version 1.2 is out and contains a fix for the crash
