### ISSUE TITLE
Unable to login to AWS using tool kit

### ISSUE THREAD

**Issue by kishoreRanganathan** [aws/aws-toolkit-jetbrains#903]
Installed IntelliJ and downloaded the aws plugin and installed the plugin through import from disk option

**Expected behavior**
Should be able to login aws using the credentials file

**Screenshots**

**Your Environment**
 - OS: Windows 10 
 - JetBrains' Product: IntelliJ IDEA
 - JetBrains' Product Version: 2019.1 (Community Edition)
 - Toolkit Version: 1.2
 - SAM CLI Version: SAM CLI, version 0.14.2
 - JVM/Python Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I am working behind a proxy server at my work place. Configured HTTP proxy in Intellij and able to test the same. 

Intellji detected my aws credentials file ,but when i tried to login to AWS  below error occured

**Invalid AWS Credential
Error while validating profile 'Profile:default**

When i click on more info below is the details for the error
**Unable to execute HTTP request: Connect to sts.us-east-1.amazonaws.com:443 [sts.us-east-1.amazonaws.com/54.239.24.200] failed: Connection refused: connect**

Changed logger level of Intellj to debug and was able to see the below lines
**2019-04-11 15:51:42,226 [21842299]  DEBUG - ingHttpClientConnectionManager - Connection request: [route: {s}->https://sts.us-east-1.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50] 
2019-04-11 15:51:42,227 [21842300]  DEBUG - ingHttpClientConnectionManager - Connection leased: [id: 186][route: {s}->https://sts.us-east-1.amazonaws.com:443][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50] 
2019-04-11 15:51:42,227 [21842300]  DEBUG - .impl.execchain.MainClientExec - Opening connection {s}->https://sts.us-east-1.amazonaws.com:443 
2019-04-11 15:51:42,227 [21842300]  DEBUG - ltHttpClientConnectionOperator - Connecting to sts.us-east-1.amazonaws.com/54.239.24.200:443 
2019-04-11 15:51:42,227 [21842300]  DEBUG - ernal.conn.SdkTlsSocketFactory - Connecting socket to sts.us-east-1.amazonaws.com/54.239.24.200:443 with timeout 2000 
2019-04-11 15:51:42,227 [21842300]  DEBUG - ntellij.util.proxy.CommonProxy - CommonProxy.select called for socket://sts.us-east-1.amazonaws.com:443 
2019-04-11 15:51:42,227 [21842300]  DEBUG - util.net.IdeaWideProxySelector - IDEA-wide proxy selector asked for socket://sts.us-east-1.amazonaws.com:443 
2019-04-11 15:51:42,227 [21842300]  DEBUG - util.net.IdeaWideProxySelector - No proxy: not http/https scheme: socket 
2019-04-11 15:51:42,227 [21842300]  DEBUG - ntellij.util.proxy.CommonProxy - CommonProxy.select returns custom proxy for socket://sts.us-east-1.amazonaws.com:443, [DIRECT] 
2019-04-11 15:51:42,900 [21842973]  DEBUG - api.vfs.impl.local.FileWatcher - Not watchable, filtered: C:\Program Files (x86)\Dell SecureWorks\Red Cloak\Known Programs
ClientConnectionManagerFactory - java.lang.reflect.InvocationTargetException
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to sts.us-east-1.amazonaws.com:443 [sts.us-east-1.amazonaws.com/54.239.24.200] failed: Connection refused: connect
** 
I can see that Intellj is trying to connect to AWS using socket and not through HTTPS.

PS
 i have configured my proxy correctly and also was able to connect to AWS through eclipse and ,AWS CLI in the same network  . I have problem only with the Intellj Plugin 

Please advice

**Comment by eburch2** [comment]
https://github.com/aws/aws-toolkit-jetbrains/issues/685
This worked for me

**Comment by kishoreRanganathan** [comment]
> #685
> This worked for me

Thanks for the reply. For some reason i am unable to dowload the AWS toolkit through market place. Hence i downloaded the plugin as zip file as installed.

While trying to use the EAP build facing the same problem

![image](https://user-images.githubusercontent.com/49364269/55963766-1c2e3080-5c7c-11e9-9fbc-046aee7dcc9c.png)

And trace from idea.log is as below

**2019-04-11 17:05:47,914 [26287987]  ERROR - lij.openapi.util.io.StreamUtil - Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset 
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1533)
	at sun.security.ssl.AppInputStream.available(AppInputStream.java:60)
	at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
	at sun.net.www.MeteredStream.available(MeteredStream.java:170)
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:85)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(HttpURLConnection.java:3517)
	at com.intellij.openapi.util.io.StreamUtil.closeStream(StreamUtil.java:147)
	at com.intellij.util.io.HttpRequests$RequestImpl.close(HttpRequests.java:486)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:543)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.downloadPlugin(PluginDownloader.java:239)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:137)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:227)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:114)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:53)
	at com.intellij.ide.plugins.newui.MyPluginModel.lambda$installPlugin$1(MyPluginModel.java:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)**

Apologies for not mentioning about this error earlier . 
I am not sure if fixing this error will help in resolving the aws login error too.

PS. I can download and install other plugins through marketplace , hence i believe my Proxy settings are correct

**Comment by abrooksv** [comment]
It looks like your intellij proxy settings aren't set. Apache is asking intellij for the proxy and intellij is saying don't use one.

'''
2019-04-11 15:51:42,227 [21842300] DEBUG - util.net.IdeaWideProxySelector - IDEA-wide proxy selector asked for socket://sts.us-east-1.amazonaws.com:443
2019-04-11 15:51:42,227 [21842300] DEBUG - util.net.IdeaWideProxySelector - No proxy: not http/https scheme: socket
'''

**Comment by abrooksv** [comment]
Are you using a socks proxy?

**Comment by kishoreRanganathan** [comment]
No I am not using socks proxy. I have only http proxy set. And that seems to be working fine

**Comment by abrooksv** [comment]
Open the HTTP Proxy settings and try to test the connection using the Test Connection box.

**Comment by kishoreRanganathan** [comment]
> Are you using a socks proxy?

Proxy test seems to be ok 
![image](https://user-images.githubusercontent.com/49364269/56091935-2e97ac80-5ebe-11e9-8a20-10e1d1338ee7.png)

**Comment by abrooksv** [comment]
1.3 was released with the proxy support,can you try again?

**Comment by abrooksv** [comment]
Closing due to no response, please re-open if you are still having trouble with 1.3
