### ISSUE TITLE
PyCharm: IDE Fatal Error - Create Project - Found 0 YAML files but only expected 1

### ISSUE THREAD

**Issue by pccornel** [aws/aws-toolkit-jetbrains#905]
**Describe the bug**

After creating an AWS Serverless Application project in PyCharm, I get an error: "Found 0 YAML files but only expected 1."

**To reproduce**

1. Open PyCharm.
2. **File, New Project**.
3. **AWS Serverless Application**, use default project settings, **Create, This Window**.
4. **IDE Error Occured: Click See Details and Submit Report**. Error is: `Found 0 YAML files but only expected 1.` 

**Expected behavior**

No error. 

**Your Environment**

 - OS: Ubuntu Server 18.04.2 LTS
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2019.1
 - Toolkit Version: 1.2 
 - SAM CLI Version: 0.14.2
 - JVM/Python Version: 3.6.7

**Additional context**

A `template.yaml` file does exist in the root of the project.

**Comment by pccornel** [comment]
Fixed in Toolkit Version 1.3-EAP.2019.04.11.

**Comment by DmytroPaliichuk** [comment]
I have faced with the same problem when I try to create new project with SAM template ```AWS SAM DynamoDB Event Example```

**To reproduce**
1. Open **PyCharm**.
2. **File**, **New Projec**t.
3. **AWS Serverless Application**, use default project settings, create new project with SAM template ```AWS SAM DynamoDB Event Example```
4. **IDE Error Occured: Click See Details and Submit Report**. Error is: Found 0 YAML files but only expected 1.


**Expected behavior**
No error.


**Environment**
- SAM CLI, version 0.17.0
- aws-cli/1.16.180 Python/3.7.3 Darwin/17.7.0 botocore/1.12.170
- PyCharm 2018.3.4 (Community Edition)
Build #PC-183.5429.31, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6



**IDE Fatal Errors**
```
java.lang.AssertionError: Found 0 YAML files but only expected 1
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion.getTemplateFromDirectory(SamCommon.kt:148)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectTemplate.createRunConfigurations(SamInitProjectBuilderCommon.kt:58)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectTemplate.postCreationAction(SamInitProjectBuilderCommon.kt:47)
	at software.aws.toolkits.jetbrains.ui.wizard.SamPythonProjectTemplate.postCreationAction(SamInitProjects.kt:73)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectBuilder.runPostModuleCreationStep(SamProjectGeneratorIntelliJShims.kt:97)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectBuilder.setupRootModel(SamProjectGeneratorIntelliJShims.kt:65)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator$generateProject$$inlined$runInEdt$lambda$1.compute(actions.kt:77)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$19(ApplicationImpl.java:1067)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1023)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1067)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:157)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:43)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.lambda$doGenerateProject$2(AbstractNewProjectStep.java:189)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:260)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:194)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$AbstractCallback.consume(AbstractNewProjectStep.java:148)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.actionPerformed(ProjectSettingsStepBase.java:135)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by zhangzhx** [comment]
Hi @DmytroPaliichuk,

This seems to be the same to #1042 for DynamoDB template of Python. This was fixed in the latest [EAP version](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/65083). Feel free to give it a try and let us know if you still see this problem.
