### ISSUE TITLE
Error running '[Local] HelloWorldFunction': Failed to locate module for PyFile:app.py

### ISSUE THREAD

**Issue by techandtools** [aws/aws-toolkit-jetbrains#920]
**Describe the bug**
Local execution of a Lambda function in Pycharm (using the AWS toolkit plugin) fails on OS X. Pycharm is unable to locate the Python module.
Docker is installed on the platform and "/Applications" has been added under "file sharing". 

**To reproduce**
1. Install the local AWS and SAM CLI on OS X.
2. Install the AWS Toolkit plugin in Pycharm (2019.1.1 professional edition) on OS X.
3. Create a new "AWS Serverless Application", using the "AWS SAM Hello World" template.
4. Go to the "template.yaml" file. From there execute "run '[Local] HelloWorldFunction'".
5. Pycharm reports the error "Error running '[Local] HelloWorldFunction': Failed to locate module for PyFile:app.py".

**Expected behavior**
I expected the Docker container to be launched and the function to be executed.

**Screenshots**
<img width="519" alt="Screenshot 2019-04-17 at 14 46 39" src="https://user-images.githubusercontent.com/25323954/56346526-969e0980-61c2-11e9-9d88-685378140186.png">

**Your Environment**
 - OS: OS X 10.14.1
 - JetBrains' Product: PyCharm
 - JetBrains' Product Version: 2019.1.1 Professional Edition
 - Toolkit Version: 1.2
 - SAM CLI Version: 1.15.0
 - JVM/Python Version: Python 3.6

**Additional context**
* I created multiple projects using the AWS toolkit plugin. Strangely enough I am able to exectute the function in only one of these projects.
* A Lambda icon should appear in front of each Lambda function. I need to close the project and re-open it before the icon appears.

**Comment by techandtools** [comment]
Some additional info. Upon creation of a new project in Pycharm I get the following error:
```
java.lang.AssertionError: Found 0 YAML files but only expected 1
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion.getTemplateFromDirectory(SamCommon.kt:143)
	at software.aws.toolkits.jetbrains.services.lambda.sam.SamCommon$Companion.setSourceRoots(SamCommon.kt:169)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectBuilder.setupRootModel(SamProjectGeneratorIntelliJShims.kt:63)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator$generateProject$$inlined$runInEdt$lambda$1.compute(actions.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$19(ApplicationImpl.java:1064)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1020)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1064)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:154)
	at software.aws.toolkits.jetbrains.ui.wizard.SamProjectGenerator.generateProject(SamProjectGenerator.kt:42)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.lambda$doGenerateProject$2(AbstractNewProjectStep.java:202)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:266)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:207)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$AbstractCallback.consume(AbstractNewProjectStep.java:161)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.actionPerformed(ProjectSettingsStepBase.java:135)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:686)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:688)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:427)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
	at com.jetbrains.python.newProject.PyCharmNewProjectAction.actionPerformed(PyCharmNewProjectAction.java:13)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(Unknown Source)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(Unknown Source)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(Unknown Source)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by zhangzhx** [comment]
It seems a dup to this one https://github.com/aws/aws-toolkit-jetbrains/issues/856. This should be fixed from the latest release of [version 1.3](https://plugins.jetbrains.com/plugin/11349-aws-toolkit/update/61424). Can you try the new version?

**Comment by techandtools** [comment]
Dear,

Thanks a lot for looking into this. I installed version 1.3 of the plugin. Now things seem to work fine for new projects generated with this version of the plugin.

Projects created with the previous version of the plugin still suffer from the issue, but that is ok..

Best regards,
Sven.

**Comment by zhangzhx** [comment]
Glad to hear that. Closing this issue as it is working in the new version. Feel free to reopen it if you have more questions.

**Comment by Rubyj** [comment]
I still get this error with a codUri of . and a Handler of `app.lambda_handler` and I am on 1.4 EAP

**Comment by zhangzhx** [comment]
Hi @Rubyj, this [change](https://github.com/aws/aws-toolkit-jetbrains/commit/e79b7b05146adcc9195c933cb567a68b1dd37cf5) should fix your problem. It has not been released into the eap channel yet. Can you try a local build and install from disk to see if it works? You can follow the [instructions](https://github.com/aws/aws-toolkit-jetbrains/blob/master/CONTRIBUTING.md) here to build from source.

**Comment by Rubyj** [comment]
@zhangzhx sorry. By EAP I meant I built from source. I am the one who requested that change. It looks like by creating a new project with the new version it now works as mentioned above.
