### ISSUE TITLE
IllegalStateException after update to AWS Toolkit 1.3

### ISSUE THREAD

**Issue by ronakcshah** [aws/aws-toolkit-jetbrains#935]
**Plugin exception after update to Toolkit 1.3**
Everytime I try to run the function locally, keep getting IllegalStateException.

**Screenshots**
![Screen Shot 2019-04-29 at 2 43 38 PM](https://user-images.githubusercontent.com/5214360/56929041-7b1de300-6a8d-11e9-9bc8-d0bd2597ed9c.png)
![Screen Shot 2019-04-29 at 2 43 15 PM](https://user-images.githubusercontent.com/5214360/56929044-7ce7a680-6a8d-11e9-8d83-dead047ee7a2.png)

**Your Environment**
 - OS: MacOS Mojave
 - JetBrains' Product: IntelliJ IDEA
 - JetBrains' Product Version: 2019.1.1
 - Toolkit Version: 1.3
 - SAM CLI Version: 0.15.0
 - JVM/Python Version: 1.8.0_201

**Stacktrace**
java.lang.IllegalStateException: Unable to locate project diretory for Module ''%s''
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaBuilder.getPomLocation(JavaLambdaBuilder.kt:61)
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaBuilder.buildLambda(JavaLambdaBuilder.kt:35)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaBuilderUtils.runSamBuild(LambdaBuilderUtils.kt:133)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaBuilderUtils.access$runSamBuild(LambdaBuilderUtils.kt:32)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaBuilderUtils$buildAndReport$$inlined$runSamBuildInBackground$1.run(LambdaBuilderUtils.kt:177)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by abrooksv** [comment]
Can you describe your setup some more.

Are you using Maven or Gradle?
What does your project layout look like?

This will help us to reproduce the error.

**Comment by ronakcshah** [comment]
Hello, after deleting the template.yaml file and reimporting the project into IntelliJ it is working correctly.
