### ISSUE TITLE
Support JDK 11

### ISSUE THREAD

**Issue by naihuayang** [aws/aws-toolkit-jetbrains#938]
```
Disconnected from the target VM, address: 'localhost:62676', transport: 'socket'
java.lang.UnsupportedClassVersionError: XXXXX/App has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

**Comment by abrooksv** [comment]
Lambda does not run Java 11 code today, you will need to change your bytecode version to be 8 in either Gradle or Maven.

**Comment by puradawid** [comment]
Now Lambda supports Java 11: https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-java-11/

The problem I have faced is inability to set up different `JAVA_HOME` or simply JRE for Maven that runs `sam`. It's relatively easy to do in SAM CLI but I can't find any option in IntelliJ plugin at all, so I have to rely on environmental settings only (which I can't change for specific run configuration).

**Comment by abrooksv** [comment]
We added Java 11 support in verion 1.10 of the toolkit
