### ISSUE TITLE
Error Creating New Lambda Function

### ISSUE THREAD

**Issue by karthiknwo** [aws/aws-toolkit-jetbrains#940]
**Describe the bug**
Error while creating a new Lambda

**To reproduce**

1. Right click on Lambda (AWS Toolkit View) and select 'Create new AWS Lambda...'
2. Fill in all required fields and click on 'Create Function'

**Expected behavior**

**Stacktrace**
java.lang.IllegalStateException: Module ''%s'' is not managed by Maven or Gradle
	at software.aws.toolkits.jetbrains.services.lambda.java.JavaLambdaBuilder.buildLambda(JavaLambdaBuilder.kt:36)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaBuilder.packageLambda(LambdaBuilder.kt:146)
	at software.aws.toolkits.jetbrains.services.lambda.LambdaBuilderUtils$packageAndReport$$inlined$runSamBuildInBackground$1.run(LambdaBuilderUtils.kt:177)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Your Environment**
 - OS: Mac OSX Mojave
 - JetBrains' Product: IntelliJ
 - JetBrains' Product Version:2019.x
 - Toolkit Version: 1.3
 - SAM CLI Version: 0.15.0
 - JVM/Python Version: Java 8

**Additional context**

**Comment by abrooksv** [comment]
Are you using Maven/Gradle? If so, did you import/refresh the project?

**Comment by karthiknwo** [comment]
I don’t use Maven/Gradle. Not sure where the issue is

**Comment by zhangzhx** [comment]
At the moment, the toolkit only supports Maven and Gradle build system for Java. By the way, what build system are you using?

**Comment by DavidRileyZipabout** [comment]
I have the same problem, using SBT within Intellij for a scala project

**Comment by zhangzhx** [comment]
The Toolkit doesn't support SBT build system at the moment. But I think it's good to show the error message in a nice way.

**Comment by breedloj** [comment]
Tracking Scala support in feature request #3045
